### ISSUE TITLE
everyone someone dies and they get revived or they click respawn issue

### ISSUE THREAD

**Issue by konrad50024** [ESX-Org/es_extended#10]
everytime this happens all we get is a black screen and we cant do anything and i havnt changed any of the code and got all the latest scripts

**Comment by nearbyplayer** [comment]
Make sure base events is started.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter

**Comment by AxeriusNetwork** [comment]
Having the same issue.

> Make sure base events is started.

This has been done.
