### ISSUE TITLE
Implement support for weapon attatchments

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/es_extended#100]
- [x] xPlayer functions for removing & adding weapon components https://github.com/ESX-Org/es_extended/commit/caec0579541fa760d7b7af3329da4f7081327cb0
- [ ] remove all components when weapon is dropped
- [ ] transform weapon drops into special esx drops
- [ ] handle possible exceptions

**Comment by Matspyder51** [comment]
https://github.com/Matspyder51/esx_weaponsaccessories
I referenced a lot of accessories for a lot of weapons, if you wan't to take from it instead of rewriting everything

**Comment by ElPumpo** [comment]
Thanks for the help, the config file you had with compatiable attatchments is cool, but I think there's a much better way. Seen the lsv source some time ago and they had a good implementation of weapon attatcments. I'll look into it when the time comes.

ESX does not currently support attatchments at all, nor does the official scripts support them. Even with your script it falls apart when you give a weapon to someone else, etc. We'll have to add extra metadata to weapons, something like `attatchments`

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/caec0579541fa760d7b7af3329da4f7081327cb0
