### ISSUE TITLE
Access denied for command add_principal.

### ISSUE THREAD

**Issue by 16BitShooter** [ESX-Org/es_extended#103]
Everything seems to load like it should in the console, but when some connects to the server it breaks. Once it throws Access denied, other things flood the console as well. Not sure what they mean, or if I just messed up setting it up. I tried to follow the instructions as they where given but I may be missing something. I'm using HeidiSQL for my database, not sure if that's the issue either. Thanks, see ya soon

Loaded System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_2011462917
hitch warning: frame time of 673 milliseconds
Loaded System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_2011462917
Connecting: Shooter
Sending heartbeat to live-internal.fivem.net:30110
Sending player (1) ELS data
Access denied for command add_principal.
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:351: server/main.lua:162: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:162: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
[ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM `users` WHERE `identifier` = @identifier {@identifier=steam:110000116f052ff}"

**Comment by Tanoshi-Shinto** [comment]
Theres a sql error. so it may not be connecting to database or something else maybe

**Comment by ElPumpo** [comment]
Install ESX properly
