### ISSUE TITLE
attempt to compare number with nil

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/es_extended#107]
`Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:326: attempt to compare number with nil
stack traceback:
	server/main.lua:326: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>`

On the line "server/main.lua:326" i have if itemCount > 0 and sourceItem.count >= itemCount then ...

How can i fix it?

**Comment by ElPumpo** [comment]
When does this happen?

**Comment by JaroSound** [comment]
I have no idea, i just have this massage random in my log file.

**Comment by ElPumpo** [comment]
It has been fixed...

**Comment by luannf** [comment]
como?
