### ISSUE TITLE
Error when player dies (client side)

### ISSUE THREAD

**Issue by djowdobom** [ESX-Org/es_extended#108]
I have this error, when someone dies for pvp, I'm hoping to get some help here : 

https://ibb.co/nMnanT

And the client : 

`	if killerPed ~= -1 then -- if the killer isn't AI
		local killerCoords = GetEntityCoords(killerPed)
		local distance     = GetDistanceBetweenCoords(table.unpack(killerCoords), table.unpack(data.victimCoords), false)`

the player who is killed by another, does not trigger esx_ambulancejob,
i'm running both of them from esx-org.

**Comment by ElPumpo** [comment]
What line?

**Comment by djowdobom** [comment]
extended/ main.lua109

**Comment by ElPumpo** [comment]
Shit, investigating!

**Comment by ElPumpo** [comment]
Fixed in latest commit
