### ISSUE TITLE
i have this error

### ISSUE THREAD

**Issue by funzik** [ESX-Org/es_extended#11]
[    893218] Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes

**Comment by funzik** [comment]
i have last update but i have this error : 
[    703656] Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:339: attempt to compare number with nil
[    703656] stack traceback:
[    703656] 	server/main.lua:339: in upvalue 'handler'
[    703672] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[    703672] stack traceback:
[    703688] 	[C]: in function 'error'
[    703688] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[    703703] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

**Comment by RomainLanz** [comment]
Hey @funzik 👋 

1. What do you do to get this error?
2. Does all of your ESX resource up to date?

**Comment by funzik** [comment]
i have the same error today :
[   8711078] Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:325: attempt to compare number with nil
[   8711109] stack traceback:
[   8711125] 	server/main.lua:325: in upvalue 'handler'
[   8711125] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[   8711140] stack traceback:
[   8711156] 	[C]: in function 'error'
[   8711156] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[   8711172] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

i have all last ESX resource up to date...
i do nothing when i was this error, i think it's an action of player...
