### ISSUE TITLE
Hotwiring problem

### ISSUE THREAD

**Issue by nykroza** [ESX-Org/es_extended#114]
Since the new updates of the streaming.. everytime we enter a car that we own or not it does the animation of hotwiring the car just like if we were stealing it..

**Comment by ralfaparins** [comment]
I wonder how to fix this...

**Comment by nykroza** [comment]
Anyone has news on how to fix the problem ?

**Comment by SaltyGrandpa** [comment]
How are the cars spawned that need hotwired? Are they purchased at a vehicle dealer? If so, which vehicle dealer script?

**Comment by frayCORE** [comment]
The issue exists irregardless of how the car was spawned in.

Cars from dealership, cars from job scripts, cars from admin commands, cars from garage scripts. All cars require hot wiring. I am not sure if it is something related to es_extended or FiveM.

**Comment by SaltyGrandpa** [comment]
Curious if adding `SetVehicleNeedsToBeHotwired(vehicle, false)` at lines 400 and 435 of client/functions.lua would fix this. More of a work around than anything. This is the only commit I've seen that could have recently impacted this.
https://github.com/ESX-Org/es_extended/commit/74d27e4d807df57c32ce9145ec659d2c48422258#diff-2e4cc1eea04486dac2fb436e0e87a173
