### ISSUE TITLE
Question: displaying money ?

### ISSUE THREAD

**Issue by nykroza** [ESX-Org/es_extended#121]
Hello,

I'm modifying the HUD and I am trying to display the "cash" money.. everything work fine with the bank and black_money but the "cash" money which is in our pocket stay at 0 ..

`if xPlayer.accounts[i].name == 'money' then
    local accountTpl = '$&nbsp;{{money}}&nbsp;&nbsp;&nbsp;&nbsp;'

    ESX.UI.HUD.RegisterElement('account_' .. xPlayer.accounts[i].name, i-1, 0, accountTpl, {
      money = 0
    })

    ESX.UI.HUD.UpdateElement('account_' .. xPlayer.accounts[i].name, {
      money = xPlayer.accounts[i].money
    })
    elseif xPlayer.accounts[i].name == 'bank' then
    local accountTpl = '<img src="img/accounts/' .. xPlayer.accounts[i].name .. '.png"/>&nbsp;{{money}}&nbsp;&nbsp;&nbsp;&nbsp;'

    ESX.UI.HUD.RegisterElement('account_' .. xPlayer.accounts[i].name, i-1, 0, accountTpl, {
      money = 0
    })

    ESX.UI.HUD.UpdateElement('account_' .. xPlayer.accounts[i].name, {
      money = xPlayer.accounts[i].money
    })`

I also added 'cash' in the config.accounts

**Comment by redoper1** [comment]
Have you tried to use `xPlayer.getMoney()`?

**Comment by nykroza** [comment]
Using xPlayer.getMoney() will broke the code and not display cash, bank, black_money

**Comment by redoper1** [comment]
Ok, I will try to come with something else tomorrow after some testing (we have midnight over here).

**Comment by nykroza** [comment]
I am able to display the money with this : ESX.PlayerData.money
but if I buy something or sell something, it does not update, it stay at the amount you were when you logged in

**Comment by nykroza** [comment]
Trying this code insted will work but will duplicate the hud insted of just updating it like bank or black money

`Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0) --le 0 égale 0 miliseconde, donc en gros ça refresh à l'infini ultra rapidement, en d'autre mot, instantanné (mais ça demande quand même +/- beaucoup de ressources)
        if xPlayer.accounts[i].name == 'money' then
            local accountTpl = '<img src="img/accounts/cash.png"/>&nbsp;{{money}}&nbsp;&nbsp;&nbsp;&nbsp;'

            ESX.UI.HUD.RegisterElement(ESX.PlayerData.money, i-1, 0, accountTpl, {
                money = 0
            })

            ESX.UI.HUD.UpdateElement(ESX.PlayerData.money, {
                money = ESX.PlayerData.money
            })
        end
    end
end)`

**Comment by redoper1** [comment]
Sorry, but I had today too much work, so I didn't have time to test it by myself. I will do it tomorrow.

Can you please post a link to your whole file meanwhile?

**Comment by nykroza** [comment]
Inside ES_EXTENDED:

```AddEventHandler('esx:playerLoaded', function(xPlayer)```

I simply added: 

```
    if xPlayer.accounts[i].name == 'money' then
    local accountTpl = '<img src="img/accounts/cash.png"/>&nbsp;{{money}}&nbsp;&nbsp;&nbsp;&nbsp;'

    ESX.UI.HUD.RegisterElement('money', i-1, 0, accountTpl, {
      money = 0
    })

    ESX.UI.HUD.UpdateElement('money', {
      money = xPlayer.money
    })
```

So the money in our pocket is showing insted of using ESSENTIALMODE but the problem is that it's not updating

**Comment by redoper1** [comment]
It looks like the cash can't be shown in 'client' script, but only in 'server' script by the ESSENTIALMODE function like it's in the original. At least I couldn't find another way.

**Comment by nykroza** [comment]
It is strange then.. because if we open our inventory the cash is shown there without any problem and it update once we buy or sell something

**Comment by redoper1** [comment]
Good point, I forgotten about this. I will try to look into it and test it again later today.

**Comment by redoper1** [comment]
It looks like there is used function `xPlayer.getAccount(itemName).money`, but it looks like I will not have time to test it today.

**Comment by nykroza** [comment]
Alight, I am still continuing on my side to try to make it work, no success so far

**Comment by SaltyGrandpa** [comment]
You can use listeners to update your money. esx:setAccountMoney can also be used to listen for dirty money, etc. but I'm only getting bank in this example.

```
local cash = 0
local bank = 0

RegisterNetEvent('esx:setAccountMoney')
AddEventHandler('esx:setAccountMoney', function(account)
    if "bank" == account.name then
		bank = account.money
    end
end)

RegisterNetEvent('es:activateMoney')
AddEventHandler('es:activateMoney', function(e)
	cash = e
end)

RegisterNetEvent("es:addedMoney")
AddEventHandler("es:addedMoney", function(m, native)
	if not native then
		cash = m
	end
end)

RegisterNetEvent("es:removedMoney")
AddEventHandler("es:removedMoney", function(m, native, current)
	if not native then
		cash = m
	end
end)
```

**Comment by nykroza** [comment]
@SaltyGrandpa 

I already have the black money and bank money working with the 

```
    if xPlayer.accounts[i].name == 'bank' then
    local accountTpl = '<img src="img/accounts/' .. xPlayer.accounts[i].name .. '.png"/>&nbsp;{{money}}&nbsp;&nbsp;&nbsp;&nbsp;'

    ESX.UI.HUD.RegisterElement('account_' .. xPlayer.accounts[i].name, i-1, 0, accountTpl, {
      money = 0
    })

    ESX.UI.HUD.UpdateElement('account_' .. xPlayer.accounts[i].name, {
      money = xPlayer.accounts[i].money
    })
    elseif xPlayer.accounts[i].name == 'black_money' then
    local accountTpl = '<img src="img/accounts/' .. xPlayer.accounts[i].name .. '.png"/>&nbsp;<span style="color:red;">{{money}}</span>&nbsp;&nbsp;&nbsp;&nbsp;'

    ESX.UI.HUD.RegisterElement('account_' .. xPlayer.accounts[i].name, i-1, 0, accountTpl, {
      money = 0
    })

    ESX.UI.HUD.UpdateElement('account_' .. xPlayer.accounts[i].name, {
      money = xPlayer.accounts[i].money
    })
    end
```

But if I try to add your code inside es_extended all my money is gone, nothing appear... how would I do it for the wallet money only ?

**Comment by ElPumpo** [comment]
This is not the place to ask questions

**Comment by markmorris** [comment]
also having this issue, no cash gets displayed at all on the latest version.

**Comment by Minimalistic09** [comment]
same here, money not show in hud, only if i restart fivem, i use es_extended final 1
