### ISSUE TITLE
Suggestion: Different HUD Elements.

### ISSUE THREAD

**Issue by Detoxz** [ESX-Org/es_extended#124]
I've noticed that upon modifying the #HUD class, within the CSS file that it modifies the Bank, The Dirty money AND the job. My suggestion/idea was wondering if it'll be possible to separate the sections for more customization such as #HudMoney , #HudJobs , #hudDMoney, as examples

**Comment by TemptressTeelia** [comment]
If you pull request the write up of the suggestion, they might accept it.

**Comment by nykroza** [comment]
Where you able by any chance to show the money you have in your pocket on es_extended ? because it's normally shown by essentialmode ..

**Comment by TemptressTeelia** [comment]
What you mean? Yesterday? I got the wallet to work. But the cash still shows up in hud. I changed the hud css in extended. 
I guess it is essential then. Gotta take a look. Thanks.

**Comment by Detoxz** [comment]
I know where everything is located. Just offering a suggestion regarding more customization due to the fact the div class calls 3 things in one class file

**Comment by nearbyplayer** [comment]
Like he said, if you code it and make a PR we'll be more than glad to merge it, if it's up to our standards.
