### ISSUE TITLE
Spawn point

### ISSUE THREAD

**Issue by Nxssie** [ESX-Org/es_extended#126]
How can i change those random spawn points to only one predefined spawn point?

**Comment by SaltyGrandpa** [comment]
This doesn't have to do with es_extended. Edit the map file you're using, it's very straightforward when you look at the files.

**Comment by Nxssie** [comment]
Does it mean that esx or essentialmode doesn't modify spawnpoints or randomize them?

**Comment by SaltyGrandpa** [comment]
Correct. Aside from from spawning back where you were when you log back in.

**Comment by ElPumpo** [comment]
Not esx related
