### ISSUE TITLE
ex_extended error

### ISSUE THREAD

**Issue by BrianmSK** [ESX-Org/es_extended#127]
Hey guys i have a problem im getting this error on es_extended and other esx scripts... thx for any help.. :)

> Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:307: attempt to index a nil value (local 'xPlayer')
stack traceback:
        server/main.lua:307: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function citizen:/scripting/lua/scheduler.lua:174
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function citizen:/scripting/lua/scheduler.lua:138

**Comment by ElPumpo** [comment]
When do you get this error?

**Comment by KingRyuShin** [comment]
This happen when a player join the server with another steam account, since FiveM block the multi-account it's detecting that the license is already used so the player is being spawn as a NPC and is not able to see the normal HUD or create his character, so it can't pickup his last position

**Comment by Timo972** [comment]
I have gotten the same problem now.
Have you found a way to fix it?

**Comment by ElPumpo** [comment]
> since FiveM block the multi-account it's detecting that the license is already used so the player is being spawn as a NPC and is not able to see the normal HUD or create his character, so it can't pickup his last position

is this a halloween prank?

**Comment by KingRyuShin** [comment]
Uh no ?
With the amount of player that joined my server with another account I know..
They always spawn with npc character, can't use the register, no hud will be displayed but once they return on their main account everything is perfect.

**Comment by ElPumpo** [comment]
ES doesnt support this. Not a bug with ESX

**Comment by joedirt19871** [comment]
SCRIPT ERROR: @es_extended/server/functions.lua:127: attempt to index a nil value (local "xPlayer")

**Comment by JanisSano** [comment]
SCRIPT ERROR: @es_extended/server/main.lua:127: attempt to index a nil value (field '?')
