### ISSUE TITLE
Error es_extended

### ISSUE THREAD

**Issue by btwentyone** [ESX-Org/es_extended#129]
Hello,

 I have a small problem, I have these errors that launches but I can not see where it comes from. Thank you

`Error parsing script server/paycheck.lua in resource es_extended: server/paycheck.lua:47: 'end' expected (to close 'function' at line 3) near <eof> 
Failed to load script server/paycheck.lua. 
Error loading script server/main.lua in resource es_extended: server/main.lua:611: attempt to call a nil value (field 'StartPayCheck') `

and

 `Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: client/main.lua:149: attempt to get length of a nil value (field 'loadout')
 stack traceback:
 	client/main.lua:149: in upvalue 'handler'
 	citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
 stack traceback:
 	[C]: in function 'error'
 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
 	citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
 	[C]: in function 'coroutine.resume'
 	citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
 	citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>`

**Comment by ElPumpo** [comment]
You've modified code
