### ISSUE TITLE
Quelques problèmes

### ISSUE THREAD

**Issue by Pacha78** [ESX-Org/es_extended#13]
Bonsoir, tout d'abord merci de votre partage et bravo pour le boulot que vous avez fait jusqu’à maintenant.

Voila mon problème j'ai installer l'ensemble des scripts fournis sur github
Sans aucunes erreurs 
Et la vient le problème lors de la première connection s'affiche la création d'identité mais lorsque qu'on la rempli rien ne se passe on reste bloquer sur le GUI de création :/
Je précise que au tout début de la création lorsque qu'il y avait seulement es_extended tout fonctionner sauf le menu F2 qui ne se fermer pas non plus ( maudit par les GUI qui se ferme pas )

merci d'avance 
Pacha

**Comment by ElPumpo** [comment]
In English?
