### ISSUE TITLE
Paycheck: isInService

### ISSUE THREAD

**Issue by KingRyuShin** [ESX-Org/es_extended#133]
Hello,
I would like to add that you get your paycheck only if you are in service with the job police, taxi, ambulance, mecano..

I've already added the service system to my job ambulance, taxi, mecano just like the police one and everything work fine.. but now come the time of the paycheck, I'm trying to add this but it doesn't seem to work..

```
				elseif job == 'police' then
				ESX.TriggerServerCallback('esx_service:isInService', function(isInService)
					if isInService then
						xPlayer.addMoney(salary)
						TriggerClientEvent('esx:showAdvancedNotification', xPlayer.source, _U('bank'), _U('received_paycheck'), _U('received_salary', salary), 'CHAR_BANK_MAZE', 9)
						print('Police job paycheck added')
					end
				end, 'police')
```

**Comment by ElPumpo** [comment]
What did you paste? You'll have to use a seperate callback that parses the player id.
