### ISSUE TITLE
Add GetVehicleEngineHealth to ESX.Game.GetVehicleProperties

### ISSUE THREAD

**Issue by benzon** [ESX-Org/es_extended#134]
Hi,

One thing that could be cool to add would be something like saving EngineHealth to the database.

From an RP perspective it would make more sence it saves it to the database, so yoou can actually use it when ppl drives there car in to the garage, and make sure it's still just as broke when they pull it out again.

**Comment by benzon** [comment]
GetVehicleBodyHealth

Could be nice to with out doubt.

**Comment by benzon** [comment]
To get it to work the most optimal way a change of ESX.Game.GetVehicleProperties and ESX.Game.SetVehicleProperties to have these additions added to them, that way you keep the possibility to update and avoide having to anything sketchy.

The change is minor, but would make es_extended support that feature out of the box.

**Comment by benzon** [comment]
The reason i mention it is that something like dirtLevel is actually there as standart, so wondering why something like GetVehicleEngineHealth and GetVehicleBodyHealth is actually not there, since they are 2 car related natives, that would make sence, if something like dirtLevel makes sence :)

**Comment by ElPumpo** [comment]
Did you take look at the function? It returns `dirtLevel` and `health`

**Comment by benzon** [comment]
From what i have noticed the health dos not actually set the propper damage to the car.

Engine and Body Damage would be a more correct way to do it.

**Comment by LuaDeldu** [comment]
I personnaly switched 
`health = GetEntityHealth(vehicle)` 
to 
`health = GetVehicleEngineHealth(vehicle)`

**Comment by benzon** [comment]
Ye i only have bad experience with GetEntityHealth thats why i dont get why it's not using GetVehicleEngineHealth.

since GetEntityHealth will never set the correct value for Body and Engine health from my testings.
