### ISSUE TITLE
Invalid ref call attempt: 13 & 15

### ISSUE THREAD

**Issue by KingRyuShin** [ESX-Org/es_extended#140]
Hello,

So I upgraded everything to work with the new version of mysql-async, but now when I try to do a command like /car it's giving me invalid ref call attempt: 13

and if I do : /dv
I get invalid ref call attempt: 15

If I try /giveitem
I get valid ref call attempt: 25

And it just goes on.. any idea why ?

Edit: I'm on windows

**Comment by Xseba360** [comment]
Can confirm, updated server artifact on linux from `679` to `792`, this resulted in needing to update [fivem-mysql-async](https://github.com/brouznouf/fivem-mysql-async) to latest version (3.0.1), which in turn broke this.

**Comment by benzon** [comment]
@Xseba360 

It''s not broken stop saying that.

You should read the warnings tho.

**

> Warning
> On Linux servers, users need to stick with the old mysql-async 2.x at least for the moment, due to some issues the linux server has with v8/javascript.
> 
> It can be downloaded from https://github.com/brouznouf/fivem-mysql-async/tree/2.0 or the release section. Note that the connection_string is different for 3.0.0 and 2.x.

**

**Comment by Xseba360** [comment]
@benzon i see. updated mysql-async to 3.0.2 and issue seems to be fixed. This can be closed then.

https://github.com/brouznouf/fivem-mysql-async/issues/41

**Comment by KingRyuShin** [comment]
I'm not using linux, i'm on windows dunno for @Xseba360

**Comment by KingRyuShin** [comment]
The last build of FiveM that they put out yesterday seem to have fixed the issues..

**Comment by Xseba360** [comment]
Sadly no linux new linux artifacts

**Comment by ElPumpo** [comment]
It's a problem with fivem and not related to ESX
