### ISSUE TITLE
Server breaks the policy of rules.

### ISSUE THREAD

**Issue by TheMulti808** [ESX-Org/es_extended#141]
Hey guys, i find a server what have changed all 'esx' prefix to 'ess'.  Im not sure but i think it breaks the policy of rules. 
Ip of this server: 137.74.4.165:30120

**Comment by KingRyuShin** [comment]
It doesn't break anything, it can prevent people from using lua_injector program to activate some function..
It act the same as ressources-scrambler lol

But if you read the cache you can't find the function and still use it

**Comment by ElPumpo** [comment]
We don't care.
