### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by taysupra** [ESX-Org/es_extended#142]
I've reinstalled on Debian 9 and Windows 10  all today. I have my inventory menu. but if i go to a shop or policejob or vehicleshop i don't get the menu to go through. my database is linked no issues. no console issues at all. just nothing. the blip is displayed and the icon on the map. it's like somethings turned off. I don't know what else to try. so i feel this is an issue 

`INFO: No channel links found in configuration file.
Resolved live-internal.fivem.net:30110 to 178.32.9.100:30110
Found new resource async in C:/Users\Taylor\Desktop\fmserver\server-data/resources//async
Found new resource esplugin_mysql in C:/Users\Taylor\Desktop\fmserver\server-data/resources//esplugin_mysql
Found new resource essentialmode in C:/Users\Taylor\Desktop\fmserver\server-data/resources//essentialmode
Found new resource es_admin2 in C:/Users\Taylor\Desktop\fmserver\server-data/resources//es_admin2
Found new resource fivem in C:/Users\Taylor\Desktop\fmserver\server-data/resources//fivem
Found new resource fivem-awesome1501 in C:/Users\Taylor\Desktop\fmserver\server-data/resources//fivem-awesome1501
Found new resource fivem-map-hipster in C:/Users\Taylor\Desktop\fmserver\server-data/resources//fivem-map-hipster
Found new resource fivem-map-skater in C:/Users\Taylor\Desktop\fmserver\server-data/resources//fivem-map-skater
Found new resource mysql-async in C:/Users\Taylor\Desktop\fmserver\server-data/resources//mysql-async
Found new resource runcode in C:/Users\Taylor\Desktop\fmserver\server-data/resources//runcode
Found new resource es_extended in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[essential]/es_extended
Found new resource esx_menu_default in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[esx]/esx_menu_default
Found new resource esx_menu_dialog in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[esx]/esx_menu_dialog
Found new resource esx_menu_list in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[esx]/esx_menu_list
Found new resource esx_shops in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[esx]/esx_shops
Found new resource race in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[gamemodes]/race
Found new resource race-test in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[gamemodes]/race-test
Found new resource channelfeed in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[gameplay]/channelfeed
Found new resource irc in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[gameplay]/irc
Found new resource obituary in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[gameplay]/obituary
Found new resource obituary-deaths in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[gameplay]/obituary-deaths
Found new resource playernames in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[gameplay]/playernames
Found new resource mapmanager in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[managers]/mapmanager
Found new resource baseevents in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/baseevents
Found new resource chat in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/chat
Found new resource chat-theme-gtao in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/chat-theme-gtao
Found new resource hardcap in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/hardcap
Found new resource rconlog in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/rconlog
Found new resource scoreboard in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/scoreboard
Found new resource sessionmanager in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/sessionmanager
Found new resource spawnmanager in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/spawnmanager
Found new resource betaguns in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[test]/betaguns
Found new resource gameInit in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[test]/gameInit
Found new resource keks in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[test]/keks
Found new resource yarn in C:/Users\Taylor\Desktop\fmserver\server-data/resources//[system]/[builders]/yarn
Started resource sessionmanager
Started resource mapmanager
Started resource chat
Started resource spawnmanager
Started gametype Freeroam
Started resource fivem
Started resource hardcap
Started resource rconlog
Started resource scoreboard
Started resource playernames
Started resource baseevents
Started resource mysql-async
Started resource essentialmode
Started resource esplugin_mysql
Started resource es_admin2
Started resource async
Started resource es_extended
Started resource esx_menu_default
Started resource esx_menu_list
Started resource esx_menu_dialog
Started resource esx_shops
Authenticating server license key...
Server licensecfx>  key authentication succeeded. Welcome!
Sending heartbeat to live-internal.fivem.net:30110

Current version: 5.0.3
Updater version: 5.0.3

Everything is fine!

Started map fivem-map-skater
Started resource fivem-map-skater
Connecting: MirryKitty
Sending heartbeat to live-internal.fivem.net:30110
Sending heartbeat to live-internal.fivem.net:30110
Sending heartbeat to live-internal.fivem.net:30110
Sending heartbeat to live-internal.fivem.net:30110
[SAVED] MirryKitty
[SAVED] All players`

`# you probably don't want to change these!
# only change them if you're using a server with multiple network interfaces
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

set es_enableCustomData 1
add_ace resource.essentialmode command.add_principal allow

set mysql_connection_string "mysql://Hidden@localhost/hidden?dateStrings=true"

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start playernames

start baseevents

start mysql-async
start essentialmode
start esplugin_mysql
start es_admin2

start es_extended

start esx_menu_default
start esx_menu_list
start esx_menu_dialog
start esx_shops
 
sv_scriptHookAllowed 1

# change this
#rcon_password hidden

# a comma-separated list of tags for your server
# for example: sets tags "drifting, cars, racing" or sets tags "roleplay, military, tanks"
sets tags "default"

# set an optional server info and connecting banner image url.
# size doesn't matter, any banner sized image will be fine.
#sets banner_detail "http://url.to/image.png"
#sets banner_connecting "http://url.to/image.png"

sv_hostname "City Of Lost Dreams RP"

# nested configs!
#exec server_internal.cfg

# loading a server icon (96x96 PNG file)
#load_server_icon myLogo.png

# convars for use from script
set temp_convar "hey world!"

# disable announcing? clear out the master by uncommenting this (your server will not be listed in the serverlist if you uncomment this!)
#sv_master1 ""

# want to only allow players authenticated with a third-party provider like Steam (don't forget, Social Club is a third party probvider too!)?
#sv_authMaxVariance 1
#sv_authMinTrust 5

# add system admins
add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit
add_principal identifier.steam:110000104214ac0 group.admin # add the admin to the group

# remove the # to hide player endpoints in external log output
sv_endpointprivacy true

# server slots limit (must be between 1 and 31)
sv_maxclients 30

# license key for server (https://keymaster.fivem.net)
sv_licenseKey my license key has been hidden for security`

**Comment by mrkersh2019** [comment]
I'm facing the same issue

**Comment by BrickTree** [comment]
myself as well.
this error is thrown in the F8. First at police cloakroom, then at the unicorn.
![menuerror](https://user-images.githubusercontent.com/44795691/48055637-a7f3dc00-e175-11e8-9534-2f201adfde7b.PNG)

**Comment by ElPumpo** [comment]
@BrickTree you get that because you haven't updated esx, dummy. You can't just update policejob and not ESX, ffs.

You'd follow the installation manual then it would work just fine - this isn't related to esx
