### ISSUE TITLE
Vehicle health

### ISSUE THREAD

**Issue by KingRyuShin** [ESX-Org/es_extended#144]
I'm trying to add engineHealth and bodyHealth into the client function so when people take their car out of the garage it keep the damage of their car just like it was..

in GetVehicleProperties
```
		engineHealth      = GetVehicleEngineHealth(vehicle),
		bodyHealth        = GetVehicleBodyHealth(vehicle),
```

in SetVehicleProperties
```
	if props.engineHealth ~= nil then
		SetVehicleEngineHealth(vehicle, props.engineHealth)
	end
 	if props.bodyHealth ~= nil then
		SetVehicleBodyHealth(vehicle, props.bodyHealth)
	end
```

The first time we take our car out of the garage everything is perfect.. but once you store it the bodyhealth is setting itself to 360.0 and enginehealth to 100.0 or 1000.0 (vary)

Even tough you didn't do any damage to the car and happen even when you just repaired it

**Comment by ElPumpo** [comment]
See https://github.com/ESX-Org/es_extended/commit/e850da085e694a17235501873d11635be2fa43c0
