### ISSUE TITLE
after latest commit 4c0f1eb i have this error :

### ISSUE THREAD

**Issue by funzik** [ESX-Org/es_extended#15]
[      2484] Error parsing script locales/fr.lua in resource es_extended: locales/fr.lua:20: invalid escape sequence near ''vous avez reÃ§u une aide de l\Ã'
[      2500] Failed to load script locales/fr.lua.

**Comment by RomainLanz** [comment]
Hey @funzik! 👋

Have you checked the content of the file **locales/fr.lua:20**?
You have probably an issue with the charset set of your files that doesn't handle french accent.

**Comment by RomainLanz** [comment]
Never mind, fixed in https://github.com/ESX-Org/es_extended/commit/9b42c33ae547b6ea77ee899098cc1fe93056cbf9
