### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by mukbang** [ESX-Org/es_extended#151]
When you use a F6 menu and take someone's weapon / items and the dead person will be revived by ambulancejob / /revive. The guy who died have the weapon and the guy who took the weapon.

Sorry for bad english //Pontus

**Comment by ElPumpo** [comment]
Not directly a bug with this resource, see https://github.com/ESX-Org/esx_ambulancejob/issues/71

**Comment by mukbang** [comment]
How to fix the hole thing do?

**Comment by ElPumpo** [comment]
?

**Comment by mukbang** [comment]
How to fix so it dosen’t duplicate?

**Comment by ElPumpo** [comment]
Take it up with the corresponding resource, because it's not esx.
