### ISSUE TITLE
My ESX markers arent working anymore

### ISSUE THREAD

**Issue by itsjeroentje** [ESX-Org/es_extended#155]
At some time i restarted my server and suddenly the ESX markers wouldnt work. I checked the console but it doesnt give errors. I need help with this problem!!!

**Comment by itsjeroentje** [comment]
![image](https://user-images.githubusercontent.com/25204778/47969108-0a17e880-e073-11e8-9eed-8f38a02d2912.png)

**Comment by itsjeroentje** [comment]
these are the errors i get in my F8

**Comment by ElPumpo** [comment]
update esx, and that's not even this resource!
