### ISSUE TITLE
Error with create "data" array after dead by other online player.

### ISSUE THREAD

**Issue by Nowson04** [ESX-Org/es_extended#161]
Hello, maybe i find a bug.

Function ESX.Round from file "shared/functions.lua" required 2 values (line 62), but "AddEventHandler('baseevents:onPlayerKilled', function(killerId, data)" from "client/main.lua" "send" one value - "distance     = ESX.Round(distance)" (line 115).

Error:
https://ibb.co/coSEN0

Have a nice day!

**Comment by ElPumpo** [comment]
That was an issue with old code.
