### ISSUE TITLE
Money color and formatting in inventory BUG?

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/es_extended#166]
![bez tytulu](https://user-images.githubusercontent.com/19697423/48672539-62e98580-eb37-11e8-8041-e69d340cb9e5.png)

There's always a bug according to "dirty money", as you can see there's a decimal point in the amount of dirty money.

**Comment by ElPumpo** [comment]
What formatting? Its because youve entered decimals somehow, we arent fully safe from them yet

**Comment by ElPumpo** [comment]
Make sure esx was updated, we are in fact rounding those values

**Comment by xdrahmahx** [comment]
i have the same issue what can cause this? or is there a fix?
