### ISSUE TITLE
esx_identity problem 

### ISSUE THREAD

**Issue by MaldoNanoche** [ESX-Org/es_extended#176]
Error running system event handling function for resource esx_identity: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_fetch_all in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:143: in field 'fetchAll'
        server/main.lua:8: in function 'getIdentity'
        server/main.lua:208: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
Error resuming coroutine: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_fetch_all in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:143: in field 'fetchAll'
        server/main.lua:155: in local 'task'
        @async/async.lua:67: in local 'processQueue'
        @async/async.lua:86: in field 'parallelLimit'
        @async/async.lua:91: in field 'series'
        server/main.lua:232: in field '?'
        @async/async.lua:21: in function <@async/async.lua:19>
Error resuming coroutine: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_fetch_all in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:143: in field 'fetchAll'
        server/main.lua:65: in field '?'
        @async/async.lua:21: in function <@async/async.lua:19>
Error resuming coroutine: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_fetch_all in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:143: in field 'fetchAll'
        server/main.lua:36: in field '?'
        @async/async.lua:21: in function <@async/async.lua:19>
Error resuming coroutine: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_execute in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:130: in field 'execute'
        server/main.lua:20: in field '?'
        @async/async.lua:21: in function <@async/async.lua:19>
Error running call reference function for resource esx_identity: citizen:/scripting/lua/scheduler.lua:351: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_fetch_all in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:143: in field 'fetchAll'
        server/main.lua:39: in function 'getCharacters'
        server/main.lua:248: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
Error running call reference function for resource essentialmode: citizen:/scripting/lua/scheduler.lua:351: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in upvalue 'callback'
        server/main.lua:186: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>

**Comment by benzon** [comment]
Error resuming coroutine: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_fetch_all in resource mysql-async

Your problem is mysql.
