### ISSUE TITLE
Feature Request: user_inventory in array

### ISSUE THREAD

**Issue by Kevintjuhz** [ESX-Org/es_extended#177]
Right now on our server, our user_inventory table consists of 150k + rows. Because for every single item someone has ever had it stores it. If he doesn't have it it still stays there. I think it would be better to make it a array like was done for the weapons you are carrying. So you only have one row per user to get his inventory. This would reduce mysql and server lagg a lot.

**Comment by ElPumpo** [comment]
This has been discussed in the past,

- storing encoded json text in a database is a bad idea due to how mysql works
- the `json.decode` & `json.encode` functions run on the main server thread

[here's](https://pastebin.com/2sESDeEc) my snippet I used when I tested and my results are this

| default | new  |
|---------|------|
| 2040    | 2321 |

unit: frame time (in ms)

**Comment by Trsak** [comment]
I have changed the code so items are only saved in database, if user have any. This saved like 150k rows on my server.

Part of the code:
```
for i = 1, #xPlayer.inventory, 1 do
		if ESX.LastPlayerData[xPlayer.source].items[xPlayer.inventory[i].name] ~= xPlayer.inventory[i].count then
			table.insert(
				asyncTasks,
				function(cb)
					MySQL.Async.execute(
						"UPDATE user_inventory SET `count` = @count WHERE identifier = @identifier and item = @item",
						{
							["@count"] = xPlayer.inventory[i].count,
							["@identifier"] = xPlayer.identifier,
							["@item"] = xPlayer.inventory[i].name
						},
						function(rowsChanged)
							if rowsChanged == 0 then
								MySQL.Async.execute(
									"INSERT INTO `user_inventory` (count, identifier, item) VALUES (@count, @identifier, @item)",
									{
										["@count"] = xPlayer.inventory[i].count,
										["@identifier"] = xPlayer.identifier,
										["@item"] = xPlayer.inventory[i].name
									},
									function(rowsChanged)
										if cb ~= nil then
											cb()
										end
									end
								)
							else
								cb()
							end
						end
					)
				end
			)

			ESX.LastPlayerData[xPlayer.source].items[xPlayer.inventory[i].name] = xPlayer.inventory[i].count
		end
	end
```

And call
```
	MySQL.Sync.fetchAll('DELETE FROM user_inventory WHERE `count` = 0', {})
```
on MySQL.ready

**Comment by schwim0341** [comment]
Trask, with that code, what happens when a resource tries to work with an item that isn't in the user's inventory table?

**Comment by WhopperDazzle** [comment]
Couldn't this issue be somewhat mitigated if you created two MySQL indexes on ìdentifier` and `item` columns?
