### ISSUE TITLE
Weapons Ammo Not Saving 

### ISSUE THREAD

**Issue by KingOfPower2828** [ESX-Org/es_extended#18]
The Weapon Ammo Resets When Players Relog

**Comment by funzik** [comment]
i have the same problem

**Comment by RomainLanz** [comment]
Should be fixed!

May you confirm?

**Comment by KingOfPower2828** [comment]
i can confirm it has been fixed.

**Comment by RomainLanz** [comment]
Cool 🎉

**Comment by imdylan93** [comment]
I am running into this exact issue, even with an updated build of ESX. Anytime a player relogs, their ammo resets back to full. any fix?

**Comment by NightcoreIsla** [comment]
i get same problem now,
lastest version
