### ISSUE TITLE
MySQL Problems

### ISSUE THREAD

**Issue by WafflezPlayz** [ESX-Org/es_extended#180]
I'm having a few problems trying to hook up ESX to my database. I've put in the connection string as follows:

`set mysql_connection_string "mysql://admin:admin@192.168.0.25/esx?dateStrings=true"`

^^ which I know works because I've used it for something else just fine. The database name is correct as well.

I have installed everything correctly following the Installation instructions **however** my essentialmode still isn't going on to the database. Is this an esplugin_mysql issue that I need to fix?

For the record I'm getting BUFFER_SHORTAGE errors.

**Comment by ElPumpo** [comment]
Ho ho ho.

This is not an ESX issue. The connection string is very wrong too
