### ISSUE TITLE
if more than one player is nearby when giving an item (Bugged)

### ISSUE THREAD

**Issue by benzon** [ESX-Org/es_extended#181]
> if more than one player is nearby when giving an item, show an menu with all players so you can select which player you want to give the item

Sadly this function is flaky, and buggy, we experience quite alot that even tho you select a person it's always the closest one that get's the item.

**Comment by CruelAlpha** [comment]
This is true, it gives the item to the closest person, not the one you press enter on (in the menu)

**Comment by ElPumpo** [comment]
Shit this is because it was never fully implemented.
