### ISSUE TITLE
es_extended main.lua errors

### ISSUE THREAD

**Issue by Valkatastz** [ESX-Org/es_extended#191]
I have encountered some issues on the F8 console, pointing to the line 108 and then 101. On 106 and 108 have # in front of the ESX.Playerdata.loadout which looks like #ESX.Playerdata.loadout. I believe it should not have that #. I've removed it and then I got the following error pointing towards line 101. 
![image](https://user-images.githubusercontent.com/11320138/50582614-ba2f8500-0e5b-11e9-80b1-0e52c027412b.png)

Will be good to investigate this issue.

**Comment by ElPumpo** [comment]
Try the very latest update and report back. Any errors?

**Comment by Valkatastz** [comment]
@ElPumpo Works now flawlessly, great job.

**Comment by ElPumpo** [comment]
Great, dont forget to close the issue next time!
