### ISSUE TITLE
Loadout doesn't load

### ISSUE THREAD

**Issue by johnnypernik** [ESX-Org/es_extended#194]
Hey guys, after "component" update, there is a problem with loadouts, for some player weapons are dissapearing when reconnecting or even when dying.

**Comment by ElPumpo** [comment]
@Valkatastz that was fixed with the latest commit.

**Comment by johnnypernik** [comment]
Nvm, even when we clearloadout and then buy new weapons, they are not saving for some people.

**Comment by CruelAlpha** [comment]
I too seem to have the same issue with weapons.

**Comment by CruelAlpha** [comment]
Specially when transitioning from an older ESX to the newer one, the only weapons that load in is the knife for some odd reason.

**Comment by benzon** [comment]
is this still an issue or ?

**Comment by gelsbern** [comment]
Yes, I have one player who always loses her loadout.  She logs off and the data is in the loadout field on the DB, but as soon as she logs in, it vanishes.
