### ISSUE TITLE
es_extended time warning resource

### ISSUE THREAD

**Issue by Valkatastz** [ESX-Org/es_extended#195]
After being online it starts dropping frames, a message pops up where es_extended has time warning resource and it increase the fps loss with the time. 
![image](https://user-images.githubusercontent.com/11320138/50671106-b7ea3980-0fc7-11e9-8aed-6d243a487068.png) 

It will go away after a relog but it will come back around 10 to 20 minutes and it is increasing and it gets laggy.

**Comment by Valkatastz** [comment]
Also, this error has appeared after stay in game for even longer in the console, turning in game to be unresponsive. Only F8 was working and couldn't do anything but seeing that es_extended time warning resource still taking around -30 fps. 
![unknown](https://user-images.githubusercontent.com/11320138/50672767-e705a880-0fd1-11e9-9e43-447ee687d758.png)

**Comment by Delex21** [comment]
Have you've updated your server and ESX build? If so, how are your hosting specifications?

The error caused in console is harmless. I refer to issue #172 where I posted a statement about this issue.

**Comment by Valkatastz** [comment]
@Delex21 Yeah I did upgraded it. The issue with the weapons has been fixed but I started to have the es_extended resource time warning again like it was before the weapon fix. The 2nd error that occur was after being online for longer waiting that es_extended to go away, it appears on server side since it raised up to 30 and more fps to lose, that caused to go to 10 fps barely playing. 

The hosting machine is:
Xeon E5-2678 v3 @ 2.50 Ghz (8 Core Processor)
12GB of RAM
1GB internet speed
1TB of SSD storage

**Comment by Valkatastz** [comment]
Small update on the console error. It appears if the person die. The ambulancejob fetches the death people but the meaningless errors which are similar to a curl issue appears on the server side console.

**Comment by Valkatastz** [comment]
Okay, I moved the server to VPS now with high-end specs. No single hitch warning, lowered all my resources to 100 but still after playing around 20 to 35 minutes in the server the es_extended is giving time warning resource and starts lowering everyone else's fps by a lot. I tried on a dedicated and VPS server still same issues. The server machine is out of option.

**Comment by schwim0341** [comment]
When the performance drop begins, start shutting down the resources one at a time until the performance is restored.  You'll have found the root of the issue.

**Comment by ElPumpo** [comment]
Not caused by esx. It's one of your resources calling esx functions.

**Comment by DanyCryEn** [comment]
I've resource time warning too es_extended... how i can fix this? i don't know where is the problem... and profiler record command don't work.. (access denied)
