### ISSUE TITLE
Vehicles randomly despawn when abandoned

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/es_extended#196]
Vehicles can disappear even if we stand near them. I'm talking about Police cars taken out of the LSPD garage or even about Private vehicles.

It seems that the function "ESX.Game.SpawnVehicle" does not work properly.

**Comment by originalgenox** [comment]
SetEntityAsMissionEntity(vehicle, true, true)

**Comment by originalgenox** [comment]
Try adding this just for now.

SetEntityAsMissionEntity(vehicle, true, true)

**Comment by JaroSound** [comment]
I've tried it without success...

**Comment by minijoker2o0** [comment]
hi i found out through process of elimination a mod called PVD which stops players getting weapons from police cars causes this deleted it replaced with another mod of same type traffic is back :D

**Comment by benzon** [comment]
Not sure this is a ESX issue to be honest, i think it's more of a ELS issue.

**Comment by FlawwsX** [comment]
Yeah vehicles never actually de spawn for me until I disconnect.

**Comment by bozoweed** [comment]
to be honest it's from fivem, that bug appear when OneSync is out , the networking entity is broken so

**Comment by bozoweed** [comment]
to patch this we need to chek up if car exist else spawn it again  thanks fivem

**Comment by ElPumpo** [comment]
So yes this is not caused by ESX, must be some other script.

**Comment by mmod-max** [comment]
Strange. Sometimes cars despawn even while driving. Happens when someone has very high lag on the server and sometimes when someone joins. I think also it's related to the ls customs, because most of our problems in the server happen when someone is driving a tuned car directly out of customs.
