### ISSUE TITLE
Bug: Online character is not loading

### ISSUE THREAD

**Issue by XarocLP** [ESX-Org/es_extended#205]
Since this afternoon I get this error:
Sending heartbeat to live-internal.fivem.net:30110
[SAVED] All players
Connecting: XarocLP
Performing version check against: https://api.kanersps.pw/em/version?version=6.0.2&uuid=ad3eedd6-60b1-45a5-b7ea-635bf5790990

[EssentialMode] Everything is nice and updated!
Sending heartbeat to live-internal.fivem.net:30110
Connecting: XarocLP
Sending heartbeat to live-internal.fivem.net:30110
Sending player (5) ELS data
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: server/main.lua:169: attempt to index a nil value (field ‘?’)
stack traceback:
server/main.lua:169: in upvalue ‘ref’
citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
[C]: in function ‘xpcall’
citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
[C]: in function ‘error’
citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error: Unhandled error: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
at h (citizen:/scripting/v8/msgpack.js:29:15761)
at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
at unpack (citizen:/scripting/v8/main.js:20:33)
at citizen:/scripting/v8/main.js:51:11
at setImmediate (mysql-async.js:4962:9)
at Object.callback (citizen:/scripting/v8/timer.js:56:6)
Sending heartbeat to live-internal.fivem.net:30110

I can join and play as normal.

Unfortunately, he does not load my character …
Also, my account balance and my job is not displayed.

In addition, I will not be listed on the scoreboard.

For other players everything still works normally.

Xaroc

**Comment by benzon** [comment]
Check what steam acc you use to connect, if you use the wrong one this happens, and is essentialmode related not esx.

**Comment by XarocLP** [comment]
Only have a Steam account.
I also restarted my PC but did not do anything.

I use the Essentialmode 6.0.2.

For other players everything works quite normal.
Only with me not = (

I also come into the world.
But neither will my money, cars or my job be loaded.

I've already written in the FiveM forum, 
which said I should write that in Github es_extended = (

**Comment by vernietiger** [comment]
So i got mine working again.  I’ve deleted my DB and Made a totally new one and it worked so you can go and do that

**Comment by XarocLP** [comment]
that's stupid too ...
my community is big and many players are already playing on the server.

They would then lose their earned money = (

**Comment by SydeSB-EST** [comment]
Same problem... Please fix this bug. 👎

**Comment by benzon** [comment]
The error you are having is not persay a esx issue.

Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: server/main.lua:169: attempt to index a nil value (field ‘?’)

Line 169 is the part that set's the job vars you are able to call, the issue is that you either have  wrong rank set ex. 4 and it's not there, or other issues with your jobs.

**Comment by schwim0341** [comment]
I didn't mess with it enough to pin it down but noticed that although I set a player's job at rank 4, when he had this problem and I checked the db, it was set to rank 10.

Could have been fat finger syndrome but it would be pretty hard to type 10 accidentally when entering 4.

**Comment by marfixdev** [comment]
I have this problem too...Please fix

**Comment by Kamk886** [comment]
Having Basically The same Problems
My Character DB wont Load Into my Server, Thankfully its in Testing Status But Basically Ready to Launch.
The Problems im Having is : 
- does not load my character.
- my account balance and my job is not displayed.
- And  will not be listed on the scoreboard.
- neither will my money or my House Will Load.

Please Contact Me On here Or my Discord: ꧁༒drtyred༒꧂#6623 
Thanks.

**Comment by Cyephire** [comment]
Hello I'm having this issue a bit myself on my server I made a character but when I exit to add more stuff an go back in I keep having to redo my character even though I saved it is there a fix on this?

**Comment by VicLaBique** [comment]
For those you are having the same issue, for me it was the job unemployed2, make sure the job is create and have a job grade 0
I was stuck with the job unemployed2 for the secondary job and he was created but has no job_grades so make sure to add it

**Comment by VicLaBique** [comment]
> Hello I'm having this issue a bit myself on my server I made a character but when I exit to add more stuff an go back in I keep having to redo my character even though I saved it is there a fix on this?

try what i said above
