### ISSUE TITLE
Mono error

### ISSUE THREAD

**Issue by XxTopKillerzZ** [ESX-Org/es_extended#208]
Hi,

I have a virtual machine to make tests, i currently have a vrp server but i want to migrate to a esx server so i have a virtual machine on ubutno 1.18 to test the server and create ir in esx.
I have the default servr without anything changed, default plugins and default database.

I'm getting this error: https://i.imgur.com/5NQ7Fnd.png

What can it be? Also, i tryed with diferent server artifacts from fivem server

**Comment by ElPumpo** [comment]
No idea, not caused by esx
