### ISSUE TITLE
No update ui 

### ISSUE THREAD

**Issue by Blackwave78** [ESX-Org/es_extended#212]
hello the ui does not refresh when the boss deposits/ withdraws money in the company

**Comment by x1mart** [comment]
Same here

**Comment by Blackwave78** [comment]
found, re-written the code :D

**Comment by schwim0341** [comment]
Totally awesome of you not to share the fix for others.  This community thrives on that type of thing.

**Comment by Blackwave78** [comment]
just check if you have correct syntax in sql file and server/main.lua 


TriggerEvent('esx_phone:registerNumber', 'vigne', _U('vigneron_client'), true, true)
TriggerEvent('esx_society:registerSociety', 'vigne', 'Vigneron', 'society_vigne', 'society_vigne', 'society_vigne', {type = 'private'})






and sql INSERT INTO `addon_account` (`name`, `label`, `shared`) VALUES
	('society_vigne','Vigneron',1)
;

INSERT INTO `addon_inventory` (`name`, `label`, `shared`) VALUES
	('society_vigne','Vigneron', 1)
;
INSERT INTO `datastore` (`name`, `label`, `shared`) VALUES
	('society_vigne', 'Vigneron', 1)
;

INSERT INTO `jobs`(`name`, `label`, `whitelisted`) VALUES
	('vigne', 'Vigneron', 1)
;

INSERT INTO `job_grades` (job_name, grade, name, label, salary, skin_male, skin_female) VALUES
	('vigne',0,'recrue','Intérimaire', 500, '{}'),
	('vigne',1,'novice','Vigneron', 750, '{"}'),
	('vigne',2,'cdisenior','Chef de chai', 1200, '{}'),
	('vigne',3,'boss','Patron', 1600,'{}')
;

**Comment by komen205** [comment]
Blackwave78 solution is just to remove the code but then the system stops working. I'd advice fixing the code, the same is happening to @esx_society
