### ISSUE TITLE
problem with hud

### ISSUE THREAD

**Issue by FlowLzt** [ESX-Org/es_extended#213]
i don't have hud for the money. 
![capture](https://user-images.githubusercontent.com/47359811/52283756-5e2cb480-2963-11e9-80de-d5d5ce11c7e3.PNG)

**Comment by schwim0341** [comment]
As stated in the essential mode documentation, add the es_ui resource for cash display.

**Comment by FlowLzt** [comment]
> As stated in the essential mode documentation, add the es_ui resource for cash display.

How i do that please ?

**Comment by FlowLzt** [comment]
> As stated in the essential mode documentation, add the es_ui resource for cash display.

Don't work..
