### ISSUE TITLE
Keep getting ex_extended massive error

### ISSUE THREAD

**Issue by GewoonMarlon** [ESX-Org/es_extended#214]
Everytime i start my FXServer I get a error in red text saying

![screenshot_3](https://user-images.githubusercontent.com/47403510/52380145-f8c4ea80-2a6c-11e9-86fe-81b7cdcfcb4e.png)

How do i solve this ?

**Comment by schwim0341** [comment]
Change the host on your mysql connection string in server.cfg from 127.0.0.1 to localhost

**Comment by GewoonMarlon** [comment]
Nice man it worked thankyou very much :)
