### ISSUE TITLE
Paycheck going to bank?

### ISSUE THREAD

**Issue by donnayy** [ESX-Org/es_extended#215]
Hey there, thank's for this amazing script!
How I can change the money going to bank instead to wallet?

edit: I solved it but can you help me with this two ; the option to give something in menu F2 doesnt show the option.
Another question how I can remove the money like " 100.00.00 " to be " 100000?

**Comment by donnayy** [comment]
And I forgot the option to give something in menu F2 doesnt work.

**Comment by ElPumpo** [comment]
Not the place to ask question
