### ISSUE TITLE
After updating to the lastest master branch (as of the time of writing) cant change jobs

### ISSUE THREAD

**Issue by MrMallenby** [ESX-Org/es_extended#218]
I can not set jobs via the job centre but after testing the command works
es_extended: ignoring setJob for 6 due to job not found!  

in the console

**Comment by tonny766** [comment]
same problem

**Comment by MrMallenby** [comment]
After testing i also found hiring through the boss actions does not work and gives the same error

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/b8d0669b6416f79fc26cb7f3ea49b8e6302a4ee3 fixed this issue!
