### ISSUE TITLE
Release Database script needs to be fixed

### ISSUE THREAD

**Issue by luccazii** [ESX-Org/es_extended#220]
es_extended

This part of the code:
```
ALTER TABLE `users`
	ADD COLUMN `name` VARCHAR(50) NULL DEFAULT '' AFTER `money`,
	ADD COLUMN `skin` LONGTEXT NULL AFTER `name`,
	ADD COLUMN `job` varchar(50) NULL DEFAULT 'unemployed' AFTER `skin`,
	ADD COLUMN `job_grade` INT NULL DEFAULT 0 AFTER `job`,
	ADD COLUMN `loadout` LONGTEXT NULL AFTER `job_grade`,
	ADD COLUMN `position` VARCHAR(36) NULL AFTER `loadout`
;
```

has to be fixed, once is the first time I am building the database and I don't have  the table 'users', so I can't use the SQL Command "Alter Table"

**Comment by revolt32** [comment]
Bro you need to install script in right way maybe install first esx identity and look what happened

**Comment by revolt32** [comment]
Bro install first esplugin_mysql
