### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/es_extended#23]
`Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:342: attempt to compare number with nil
stack traceback:
	server/main.lua:342: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>`

How can i fix this error?

**Comment by ElPumpo** [comment]
More information? What do you expect us to say?? Give us steps to reproduce, anything!
