### ISSUE TITLE
Start Up Error

### ISSUE THREAD

**Issue by BrandsPickled** [ESX-Org/es_extended#231]
Creating script environments for sessionmanager
Started resource sessionmanager
Creating script environments for mapmanager
Started resource mapmanager
Creating script environments for chat
Started resource chat
Started resource spawnmanager
Started gametype Freeroam
Started resource fivem
Creating script environments for hardcap
Started resource hardcap
Creating script environments for rconlog
Started resource rconlog
Creating script environments for scoreboard
Error loading script server.lua in resource scoreboard: @scoreboard/server.lua:3                                                                                                                                                             7: attempt to index a nil value (global 'ESX')
stack traceback:
        @scoreboard/server.lua:37: in main chunk
Failed to load script server.lua.
Started resource scoreboard
Creating script environments for playernames
Started resource playernames
Started resource t-loadscreen-fixed
Creating script environments for async
Started resource async
Creating script environments for mysql-async
Started resource mysql-async
Creating script environments for essentialmode
Started resource essentialmode
Creating script environments for esplugin_mysql
Started resource esplugin_mysql
Creating script environments for es_admin2
Started resource es_admin2
Creating script environments for es_extended
Started resource es_extended
Started resource esx_menu_default
Started resource esx_menu_list
Started resource esx_menu_dialog
Creating script environments for cron
Started resource cron
Started resource NativeUI
Creating script environments for EasyAdmin
Started resource EasyAdmin
Creating script environments for anticheese-anticheat
Started resource anticheese-anticheat
Creating script environments for esx_addonaccount
Started resource esx_addonaccount
Started resource skinchanger
Creating script environments for esx_skin
Started resource esx_skin
Creating script environments for esx_jobs
Started resource esx_jobs
Creating script environments for esx_boilerplate
Started resource esx_boilerplate
Creating script environments for esx_rpchat
Started resource esx_rpchat
Creating script environments for esx_vehicleshop
Started resource esx_vehicleshop
Creating script environments for esx_ambulancejob
Started resource esx_ambulancejob
Creating script environments for esx_society
Started resource esx_society
Creating script environments for esx_billing
Started resource esx_billing
Creating script environments for esx_addoninventory
Started resource esx_addoninventory
Creating script environments for esx_status
Started resource esx_status
Creating script environments for esx_basicneeds
Started resource esx_basicneeds
Creating script environments for esx_atm
Started resource esx_atm
Creating script environments for esx_holdup
Started resource esx_holdup
Creating script environments for esx_policejob
Started resource esx_policejob
Creating script environments for esx_drugs
Started resource esx_drugs
Creating script environments for esx_license
Started resource esx_license
Creating script environments for esx_boat
Started resource esx_boat
Creating script environments for esx_clotheshop
Started resource esx_clotheshop
Started resource esx_animations
Creating script environments for esx_lscustom
Started resource esx_lscustom
Creating script environments for esx_mechanicjob
Started resource esx_mechanicjob
Creating script environments for instance
Started resource instance
Creating script environments for esx_datastore
Started resource esx_datastore
Creating script environments for esx_property
Started resource esx_property
Creating script environments for esx_identity
Started resource esx_identity
Creating script environments for esx_weaponshop
Started resource esx_weaponshop
Creating script environments for esx_taxijob
Started resource esx_taxijob
Creating script environments for esx_service
Started resource esx_service
Creating script environments for esx_bankerjob
Started resource esx_bankerjob
Creating script environments for esx_dmvschool
Started resource esx_dmvschool
Creating script environments for esx_shops
Started resource esx_shops
Creating script environments for esx_migrate
Started resource esx_migrate
Started resource esx_voice
Creating script environments for esx_garage
Started resource esx_garage
Creating script environments for esx_tattooshop
Started resource esx_tattooshop
Started resource esx_idonlyforadmin
Started resource map
Creating script environments for nearest-postal
Started resource nearest-postal
Creating script environments for 911
Started resource 911
Creating script environments for esx_impound
Failed to load script config.lua.
Started resource esx_impound
Creating script environments for ft_libs
Started resource ft_libs
Creating script environments for esx_jb_eden_garage2
Started resource esx_jb_eden_garage2
Started resource chat-theme-civlifechat
Creating script environments for esx_thief
Started resource esx_thief
Creating script environments for esx_outlawalert
Started resource esx_outlawalert
Creating script environments for fivem-instancedfix
Started resource fivem-instancedfix
Started resource esx_rpsuicide
Started resource esx_checkdeathcause
Creating script environments for esx_hospital
Started resource esx_hospital
Creating script environments for esx_truckerjob
Started resource esx_truckerjob
Started resource ftc_speedometer
Creating script environments for esx_panicbutton
Started resource esx_panicbutton
Creating script environments for esx_plasticsurgery
Started resource esx_plasticsurgery
Creating script environments for esx_spectate
Started resource esx_spectate
Started resource mapaddons
Creating script environments for esx_slotmachine
Started resource esx_slotmachine
Creating script environments for 99kr-burglary
Started resource 99kr-burglary
Creating script environments for esx-qalle-camerasystem
Started resource esx-qalle-camerasystem
Creating script environments for FXServer-Interact-Sound
Started resource FXServer-Interact-Sound
Creating script environments for esx_truck
Started resource esx_truck
Started resource bob74_ipl
Creating script environments for esx_TheLostMC
TheLostMC successfully loaded!
Started resource esx_TheLostMC
Creating script environments for esx_mafia
Started resource esx_mafia
Creating script environments for esx_gangjob
Started resource esx_gangjob
Creating script environments for esx_cartel
Started resource esx_cartel
Creating script environments for ESX-Binoculars
Started resource ESX-Binoculars
Creating script environments for esx_aiomenu
Started resource esx_aiomenu
Creating script environments for esx_locksystem
Started resource esx_locksystem
Creating script environments for esx_joblisting
Started resource esx_joblisting
Argument count mismatch (passed 1, wanted 2)
Authenticating server license key...
Server license key authentication succeeded. Welcome!
cfx> Started map fivem-map-hipster
Started resource fivem-map-hipster
Performing version check against: https://api.kanersps.pw/em/version?version=6.1                                                                                                                                                             .0&uuid=f41ee49c-06aa-4966-51bb-d7b6ab1fbbe0

nearest-postal by BlockBa5her started
hitch warning: frame time of 502 milliseconds
AntiCheese (anticheese-anticheat) is up to date!

[EssentialMode] Current version: 6.1.0
[EssentialMode] Updater version: 6.1.0

[EssentialMode] Everything is nice and updated!

nearest-postal up to date!
EasyAdmin (EasyAdmin) is up to date!
Error resuming coroutine: @esx_society/server/main.lua:26: attempt to index a ni                                                                                                                                                             l value (field '?')
stack traceback:
        @esx_society/server/main.lua:26: in local 'cb'
        @mysql-async/lib/MySQL.lua:204: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scriptin                                                                                                                                                             g/lua/scheduler.lua:218>

**Comment by BackrndSource** [comment]
Same isue:
#221 

Other similar issues:
#210 
#157 
#230 

But there's not solved, downgrade es_extended is the solution by the moment

**Comment by BrandsPickled** [comment]
> Same isue:
> #221
> 
> Other similar issues:
> #210
> #157
> #230
> 
> But there's not solved, downgrade es_extended is the solution by the moment

But theres Two errors...

Error loading script server.lua in resource scoreboard: @scoreboard/server.lua:3                                                                                                                                                             7: attempt to index a nil value (global 'ESX')
stack traceback:
        @scoreboard/server.lua:37: in main chunk
Failed to load script server.lua.


&

Error resuming coroutine: @esx_society/server/main.lua:26: attempt to index a ni                                                                                                                                                             l value (field '?')
stack traceback:
        @esx_society/server/main.lua:26: in local 'cb'
        @mysql-async/lib/MySQL.lua:204: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scriptin                                                                                                                                                             g/lua/scheduler.lua:218>

**Comment by BackrndSource** [comment]
sorry, those errors have nothing to do with es_extended.

esx_society y scoreboard:
@scoreboard/server.lua:3
@esx_society/server/main.lua:26:

Check your installation

**Comment by BrandsPickled** [comment]
Okay dokie
