### ISSUE TITLE
$ not showing 

### ISSUE THREAD

**Issue by BrandsPickled** [ESX-Org/es_extended#232]
I did a fresh install of ES + ESX but i dont have the $ only have the bank / dirty money / jobs. No money in hand

**Comment by schwim0341** [comment]
Install the es_ui resource from essentialmode.

**Comment by BrandsPickled** [comment]
not sure now cuz for some reason im getting this 
Successfully Loaded Identity For Brandon Rogers
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: @es_extended/server/main.lua:61: attempt to index a nil value (field '?')
stack traceback:
        @es_extended/server/main.lua:61: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:159: in function <citizen:/scripting/lua/scheduler.lua:144>
[ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM `user_inventory` WHERE `identifier` = @identifier {@identifier=steam:110000106672e5b}"
Error running call reference function for resource esx_tattooshop: citizen:/scripting/lua/scheduler.lua:403: @esx_tattooshop/server/main.lua:9: attempt to index a nil value (local 'xPlayer')
stack traceback:
        @esx_tattooshop/server/main.lua:9: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:626: in field '?'
        @es_extended/server/functions.lua:33: in field 'TriggerServerCallback'
        @es_extended/server/common.lua:63: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>

**Comment by BackrndSource** [comment]
Again? 

@es_extended/server/main.lua:61 - Means "es_extended/server/main.lua" in Line 61
@esx_tattooshop/server/main.lua:9 - Means Line 9

this is not an issue, you need support, read all from here: https://docs.fivem.net/server-manual/

**Comment by SoldiertsuNami** [comment]
i add the es_ui and doesn't work

**Comment by schwim0341** [comment]
Then you did it wrong.

**Comment by SoldiertsuNami** [comment]
can you give me your discord nametag to ask you somequestions

**Comment by SoldiertsuNami** [comment]
Work it
