### ISSUE TITLE
Error running call reference function for resource es_extended

### ISSUE THREAD

**Issue by lnno** [ESX-Org/es_extended#234]
I've received this error each time I've tried installing the server with fresh files. I've been looking for a fix, but everyone seems to say it's something wrong with the database and not being able to connect which is weird because it is connecting.

The only resources I have installed currently are;
essentialmode
mysql-async
async
es_extended
esx_menu_default/dialog/list
esplugin_mysql

Any help regarding this issue would be greatly appreciated.

```
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: @es_extended/server/main.lua:133: attempt to index a nil value (field '?')
stack traceback:
        @es_extended/server/main.lua:133: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)
```

**Comment by BackrndSource** [comment]
#231 Same error, read before repost the same

**Comment by BackrndSource** [comment]
and there are like 4 or 5 errors more like this, downgrade version es_extended

**Comment by lnno** [comment]
> and there are like 4 or 5 errors more like this, downgrade version es_extended

Downgrade to which version? I'm sure downgrading isn't the only fix to this issue.

**Comment by lnno** [comment]
I'm literally a fucking idiot. One line of code makes all the difference boys.

Anyone else with this issue, remember to add this after your mysql string.

`set es_enableCustomData 1`
