### ISSUE TITLE
Essential 5.0 compatibility update 

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/es_extended#24]
After update to "Essential 5.0 compatibility update", commands not workin for me. I cant spawn car etc :(

**Comment by Yorickvdg** [comment]
I dont now, but the **Essentialmode 5** has nothing to do with spawning cars! Essentialmode is doing communication base between MySQL i guess! And the groups ofcourse!

Im not sure, but i dont have any trouble! **Unless im respawning when died.**

Ciao! Regards **Skylake - Rivins**

**Comment by JaroSound** [comment]
`TriggerEvent('es:addGroupCommand', 'car', 'admin', function(source, args, user)`

**Comment by ElPumpo** [comment]
You've installed something wrong, ES5 works with es_extended just fine
