### ISSUE TITLE
ERROR server main.lua:163 error

### ISSUE THREAD

**Issue by Lyccossa** [ESX-Org/es_extended#241]
hello guys I have the following problem but I understand why, I'm doing hell.

Could you help me please?
![FOTO 3](https://user-images.githubusercontent.com/33160324/55637719-188e3b80-579c-11e9-9508-d9684e2d4646.png)
![foto 4](https://user-images.githubusercontent.com/33160324/55637720-188e3b80-579c-11e9-8813-002f361ba782.png)
![foto 5](https://user-images.githubusercontent.com/33160324/55637721-1926d200-579c-11e9-97a8-9a4f929225c6.png)

**Comment by ElPumpo** [comment]
Rerun esx sql
