### ISSUE TITLE
Using special characters in player name can break saving to db

### ISSUE THREAD

**Issue by secstu** [ESX-Org/es_extended#246]
Hi,
Below are the screenshots caused when a user is using a "special font" in his steam username.
![Screenshot_13](https://user-images.githubusercontent.com/24717027/55730697-b12cf180-5a10-11e9-8d13-f5d79061aaa4.png)
![Screenshot_43](https://user-images.githubusercontent.com/24717027/55730698-b1c58800-5a10-11e9-81d6-c8a016372337.png)
This is as you can see a "game breaking" bug which unable the user then to perform any action that would involve his database row to be used anywhere(as fk for example)

**Comment by indilo53** [comment]
Try to convert your tables to utf8 or utf8mb4 and see if it helps (do a backup before)

**Comment by secstu** [comment]
I thought initially it might have been the unicode. I will try to do that and see if it fixes thing(Although i have tried it before when trying to use the "emojis" within my inventory and it didnt fix much)

**Comment by secstu** [comment]
I just changed it to utfmb4_bin - still the same issue i have updated all my columns,tables and my database.

**Comment by ElPumpo** [comment]
Hmm you could maybe trim the name? I've had the same issue. Or maybe auto kick people with special characters in their name?

But to fix it it's the matter of choosing the correct charset, what did you end up using?

**Comment by ElPumpo** [comment]
Some special characters are good at completly breaking saving to db it seems. Question is do we even need to save the player name in db?

**Comment by XvenDeR** [comment]
> Some special characters are good at completly breaking saving to db it seems. Question is do we even need to save the player name in db?

it helps managing things a lot.

**Comment by benzon** [comment]
utf8mb4_

You need to change your mysql connection string.

set mysql_connection_string "mysql://USER:PASSWORD@127.0.0.1/DATABASENAME?charset=utf8mb4_general_ci&supportBigNumbers=true&multipleStatements=true"

This should fix all issues :)
