### ISSUE TITLE
Having this error help 

### ISSUE THREAD

**Issue by foregz** [ESX-Org/es_extended#247]
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: @es_extended/server/main.lua:62: attempt to index a nil value (field '?')
stack traceback:
        @es_extended/server/main.lua:62: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>

**Comment by frederic2ec** [comment]
Same here!

**Comment by ElPumpo** [comment]
Make sure esx is properly installed
