### ISSUE TITLE
Please i cant run my server all day, i need really help, @es_extended/server/main.lua:78: in upvalue 'ref'

### ISSUE THREAD

**Issue by Ranger194** [ESX-Org/es_extended#248]
I need really help please

Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: @es_extended/server/main.lua:78: attempt to index a nil value (field '?')
stack traceback:
    @es_extended/server/main.lua:78: in upvalue 'ref'
    citizen:/scripting/lua/scheduler.lua:389: in function citizen:/scripting/lua/scheduler.lua:388
    [C]: in function 'xpcall'
    citizen:/scripting/lua/scheduler.lua:388: in function citizen:/scripting/lua/scheduler.lua:387
stack traceback:
    [C]: in function 'error'
    citizen:/scripting/lua/scheduler.lua:403: in function citizen:/scripting/lua/scheduler.lua:372
error in mono_error_set_argument_null: 

[ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM user_inventory WHERE identifier = @identifier {@identifier=steam:110000101f2ae5f}"

**Comment by ElPumpo** [comment]
Install esx properly
