### ISSUE TITLE
Issue - Essentialmode 5 - Respawn Deathscreen

### ISSUE THREAD

**Issue by Yorickvdg** [ESX-Org/es_extended#25]
Hey!

First of all thanks! I really like your scripts and i really have respect for the way you make them! 

The other issue's placed about spawning cars.... Not for me..

**My issue**

Im using the ESX a while as base! As long as i stay running on _essentialmode-v4_ there are no issue's! If i upgrade to 5 then the /freeze commands are not working but i think that is the thing that you work on now!

Everything work like charm as from the moment type /die or die *.*... If i respawn the screen stays black! I restart the gamemode and then i have the effect on the screen! But still players have an black screen with loading circle down corner!

**Also! I'm learning coding for a while now and host many game servers for fun!** If you need help with anything or what ever i would be glad to learn! Your type of coding is clean and make's sence not one big of mess!

Friendly Regards!
SkyLake - Rivins

**Comment by Yorickvdg** [comment]
**I have fixxed my self!**

**Comment by signaturez** [comment]
How to Fix Black screen loading respawn

**Comment by AxeriusNetwork** [comment]
How to Fix Black screen loading respawn - Having same issue.
