### ISSUE TITLE
Failed to load script config.weapons.lua

### ISSUE THREAD

**Issue by swisherrr** [ESX-Org/es_extended#253]
Hi! I ran into this error when trying to start my server and I just dont know how to go about fixing it it says ;
"Error loading script config.weapons.lua in resource es_extended : config.weapons.lua:43: attempt to call a nil value <global 'GetHashKey' >
stack traceback:
         config.weapons.lua:43:  in main chunk
Failed to load script config.weapons.lua"

I will attach a pastebin link to exactly what my cmd prompt said but above was the topic im addressing : https://pastebin.com/WSuAgpCb

Thank you to anyone who can provide me with help as I know it's probably something simple but with there being a new update 3 hours ago I figure it's worth reporting

**Comment by ElPumpo** [comment]
Install esx properly

**Comment by Alejandroepilan** [comment]
I have the same error, i installed all correctly and nothing works. :(
