### ISSUE TITLE
Saving position and admin commands

### ISSUE THREAD

**Issue by Acelinh** [ESX-Org/es_extended#254]
I am having issues with players positions not being saved, everytime we rejoin we are spawned under the map in the city in the esxact same place everytime. Also the /bring and /goto commands spawn the person under the map too. Not seeing any errors in the console and the SQL is in the database.

Also how can I set new players positions to spawn at the airport? I’m using a Windows 2012 VPS.

 Anyone able to help?

Thank you in advance.

**Comment by ElPumpo** [comment]
That's not esx related

**Comment by kitoide** [comment]
I'm having this problem too, what could it be?
