### ISSUE TITLE
Locales Error

### ISSUE THREAD

**Issue by Smokey132** [ESX-Org/es_extended#26]
Hello, I receive these errors on most of the ESX_mods.

Error loading script locales/en.lua in resource instance-master: locales/en.lua:8: attempt to index a nil value (global 'Locales') 

It does this for almost every esx_(insertmodnamehere) that I have.........  Am I installing this stuff correctly?

Thank you,

**Comment by ElPumpo** [comment]
Obviously ES Extended has not been installed correctly.
