### ISSUE TITLE
"Position"  {"z":0.0,"y":0.0,"x":0.0}

### ISSUE THREAD

**Issue by Agony099** [ESX-Org/es_extended#268]
When a player logs out their location in the database is just all 0's, any ideas?

**Comment by BackrndSource** [comment]
Check the type of the column `position`. Needs to be varchar(255). 
To me before I did not keep the position well because the maximum size was varchar(40). Mayba something like that...

**Comment by ElPumpo** [comment]
No this is not why Source. We need to check if the player has properly loaded before querying coords

**Comment by AntonyMax** [comment]
Solution is here also !
replace "varchar(40)" to "longtext"
in Database at "users" in column `position`

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/f89e05175626f47275b4301e6561295414210711
