### ISSUE TITLE
Failed to load the config.weapon script

### ISSUE THREAD

**Issue by cantera123** [ESX-Org/es_extended#272]
I have this error:

Error loading script config.weapons.lua in resource es_extended: config.weapons.lua:43: attempt to call a nil value (global ‘GetHashKey’)
stack traceback:
config.weapons.lua:43: in main chunk
Failed to load script config.weapons.lua.

-When I enter the server the es_extended fails me

How do I have to reinstall the es_extended or esx_weaponshop

**Comment by DarkAngel99** [comment]
I have the same problem :(

**Comment by ElPumpo** [comment]
You must have done something very wrong
