### ISSUE TITLE
Attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by lRoberth** [ESX-Org/es_extended#277]
I receive this error when I try to join the server, ending with an infinite loading screen.
Reading the line 134 from main.lua, I can see it's because result[1] is null, from the result that the database received. If I go to the database, I can see there's no users  in there, so I can suppose that new users aren't being inserted in the database, and then the server tries to read them like if they were not new, returning null values. Is there a fix on this?, I don't see any INSERT INTO users in main.lua

> Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:405: @es_extended/server/main.lua:134: attempt to index a nil value (field '?')
> stack traceback:
>         @es_extended/server/main.lua:134: in upvalue 'ref'
>         citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
>         [C]: in function 'xpcall'
>         citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
> stack traceback:
>         [C]: in function 'error'
>         citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>
> Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
> Error: BUFFER_SHORTAGE
>     at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
>     at h (citizen:/scripting/v8/msgpack.js:29:15761)
>     at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
>     at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
>     at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
>     at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
>     at unpack (citizen:/scripting/v8/main.js:20:33)
>     at citizen:/scripting/v8/main.js:51:20
>     at setImmediate (mysql-async.js:5138:9)
>     at Object.callback (citizen:/scripting/v8/timer.js:96:21)

**Comment by RikoDEV** [comment]
I have the same problem after the last essentialmode update.

**Comment by GeoZzNL** [comment]
We have the same problem! It' breaks some resources :(

**Comment by RikoDEV** [comment]
Currently, most ESX scripts do not work properly due to this error.

**Comment by NeonOdyssey** [comment]
so any way to fix this as I'm having a similar issue. 
As ElPumpo has closed this issue and every other issue that is based around `BUFFER_SHORTAGE` I'm assuming they have found a solution to this and not told anyone?

**Comment by NeonOdyssey** [comment]
Hey guys,
I have done some digging and found out why @ElPumpo  has been closing issues left right and center without saying a word. Basically, @ElPumpo is claiming that the errors are all because of job errors and user errors (even when its a fresh install)

I have found out that the problem may be due to your not connecting to the MySQL before you run the resources.

**Comment by schwim0341** [comment]
Which is still completely user caused error as MySQL install is ES related and has nothing to do with ESX. If pump took the time to help every person that doesn't follow install instructions or google, he'd never have time to develop ESX.

**Comment by NeonOdyssey** [comment]
The fact that pump just closes an issue without stating why is poor pr. Pump could at least link the faq. That's how I found out.

**Comment by ElPumpo** [comment]
You idiot you caused it because your inability to read english

**Comment by DooubleTap** [comment]
i mean, i read english and i am still having this damm issue that i cant find on google, it sounda like he takes people for idiots..
