### ISSUE TITLE
Attempt to index nil value (field : 'Streaming')

### ISSUE THREAD

**Issue by jokid64** [ESX-Org/es_extended#282]
Hi,

With some of my script i've got this error since I updated es_extended.

- Those scripts (basicneeds, ambulancejob) are started AFTER es_extended in server.cfg
- client/modules/streaming.lua is in __resource.lua
- `ESX.Streaming                 = {}` is ok in functions.lua

Dont know where to look now :(

**Comment by ElPumpo** [comment]
You have done something very wrong
