### ISSUE TITLE
ESX.ShowAdvancedNotification is limited

### ISSUE THREAD

**Issue by ZeProf2Code** [ESX-Org/es_extended#286]
ESX.ShowAdvancedNotification is limited, we can't show how much characters we want.

**Comment by XvenDeR** [comment]
found fix?

**Comment by Rubyliss** [comment]
Same issue here !

**Comment by criminalist** [comment]
+1 https://github.com/ESX-Org/es_extended/issues/326

**Comment by DoubleT74** [comment]
```lua
ESX.ShowAdvancedNotification = function(title, subject, msg, icon, iconType)
	AddTextEntry('showAdNotification', msg)
	SetNotificationTextEntry('showAdNotification')
	SetNotificationMessage(icon, icon, false, iconType, title, subject)
	DrawNotification(false, false)
end
```

**Comment by criminalist** [comment]
> ```lua
> ESX.ShowAdvancedNotification = function(title, subject, msg, icon, iconType)
> 	AddTextEntry('showAdNotification', msg)
> 	SetNotificationTextEntry('showAdNotification')
> 	SetNotificationMessage(icon, icon, false, iconType, title, subject)
> 	DrawNotification(false, false)
> end
> ```

What is this for?

**Comment by ElPumpo** [comment]
The problem lies with `AddTextComponentSubstringPlayerName()` and similar natives. They have char limits of 99. What you can do is split up the message into chunks that fit the native above, or it seems like text entries dont have this tiny limit size
