### ISSUE TITLE
ESX.ShowAdvancedNotification support utf8?

### ISSUE THREAD

**Issue by hichay** [ESX-Org/es_extended#295]
ESX.ShowAdvancedNotification cannot show some character. is there any fix ?

**Comment by XvenDeR** [comment]
im interested too

**Comment by gazisaad** [comment]
im no expert i tried  and failed  :(  

if you tell me where is the file for shownotificaton exactly maybe i will be able fix it

**Comment by ElPumpo** [comment]
If it doesnt work then theres nothing we can do about it. Its a gta native
