### ISSUE TITLE
I get this error when I move in-game

### ISSUE THREAD

**Issue by acendrion** [ESX-Org/es_extended#296]
Creating script environments for es_extended
Error loading script server/main.lua in resource es_extended: @es_extended/server/main.lua:368: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:368: in main chunk
Failed to load script server/main.lua.
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)
        @es_extended/server/commands.lua:1: in main chunk
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)
        @es_extended/server/commands.lua:19: in main chunk
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)
        @es_extended/server/commands.lua:40: in main chunk
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)
        @es_extended/server/commands.lua:46: in main chunk
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)
        @es_extended/server/commands.lua:52: in main chunk
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)
        @es_extended/server/commands.lua:58: in main chunk
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)
        @es_extended/server/commands.lua:64: in main chunk
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)
        @es_extended/server/commands.lua:70: in main chunk
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/server/main.lua:308: attempt to index a nil value (global 'commands')
stack traceback:
        @es_extended/server/main.lua:308: in function 'addGroupCommand'
        @es_extended/server/main.lua:353: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:491: in function 'TriggerEventInternal'
        (...tail calls...)

**Comment by Drdrin** [comment]
With this error you can no longer drop items it does not appear in inventory

SCRIPT ERROR: @es_extended/server/main.lua:368
