### ISSUE TITLE
-$Amount  hidden behind bank account

### ISSUE THREAD

**Issue by Bod3g** [ESX-Org/es_extended#3]
Whenever money is taken from the player the  "- $500" (for example)  is hidden behind your bank account.
![knipsel](https://user-images.githubusercontent.com/26828122/29259773-5f50652a-80c5-11e7-8fe2-f0d61f338923.PNG)

**Comment by ElPumpo** [comment]
You have a script that shows that ui. It is simply not related to this script.

**Comment by HumanTree92** [comment]
I am getting this same problem do you happen to know what script will allow me to change the location so i can for say move it to the left?

**Comment by HumanTree92** [comment]
Found the fix for this. Go to your essentialmode/ui.html & find .tiny 
this is what i used to fix this
.tiny {
			font-size: 29px;
			position: absolute; 
			top: 200; right: 20;
		}
