### ISSUE TITLE
Essentialmode removed PVP, can we please add it to es_extended

### ISSUE THREAD

**Issue by pfoote** [ESX-Org/es_extended#302]
Essentialmode removed pvpEnabled recently, could we please add that functionality into es_extended 

https://github.com/kanersps/essentialmode/commit/001b0d5063b68335351b824a38375596fabcffd5

**Comment by DevMarshall95** [comment]
Agreed, i've had to use https://drive.google.com/file/d/0B7pPkNZZXKksVU9Xc1I5Q2F5eTA/view
while this gets sorted.

**Comment by essjaybee** [comment]
It's not that big of a change, while I agree that perhaps it should be in ESX, even if I don't use ESX myself.
However my codebase has taken alot of inspiration from ESX (although not enough yet to make a PR on this).

Here's what I use in my client resource:
`Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)
		if Config.EnablePVP then
			for _, player in ipairs(GetActivePlayers()) do
				local ped = GetPlayerPed(player)
				if NetworkIsPlayerActive(player) then
					SetCanAttackFriendly(GetPlayerPed(ped), true, true)
					NetworkSetFriendlyFireOption(true)
				end
			end
		end
	end
end)`

OneSync friendly and obviously Config.EnablePVP is static and could (and should) be made to something settable by events.

**Comment by ElPumpo** [comment]
```lua
AddEventHandler('playerSpawned', function(spawn)
	SetCanAttackFriendly(PlayerPedId(), true, false)
	NetworkSetFriendlyFireOption(true)
end)
```
use this code instead and not that shitty loop every fucking frame

**Comment by omgpointless** [comment]
That shitty loop is how essentialmode used to do it.

https://github.com/kanersps/essentialmode/commit/001b0d5063b68335351b824a38375596fabcffd5

**Comment by ElPumpo** [comment]
It doesnt matter

**Comment by ElPumpo** [comment]
It doesnt matter

**Comment by omgpointless** [comment]
What I meant was, this is how essentialmode did it. Being a library that been around for some time I thought there was a reason to put it in a loop that I was unaware of.

Thanks for updating with your snippet though. Much rather use an event heh.
