### ISSUE TITLE
No players nearby

### ISSUE THREAD

**Issue by OfficialBart** [ESX-Org/es_extended#309]
When I want to search someone or check the id card, give a invoice etc etc. 
We get the message: There are no players nearby!

What did we do:
- Server updated
- Server cache cleared
- Es-extended updated
- essentialmode updated

etc etc.

With onesync 64 slots

Can you help us?

**Comment by ArmoredSoldiers** [comment]
With OneSync? or without OneSync?

**Comment by OfficialBart** [comment]
with Onesync

**Comment by ArmoredSoldiers** [comment]
Change your scripts for player loop 32 to 256.  

lets check: [OneSync Adaption Tutorial](https://forum.fivem.net/t/how-to-adapt-your-script-to-onesync-and-fix-your-issues/580551)

**Comment by OfficialBart** [comment]
jup thx!!
