### ISSUE TITLE
Error /givemoney, /setjob, etc

### ISSUE THREAD

**Issue by tugamars** [ESX-Org/es_extended#31]
I got this error on every command with more than one parameter:

`Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:351: server/commands.lua:76: attempt to index a nil value (local 'xPlayer')
stack traceback:
        server/commands.lua:76: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
Error running call reference function for resource essentialmode: citizen:/scripting/lua/scheduler.lua:351: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in upvalue 'callback'
        server/main.lua:213: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>`

**Comment by HunterDragos** [comment]
I have the same error ... have you found anything helpful ?

**Comment by CoreyMcCown13** [comment]
Wipe your database. Disable all mods. Install EssentialMode and es_extended. Boot the game. Make sure you have EssentialMode 5.0. After this first boot, shutdown the server and re-activate all mods.

**Comment by ElPumpo** [comment]
You have obviously not installed the script correctly.

**Comment by ElPumpo** [comment]
Closing because of activity

**Comment by ALENTL** [comment]
> Wipe your database. Disable all mods. Install EssentialMode and es_extended. Boot the game. Make sure you have EssentialMode 5.0. After this first boot, shutdown the server and re-activate all mods.

What about in QBCore. Have you got anything for that???
