### ISSUE TITLE
xPlayer functions doesn't work

### ISSUE THREAD

**Issue by Javiito32** [ESX-Org/es_extended#311]
![image](https://user-images.githubusercontent.com/42683930/61189503-a7a9ca00-a68e-11e9-8d8f-0a87a5fde49f.png)
I am having problems with the xPlayer functions, all the others works fine
![image](https://user-images.githubusercontent.com/42683930/61189531-fc4d4500-a68e-11e9-9bf0-af4992d4f7f7.png)
Also with this other code

**Comment by hemato** [comment]
me to how you fixed it . i will fix it with remove the playerid. but i dont know if its healthy or not
