### ISSUE TITLE
ESX.SavePlayers make client crash

### ISSUE THREAD

**Issue by Sn0wBiT** [ESX-Org/es_extended#313]
My server with ~25-30 players get crash alot. I found that problem is when server call ESX.SavePlayers(). When that function run about 10 players it start to crash! Crash code : "ohio-delaware-pizza" 
My user_inventory is around: 32,762 rows.
This is my user_inventory data structure
![image](https://user-images.githubusercontent.com/9019527/61229074-b0af9f80-a751-11e9-9980-70bb3ac19692.png)

[CitizenFX.log](https://github.com/ESX-Org/es_extended/files/3393061/CitizenFX.log)

**Comment by Sn0wBiT** [comment]
Is there any fix for this problem ?

**Comment by ElPumpo** [comment]
Closed issue because only you have this problem, you will have to find out.
