### ISSUE TITLE
attempt to concatenate a nil value (local 'str')

### ISSUE THREAD

**Issue by ModatherM** [ESX-Org/es_extended#316]
Hello there,

> SCRIPT ERROR: @es_extended/locale.lua:10: attempt to concatenate a nil value (local 'str')

i got this error message right after making the sever OnceSync enabled on the latest es_extended (which removed the MaxPlayers from config) and latest sever version (posted on 26/7), idk what to do, tried to check what code but found this

> 			return 'Translation [' .. Config.Locale .. '][' .. str .. '] does not exist'

Didn't know what is the wrong with it, so i said i post it her maybe someone will help me, 
Also this console error make resource time warning in-game which make fps drops with high amount (sometimes to goes to -30fps), i would be thankful if you helped me :)
Thanks in advance.

**Comment by eoltw** [comment]
me too 
SCRIPT ERROR: @es_extended/locale.lua:8: bad argument #2 to 'format' (no value)
