### ISSUE TITLE
value (global 'ESX') ERROR

### ISSUE THREAD

**Issue by Sydres** [ESX-Org/es_extended#317]
İm getting this error on all ESX Resources
Error resuming coroutine: @esx_status/server/main.lua:7: attempt to index a nil
value (global 'ESX')
stack traceback:
        @esx_status/server/main.lua:7: in function <@esx_status/server/main.lua:

**Comment by WajihHalawani** [comment]
if that's a global issue with all esx mods than do a fresh re-install and make sure to install everything correctly.

-OR-
Everything was working before?

**Comment by WajihHalawani** [comment]
> 
> 
> İm getting this error on all ESX Resources
> Error resuming coroutine: @esx_status/server/main.lua:7: attempt to index a nil
> value (global 'ESX')
> stack traceback:
> @esx_status/server/main.lua:7: in function <@esx_status/server/main.lua:

if that's a global issue with all esx mods than do a fresh re-install and make sure to install everything correctly.

-OR-
Everything was working before?
