### ISSUE TITLE
Job Grades Not Showing

### ISSUE THREAD

**Issue by Janicki92** [ESX-Org/es_extended#320]
Once again, Job Grades are disappearing from the HUD on screen.  Don’t close the issue without commenting or acknowledging this is happening as of the last three days.  

FiveM discord indicated it had something to do with a change in the server artifact, however rolling back didn’t seem to help.

Again, looking for a solution here, not to have the issue closed with zero comments...

**Comment by ElPumpo** [comment]
Dont need to make a dupe, you're doing something wrong
