### ISSUE TITLE
How to cancel the name and ID of the player's head

### ISSUE THREAD

**Issue by Ivannnmmn** [ESX-Org/es_extended#325]
![image](https://user-images.githubusercontent.com/53795304/62490777-bb170380-b7fc-11e9-87ec-c59ac1ab20dd.png)

**Comment by schwim0341** [comment]
remove **start playernames** from server.cfg.  This has nothing to do with es_extended.

**Comment by Ivannnmmn** [comment]
@schwim0341 My fault Thank you bro.
