### ISSUE TITLE
SetNotificationTextEntry (‘STRING’) Max 99 Byte

### ISSUE THREAD

**Issue by criminalist** [ESX-Org/es_extended#326]
Hi, There was a problem with the restriction of characters in the string, the server uses the Cyrillic alphabet, this means 2 bytes per character, as a result, system notifications are truncated.
SetNotificationTextEntry (‘STRING’) Max 99 Byte
Screenshots https://i.imgur.com/PKAFQQW.jpg

**Comment by Rubyliss** [comment]
Mmh, what other type could bu used ?

**Comment by criminalist** [comment]
> Mmh, what other type could bu used ?

I don’t know, I could use another, but I don’t know others, only a string.

**Comment by ElPumpo** [comment]
Dupe
