### ISSUE TITLE
ES documentation link is broken

### ISSUE THREAD

**Issue by Roms1383** [ESX-Org/es_extended#329]
Hello everybody !
The link to [ES documentation](https://docs.essentialmode.com/) on main [README](https://github.com/ESX-Org/es_extended/blob/master/README.md) is broken, and it can't be found elsewhere (just did a quick Google search though), except maybe [this one](https://esx-org.github.io/es_extended/).

Greets !

**Comment by ElPumpo** [comment]
Tell kanersps

**Comment by Roms1383** [comment]
@kanersps ?

**Comment by kanersps** [comment]
Hi there,

Please use: https://wiki.kanersps.pw

There is a FiveM section with EssentialMode's documentation :)

Friendly regards,

Kane

**Comment by ElPumpo** [comment]
See https://github.com/ESX-Org/es_extended/pull/356
