### ISSUE TITLE
@esx_identity/server/main.lua:501: attempt to index a nil value (global 'ESX')

### ISSUE THREAD

**Issue by ThoLaNL** [ESX-Org/es_extended#337]
When starting the server, i got an error: 
`Error loading script server/main.lua in resource esx_identity: @esx_identity/server/main.lua:501: attempt to index a nil value (global 'ESX')
stack traceback:  @esx_identity/server/main.lua:501: in main chunk`

Line 501 is part of this code:

ESX.RegisterServerCallback('esx:getPlayerData', function(source, cb)
	local xPlayer = ESX.GetPlayerFromId(source)

	cb({
		identifier   = xPlayer.identifier,
		accounts     = xPlayer.getAccounts(),
		inventory    = xPlayer.getInventory(),
		job          = xPlayer.getJob(),
		loadout      = xPlayer.getLoadout(),
		lastPosition = xPlayer.getLastPosition(),
		money        = xPlayer.getMoney()
	})
end)

where }) is line 501

I have installed es_extended v1.1.0
All other esx mods are working fine.

**Comment by ThoLaNL** [comment]
Fixed by installing server and database again.

**Comment by iTzOneLightning** [comment]
What do you meant with installing them again? Ressetting them and install them again?

**Comment by ThoLaNL** [comment]
Oh it is long time ago but i think i just deleted the whole fivem server and build it up from a scratch and tested everything after installing a mod. What i did was everytime i installed a mod, i created a backup and when a mod breaks down the server, i returned back to the latest backup i've created
