### ISSUE TITLE
Lag when dropping items

### ISSUE THREAD

**Issue by Tinky124** [ESX-Org/es_extended#338]
When somebody drops the item on server everybody on server es_extended will go up like 0.40ms and even higher i am using last version of es_extended and i didnt touch anything about es extended script.. so problem is that items will load for everyone on server and it will cause ms lagg script and fps drop..

**Comment by XvenDeR** [comment]
how to disable drops completely?

**Comment by Dragese** [comment]
@ElPumpo
So, maybe check distance between players and droped items and if no players nearby 20 meters then delete that's items from ground?
