### ISSUE TITLE
Missing Weapons Names

### ISSUE THREAD

**Issue by GoldenLys** [ESX-Org/es_extended#339]
Some weapons are missing like MK2 weapons or PipeWrench

**Comment by GoldenLys** [comment]
Here's the list of the missing weapons ^.^

WEAPON_PISTOL_MK2
WEAPON_COMBATMG_MK2
WEAPON_ASSAULTRIFLE_MK2
WEAPON_CARBINERIFLE_MK2
WEAPON_SWEEPERSHOTGUN
WEAPON_SNSPISTOL_MK2
WEAPON_REVOLVER_MK2
WEAPON_SPECIALCARBINE_MK2
WEAPON_BULLPUPRIFLE_MK2
WEAPON_PUMPSHOTGUN_MK2
WEAPON_MARKSMANRIFLE_MK2
WEAPON_HEAVYSNIPER_MK2
WEAPON_PIPEWRENCH
WEAPON_SMG_MK2

**Comment by XvenDeR** [comment]
Have been adding mk2 weapons, its a lot of fun since ot has lots of attachments. 👌

**Comment by HumanTree92** [comment]
This topic can be closed. MK2 was removed. Its what they wanted.
https://github.com/ESX-Org/es_extended/commit/48a1605bc23f96a7b706183f7e2e66136df45fc5
https://github.com/ESX-Org/es_extended/commit/31f3bddf4cb9ef0130c51dc55f6aee5e9d581b53
