### ISSUE TITLE
No Issue, just want to share my script since I dont work on servers much anymore.

### ISSUE THREAD

**Issue by crixzgamez** [ESX-Org/es_extended#347]
Feel free to use my script as wanted,
Thanks to MacieG for the awesome support trough Discord when this script was inactively used a few months back!

- please read the readme before changing anything, 
the config is somehow described on how to change things.
This script comes with planting, processing, and works well!
download link: 
https://www.mediafire.com/file/av0y0883r6tyw7s/esx_planting.rar/file

**Comment by ElPumpo** [comment]
You're completly lost. Go to our esx discord and share code there.

**Comment by crixzgamez** [comment]
It works, what do you mean..? hhhh
