### ISSUE TITLE
es_extended client/main.lua 72: attempt to index a nil value (global `Pickups`)

### ISSUE THREAD

**Issue by Tinky124** [ESX-Org/es_extended#350]
![Untitled](https://user-images.githubusercontent.com/48660658/65987674-964ead80-e486-11e9-8bf9-fd3ae75e8c72.png)

**Comment by sertacdncl** [comment]
I am getting same issue on my server

**Comment by chandanroksjsr** [comment]
u got any fix to this same issue???

**Comment by Zerefdev** [comment]
For now, just rename `Pickups `to `pickups`

**Comment by sertacdncl** [comment]
![image](https://user-images.githubusercontent.com/20639384/66484246-49cf2780-eaaf-11e9-81b3-7cd2864d2430.png)
Like that ? @Zerefdev

**Comment by Zerefdev** [comment]
exactly

**Comment by ElPumpo** [comment]
Fixed, thanks for the heads up!

**Comment by youtravel-del** [comment]
![Capture](https://user-images.githubusercontent.com/57874477/106818934-5a7ab800-6679-11eb-82c2-e847bf8e2b1c.PNG)
