### ISSUE TITLE
In Ground Items Going Connecting Players Inventory

### ISSUE THREAD

**Issue by sertacdncl** [ESX-Org/es_extended#353]
I am using latest es extended but when someone throw ground item, its going to player's inventory who is connecting.

Please help.

![image](https://user-images.githubusercontent.com/20639384/66232491-9e5e5580-e6f1-11e9-8edb-a855b67afa07.png)

**Comment by Zerefdev** [comment]
@ElPumpo 
Pickups are still broken
also line 50 throws an error after dropping items and disconnect  & reconnect.
Attempt to index a nil value (global'Pickups') 

typo? `Pickups[pickupId]` -> `pickups[pickupId]` (I didn't want to PR 1 line)
Still.. mid joining players can't interact with dropped items

**Comment by ElPumpo** [comment]
@zerefdev ill take a look

**Comment by ElPumpo** [comment]
Should be fixed in #350 , please confirm fix!

**Comment by sertacdncl** [comment]
#350 Fixed

**Comment by ElPumpo** [comment]
Yey

**Comment by Tinky140** [comment]
@ElPumpo  Still problem and see error updated to lastest version and also when players dropping items on server script will go to 10.5ms -45fps and on server items will dupe..

**Comment by sertacdncl** [comment]
Yes its not fixed :(

**Comment by Tinky124** [comment]
Still the same problem using lastest update items will dupe on ground and script will lagg same error again like up picture

**Comment by Tinky124** [comment]
@sertacdncl  I fixed and its now working well on my server no error or items duplication on server 
#359

**Comment by Tinky124** [comment]
@sertacdncl and just update to es_extended to lastest version and change missingPickups to only pickups and problem will be fixed..

**Comment by sertacdncl** [comment]
#359 Fixed
