### ISSUE TITLE
Replace GetPlayerName() with xPlayer name in giving items menu

### ISSUE THREAD

**Issue by ZockerBoysHD** [ESX-Org/es_extended#354]
I want esx to use the character name isntead of the steamname when interacting with other players (giving items to them, the messages).
I tried multiple methods but none of them worked. 
I tried a server callback (the one of esx_policejob) which gives me the first & lastname of a character but after implementing this it stopped users from conencting (the FiveM client always crashed while connecting)

To implement, i edited client/functions.lua 
[Like This](https://screens.egopvp.com/images/2019/10/06/notepad_Mcg9lAFIsp.png)

**Comment by sertacdncl** [comment]
That will be good. I want to use it with esx_inventoryhud

**Comment by ZockerBoysHD** [comment]
How am I Supposed to even Cast the nearest Players to xPlayer if it doesn't even send the PlayerServerID sucessfully to the server?!?. If i print the data being received (what should be a number) it always is something like "table 0x2198470", If i add another argument to the callback (on the server side) and print that, thats the playerid/name. After trying using that it the callback doesn't work (cb(data) is without any function)

**Comment by ElPumpo** [comment]
Zocker are you high? Since we can't change the outcome of the `GetPlayerName()` native we'll have to use server callbacks to request player names
