### ISSUE TITLE
people dont get pay chacks

### ISSUE THREAD

**Issue by ilLuminatriXkill** [ESX-Org/es_extended#360]
SCRIPT ERROR: @es_extended/server/paycheck.lua:19: attempt to index a nil value (local 'account')
> ref (@es_extended/server/paycheck.lua:19)
> handler (@esx_addonaccount/server/main.lua:63)
> ref (@es_extended/server/paycheck.lua:18)
> handler (@esx_society/server/main.lua:60)
> fn (@es_extended/server/paycheck.lua:16)

everything is up to date

**Comment by ElPumpo** [comment]
Yes they do. Fix your accounts or disable society payout

**Comment by REDRUM216** [comment]
Can you elaborate on Fix your accounts please? I would like to figure out how to fix it over disabling soceity payout.

**Comment by Mycroft-Studios** [comment]
> Can you elaborate on Fix your accounts please? I would like to figure out how to fix it over disabling soceity payout.

This is very old, make sure you are using esx v1-final and that everything is up-to-date
