### ISSUE TITLE
Any item/money/etc duping

### ISSUE THREAD

**Issue by XvenDeR** [ESX-Org/es_extended#362]
Bug works in a very easy way:

1. Player drops money
2. Picks it up
3. Quickly reconnects
= You have the money and the drop is still on the ground.

How do we fix it?

Is it possible to disable dropping? Or maybe only for specific items, like, money/weed/etc... Which is critical to server economy?

**Comment by Tinky124** [comment]
Yea i have same problem

**Comment by XvenDeR** [comment]
> Yea i have same problem

i even tried to use fresh essentialmode and es_extended. problem still occurs... wth...
if you ever find a fix, please tell me know.

**Comment by Tinky124** [comment]
@XvenDeR Try to do this and test and say if it this helped.. 
![Untitled3](https://user-images.githubusercontent.com/48660658/66720044-bfacf900-edf7-11e9-8293-323c7fd4934d.png)

**Comment by XvenDeR** [comment]
![image](https://user-images.githubusercontent.com/29688478/66720378-77e09e80-ee04-11e9-8e90-446acf1ecc1f.png)
It removed pickups, but prop still spawns. At least they can't pick it anymore. :D Thanks.

**Comment by XvenDeR** [comment]
Removed whole event, no more duping and no more props... At least until real programmers fix this. :)

**Comment by Trsak** [comment]
Fixed in #377
