### ISSUE TITLE
Item weight console errors

### ISSUE THREAD

**Issue by XvenDeR** [ESX-Org/es_extended#363]
![image](https://user-images.githubusercontent.com/29688478/66721237-b6c62280-ee0b-11e9-8289-834288f84297.png)
When trying to pick up item, it doesn't add up in inventory and throws these errors.

**Comment by K3IDB** [comment]
same :(

**Comment by ElPumpo** [comment]
Update your items table on database

**Comment by kevintransp** [comment]
Explain please, checkt it several times and set all the item weight to 1 but stil get this error to.

**Comment by K3IDB** [comment]
> Update your items table on database

already update but it doesnt work

**Comment by XvenDeR** [comment]
I did update it to TINYINT and weight... Weird... I'll do fresh install to see if that's my fault.

**Comment by yagizher** [comment]
Same.Updated items table but not working
