### ISSUE TITLE
Players Spawns with No Skin

### ISSUE THREAD

**Issue by reeperk** [ESX-Org/es_extended#365]
All Peoples, they are in the Cop Job, are Spawned with No Skin and No Job :(

Please Help or Fix it...

**Comment by schwim0341** [comment]
Post the errors printed when a player with the police job logs in.

**Comment by reeperk** [comment]
I have found the Error. Sorry for this large Time ^^:

[91mSCRIPT ERROR: @esx_policejob/server/main.lua:360: bad argument #1 to 'for iterator' (table expected, got nil)[0m
[93m> TriggerServerCallback[0m ([36m@es_extended/server/functions.lua[0m:33)
[93m> handler[0m ([36m@es_extended/server/common.lua[0m:88)

**Comment by ElPumpo** [comment]
install esx_skin

**Comment by reeperk** [comment]
We have installed esx_skin and it dont work

**Comment by reeperk** [comment]
> install esx_skin

We have installed esx_skin and it dont work
