### ISSUE TITLE
Weight pr user.

### ISSUE THREAD

**Issue by danishrp** [ESX-Org/es_extended#369]
Could you add so weight is pr user insted of based on a static weight for every users?

That way we can add in training or some sort, just to add some more realisme.

**Comment by deviljin112** [comment]
If you look in config it states "Max Weight without backpack" therefore im sure there is a goal for altering or providing a platform where you can alter the max weight therefore it will be rather easy to later alter the code further with custom parameters. Simply sit tight and weight for Pumpo to finish his development :)

**Comment by ElPumpo** [comment]
implement yourself?!?!
