### ISSUE TITLE
Inventory issue after weight update.

### ISSUE THREAD

**Issue by deviljin112** [ESX-Org/es_extended#370]
Got issue after the new update, I've updated everything (incl. SQL)

[Image of error here](https://cdn.discordapp.com/attachments/486612402721390602/634439316713635840/unknown.png)

I believe that it pulls from SQL 1 or 0 and interprets it as boolean and not an integer which then causes an issue in functions which attempts to make a calculation ( weight * count ) but cant do it on a boolean ( as its true or false ). I've tried changing the weights etc. but its not fixing it :S

**Comment by drezh** [comment]
I thought i was the only one with this problem. I have the exact same. Really annyoing :/

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/f33c317d6f5618764eb60f7e22e15755d3075687
