### ISSUE TITLE
Scipt Error

### ISSUE THREAD

**Issue by AguiarMacho** [ESX-Org/es_extended#374]
SCRIPT ERROR: @es_extended/server/main.lua:184: bad argument #1 to 'for iterator' (table expected, got nil)

**Comment by Domitresku** [comment]
yes, i have that problem too, but on my pc, this comes up : 

[ERROR] connect EACCES 127.0.0.1:3306

[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM items": connect EACCES 127.0.0.1:3306
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM jobs": connect EACCES 127.0.0.1:3306

SCRIPT ERROR: @es_extended/server/common.lua:23: bad argument #1 to 'for iterator' (table expected, got nil)
> ref (@es_extended/server/common.lua:23)
> setImmediate (@mysql-async/mysql-async.js:14431)
SCRIPT ERROR: @es_extended/server/common.lua:35: attempt to get length of a nil value (local 'result')
> fn (@mysql-async/lib/MySQL.lua:197)
