### ISSUE TITLE
[ERROR] Connect EACCES 127.0.0.1:3306

### ISSUE THREAD

**Issue by Domitresku** [ESX-Org/es_extended#375]
Hello, I need help with es_extended, but with some thing called eacces, please, if you know, leave a comment down bellow. 

This comes up: 

[ERROR] connect EACCES 127.0.0.1:3306

[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM items": connect EACCES 127.0.0.1:3306
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM jobs": connect EACCES 127.0.0.1:3306

SCRIPT ERROR: @es_extended/server/common.lua:23: bad argument #1 to 'for iterator' (table expected, got nil)
> ref (@es_extended/server/common.lua:23)
> setImmediate (@mysql-async/mysql-async.js:14431)
SCRIPT ERROR: @es_extended/server/common.lua:35: attempt to get length of a nil value (local 'result')
> fn (@mysql-async/lib/MySQL.lua:197)

Here is my server.cfg : 

# Only change the IP if you're using a server with multiple network interfaces, otherwise change the port only.
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

set es_enableCustomData 1
set mysql_connection_string "server=127.0.0.1;database=essentialmode;password:root;userid=root;"

add_ace resource.essentialmode command.sets allow
add_ace resource.essentialmode command.add_principal allow
add_ace resource.essentialmode command.add_ace allow

# These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard

start essentialmode
start es_admin2
start es_extended

**Comment by Zerefdev** [comment]
Try this (if user is root and password is also root)
`set mysql_connection_string "server=localhost;uid=root;password=root;database=essentialmode"`

**Comment by Domitresku** [comment]
Hello, your advice didn't help, can you contact me trough discord ?


Domitresku#3382

po 21. 10. 2019 o 18:08 Zerefdev <notifications@github.com> napísal(a):
