### ISSUE TITLE
(fie ld 'showNotification')  SCRIPT ERROR: @es_extended/server/main.lua:368

### ISSUE THREAD

**Issue by Drdrin** [ESX-Org/es_extended#376]
SCRIPT ERROR: @es_extended/server/main.lua:368: attempt to call a nil value (fie ld 'showNotification')

After throwing items on the floor this error appears

With this error you can no longer drop items it does not appear in inventory

**Comment by Drdrin** [comment]
SCRIPT ERROR: @es_extended/server/main.lua:368, (field 'ld 'showNotification')
SCRIPT ERROR: @es_extended/server/main.lua:383, (field 'ld 'showNotification')
SCRIPT ERROR: @es_extended/server/main.lua:398, (field 'ld 'showNotification')
SCRIPT ERROR: @es_extended/server/main.lua:438, (field 'canCarryItem')

**Comment by DanyCryEn** [comment]
solved??
