### ISSUE TITLE
Picking items back up

### ISSUE THREAD

**Issue by DyJaLo** [ESX-Org/es_extended#38]
Not sure if I have a setting wrong or something, but for some reason when I drop for example gold, I'm unable to pick it back up for reason "Not enough room for Gold" even though I JUST had it in my inventory. BUT if I drop a weapon, I can pick it back up with no issues. Anything I can do to fix this?

https://gyazo.com/dc838b176013d61aaf4f83ebafe44bbd < Gif of my issue.

**Comment by HumanTree92** [comment]
I am having an issue with this as well. Say i have 6 Coke on me. And i drop the 6 Coke. When i got to pickup the item it says "You do not have enough space for in your inventory to pickup Coke!" where would i go to set this to allow me to pickup items. I can drop Cash/Guns & pick them back up. I tried to drop 1 water. Once dropped i couldn't pickup that 1 water.

**Comment by HumanTree92** [comment]
To fix my issue i needed to go to my database and change the limit of the items from -1 to for say 10. Then if i drop 1-10 of the items i can pickup them backup.

**Comment by Dimmies** [comment]
Issue can be closed :)

**Comment by MarioRogue** [comment]
If there is too much on the floor then  you won't be able to pick it up but lets say you dropped 6 gold and the max is 10, then you could pick up the gold, but if there was 11 on the floor, it will just say you don't have enough space, so there could be a fix if you calculate how much you can pick up vs how much on the floor pick whatever on the floor, throwback what you can't hold

**Comment by HumanTree92** [comment]
Well after putting a limit in the DB if say i have water set at a max of 10 and there was 11 on the floor i would pickup 10 and not the 1. The 1 would still be there.

**Comment by CoreyMcCown13** [comment]
@HumanTree92 @MarioRogue I submitted a pull request that will fix your issues if/when the request is approved. Otherwise, it's a single line change in the server/main.lua file that I made, you can update yours pretty easily.

**Comment by ElPumpo** [comment]
This bug has been fixed, update esx and enjoy!
