### ISSUE TITLE
Console error xPlayer.canCarryItem with esx_shops

### ISSUE THREAD

**Issue by Letsion** [ESX-Org/es_extended#381]
SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field ‘weight’)

getWeight (@es_extended/server/classes/player.lua:358)
ref (@es_extended/server/classes/player.lua:365)
handler (@esx_shops/server/main.lua:61)

**Comment by ElPumpo** [comment]
Update your SQL
