### ISSUE TITLE
es_extended error

### ISSUE THREAD

**Issue by gmkaizzer** [ESX-Org/es_extended#382]
> SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')
> canCarryItem (@es_extended/server/classes/player.lua:365)
> handler (@es_extended/server/main.lua:438)

How to fix this problem from es_extended

**Comment by Havoc1031** [comment]
did you find a fix for this?

**Comment by Tarantulis1** [comment]
Guys did you find a fix?
