### ISSUE TITLE
Max items is 350

### ISSUE THREAD

**Issue by KanikulyCZ** [ESX-Org/es_extended#385]
Hello, i found problem, i cannot have more than 350 items on server, its possible to change this limit ?

**Comment by lukaskabc** [comment]
Agree

**Comment by ElPumpo** [comment]
No and why on earth do you have so many items?

**Comment by KanikulyCZ** [comment]
to improve the quality of roleplay? why its not possible?

**Comment by lukaskabc** [comment]
why no? what is reason of this limit? can you explain where is problem? (i can change it on my copy of ESX) And WHY? because never will be enough items ;)

**Comment by lukaskabc** [comment]
@ElPumpo

**Comment by AleDema** [comment]
Maybe if xPlayer class didn't have to load all inventory items even if you don't have them, this stupid limit wouldn't exist.

**Comment by lukaskabc** [comment]
yea, damm it, I allready solve it rewriting some parts of esx

**Comment by AleDema** [comment]
Seems like thats the only way, thanks Pumpo for being lazy

**Comment by lukaskabc** [comment]
yep, community and anyone else must take care about their self
¯\_(ツ)_/¯

**Comment by KanikulyCZ** [comment]
Lol sad ElPumpo  blocking people for true :D

**Comment by HumanTree92** [comment]
> 
> 
> Lol sad ElPumpo blocking people for true :D

Well people trash talking about ESX. Yeah it has its ups & downs. This issue about Max Items has been talked about many times. Yeah i understand what people are saying about Max Items being 350 but that is a lot of items. Would actually love to see all the items lol. But simply removing loading/saving all inventory items would put a lot of work for when they are working on other important stuff like hopefully moving away from other scripts & making their own.
