### ISSUE TITLE
Issue the moment I joined the server

### ISSUE THREAD

**Issue by clumsyzombie** [ESX-Org/es_extended#39]
I added ees_eextended and the moment I joined the server I started getting the following errors just trying to make heads and tails out of the issue with this. This is just me joining the server I just Loaded this server ruing essentials 5 

I am also working with these resources 
# Initialize System Main Files
start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start playernames
start es_AdvancedFuel
start FamilyRP-Styled-Voice-master
restart sessionmanager

# Starting Essentialmode
start mysql-async
start essentialmode
start esplugin_mysql
start es_admin2
start es_extended
start esx_menu_default
start esx_menu_list
start esx_menu_dialog
start new_banking
start esx_addonaccount
start esx_jobs

Error I am getting

Connecting: ClumsyZombie
Access denied for command add_principal.
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:351: server/main.lua:237: atte
mpt to index a nil value (global 'Async')
stack traceback:
        server/main.lua:237: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
Error running system event handling function for resource essentialmode: citizen:/scripting/lua/scheduler.lua:41: Failed to execute
 thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in local 'cb'
        server/player/login.lua:145: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:335: in function <citizen:/scripting/lua/scheduler.lua:322>

**Comment by ElPumpo** [comment]
You've obviously not installed ES correctly. Do you have the following in your server cfg:
```
add_ace resource.essentialmode command.add_ace allow
add_ace resource.essentialmode command.add_principal allow
```
