### ISSUE TITLE
Missing column "limit" in "items" table in sql import file

### ISSUE THREAD

**Issue by pwnjack** [ESX-Org/es_extended#395]
I did a clean installation and proceeded to import the sql file to create the needed tables in my db but it seems that table "items" is missing the column "limit". A lot of other plugins (like BasicNeeds) complain during installation because of that.

**Comment by UnorthadoxPigeon** [comment]
I think its now weight.

**Comment by niekschoemaker** [comment]
See commit: [145f8eb](https://github.com/ESX-Org/es_extended/commit/145f8ebe755670dba185ce86ddcf2b0bca266926)
