### ISSUE TITLE
How low can we go on the weight?

### ISSUE THREAD

**Issue by jigglyblunt** [ESX-Org/es_extended#399]
The new weight system support decimals?

example:
Item- GramWeed = 0.10) vs (the default = 1

I'm looking at switching the server over, just trying to plan ahead for an idea of limits and weights essentially.

Thanks,
JB

**Comment by LeoLight868** [comment]
same here. stock at limit 1. cant drop below

**Comment by jigglyblunt** [comment]
thank you for updating, appreciate it
-JB

**Comment by ElPumpo** [comment]
Jiggly what I would do is simply modify the max weight to a greater number. Dont need to complicate it with decimals.. but you could if you really wanted to.
