### ISSUE TITLE
ÅÄÖ not working in latest version of ESX

### ISSUE THREAD

**Issue by TheRavenBlue** [ESX-Org/es_extended#40]
Hi!

I noticed that ÅÄÖ are not working anylonger it worked on a older version of ESX, this applies to all commands such as /report and so on.
The regular chat works without problem its just ESX that is not showing ÅÄÖ the message comes up blank.

**Comment by TheRavenBlue** [comment]
Notices another odd thing, if I do for example "/report" åäö it does not show the åäö, but if I do "//report åäö" then åäö will work correctly.

**Comment by ElPumpo** [comment]
It's a problem with ES5
