### ISSUE TITLE
Error when player connect

### ISSUE THREAD

**Issue by vWernay** [ESX-Org/es_extended#403]
When a player connect shows this in CMD:

SCRIPT ERROR: @es_extended/server/main.lua:61: attempt to index a nil value (field '?')
> ref (@es_extended/server/main.lua:61)
>  (@mysql-async/mysql-async.js:14959)

plz help me, i updated the: essentialmode, async, mysql-async, esplugin-mysql

es_extended version is: 1.1.0

**Comment by ElPumpo** [comment]
Reinstall esx
