### ISSUE TITLE
Error with xPlayer.addWeaponComponent

### ISSUE THREAD

**Issue by hichay** [ESX-Org/es_extended#404]
so i try to use xPlayer.addWeaponComponent in server to add a component but it alway give me this error attempt to call a nil value (field 'addWeaponComponent')
anyone have solution for this one ??.
this is what i use xPlayer.addWeaponComponent('WEAPON_ASSAULTRIFLE', 'flashlight')

**Comment by ElPumpo** [comment]
Update esx
