### ISSUE TITLE
Issue with es_extended 

### ISSUE THREAD

**Issue by asgraal** [ESX-Org/es_extended#407]
Hello, i'm using es_drugs and es_shops with the last version of es_extended and when i buy something or i take marijuana, i see this error in the console and i recive nothing. Can anyone help me? Thanks.

**The error:** 
`SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')`

**Comment by Richards0nd** [comment]
This is because probably in your database, in the table 'items' does not have the column weight
This is probably causing the error, check if this column exists, if not, I recommend creating it.

**Comment by asgraal** [comment]
Oh thanks! You helped me a lot! Another question (sorry): how i can set the spawn point as the last place when i left the server? Thanks!
