### ISSUE TITLE
es_extended resource time warning

### ISSUE THREAD

**Issue by XvenDeR** [ESX-Org/es_extended#419]
This causes problems.
![image](https://user-images.githubusercontent.com/29688478/71735936-76010700-2e58-11ea-8fb5-0cbde0a90fcf.png)
![image](https://user-images.githubusercontent.com/29688478/71735953-85805000-2e58-11ea-8b63-95e4fd10da52.png)
`
-- Pickups
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)

		local playerPed = PlayerPedId()
		local coords = GetEntityCoords(playerPed)
		
		-- if there's no nearby pickups we can wait a bit to save performance
		if next(pickups) == nil then
			Citizen.Wait(500)
		end

		for k,v in pairs(pickups) do
			local distance = GetDistanceBetweenCoords(coords, v.coords.x, v.coords.y, v.coords.z, true)
			local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()

			if distance <= 5.0 then
				ESX.Game.Utils.DrawText3D({
					x = v.coords.x,
					y = v.coords.y,
					z = v.coords.z + 0.25
				}, v.label)
			end

			if (closestDistance == -1 or closestDistance > 3) and distance <= 1.0 and not v.inRange and IsPedOnFoot(playerPed) then
				TriggerServerEvent('esx:onPickup', v.id)
				PlaySoundFrontend(-1, 'PICK_UP', 'HUD_FRONTEND_DEFAULT_SOUNDSET', false)
				v.inRange = true
			end
		end
	end
end)
`

**Comment by ElPumpo** [comment]
Try the new version https://github.com/ESX-Org/es_extended/commit/2f751524578980e0966c9f6b68be4d094de484f7

**Comment by DanyCryEn** [comment]
Any Fix?
