### ISSUE TITLE
error when picking up items.

### ISSUE THREAD

**Issue by mikak00s** [ESX-Org/es_extended#423]
When i throw an item and then trying to pick it up i get this error.
![image](https://user-images.githubusercontent.com/58352902/71784653-51469400-2ffe-11ea-87a6-1d19cb929d67.png)

**Comment by schwim0341** [comment]
Do the items you're throwing have a weight assigned to them in the database?

**Comment by mikak00s** [comment]
Yes, all of them have weight as 1.

**Comment by ElPumpo** [comment]
Update esx
