### ISSUE TITLE
Script ERROR: @es_extended/server/main.lua:123: attempt to index a nil value (field ‘?’)

### ISSUE THREAD

**Issue by AwaYBG** [ESX-Org/es_extended#431]
![image](https://user-images.githubusercontent.com/54179878/71898502-52ff7d00-310e-11ea-8549-fa91d36ce46f.png)

**Comment by schwim0341** [comment]
It's not showing because you've broken the install.  Go through the entire startup log and find the first error and work from there.

**Comment by AwaYBG** [comment]
> It's not showing because you've broken the install. Go through the entire startup log and find the first error and work from there.

I'm installing all my servers the same method.. it works on them and there are no crashes when I open the configs its the default config for main.lua and mysql-async.js. It should work

**Comment by BloodyGamer** [comment]
which solution worked for u mate?
