### ISSUE TITLE
Drugs systems broken with new update

### ISSUE THREAD

**Issue by SidVicious99** [ESX-Org/es_extended#436]
This is the error it throws out with esx_drugs:

Error resuming coroutine: server/esx_drugs_sv.lua:53: attempt to compare nil with number
stack traceback:
        server/esx_drugs_sv.lua:53: in function <server/esx_drugs_sv.lua:45>

I also tried it with esx_illegal_drugs:

Error resuming coroutine: server/esx_illegal_drugs_sv.lua:390: attempt to compare nil with number
stack traceback:
server/esx_illegal_drugs_sv.lua:390: in function <server/esx_illegal_drugs_sv.lua:382>

It seems like the functions have stopped working with the new version, any help appreciated :)

**Comment by SidVicious99** [comment]
Why did you close it without replying? I'm confused lol.

**Comment by SleepeXapu** [comment]
> Why did you close it without replying? I'm confused lol.

I think thats normal?

**Comment by HumanTree92** [comment]
> 
> 
> Why did you close it without replying? I'm confused lol.

Open the issue for the correct Script. Meaning if you having issue with esx_drugs the issue should be posted under that Github Page & not es_extended.
