### ISSUE TITLE
picking up items weight error??

### ISSUE THREAD

**Issue by ZayOsama** [ESX-Org/es_extended#438]
I keep getting this error when trying to pickup dropped items.  

@es_extended/server/classes/player.lua:362: attempt to perform arithmetic on a nil value (field ‘weight’)

**Comment by criminalist** [comment]
Approximately the same problem, it is impossible to pick up items, it says there is no space in the inventory, when buying in a store everything is fine.

**Comment by ZayOsama** [comment]
criminalist did you solve your issue yet?

**Comment by criminalist** [comment]
No

пт, 10 янв. 2020 г., 21:05 ZayOsama <notifications@github.com>:

**Comment by itsxScrubz** [comment]
Yeah it's broken for me too.

**Comment by ZayOsama** [comment]
i got the latest so im not sure why?

**Comment by criminalist** [comment]
I solved the problem with picking up items
in the database, transferred the data in the field weight = -1 to 0
and recursively changed .limit to weight in all scripts
Anyway, it helped me.

**Comment by ZayOsama** [comment]
why close without answering

**Comment by schwim0341** [comment]
Probably because it's not an issue with a script but due to a mixing of limit and weight systems. Hit up this discord for assistance in altering scripts to work with the new system: https://discord.gg/F5e8aEk
