### ISSUE TITLE
How can I replace the default inventory?

### ISSUE THREAD

**Issue by AwaYBG** [ESX-Org/es_extended#441]
I've got a inventory that is custom but when I press F2 it shows the default inventory and the custom one, how can I disable the default one?

**Comment by Duqino** [comment]
If you have not found a way too turn it off:

es_extended / client / main.lua
line 451 put -- infront off it

--RegisterKeyMapping('showinventory', _U('keymap_showinventory'), 'keyboard', 'F2')

**Comment by itxnobody** [comment]
How can i change its keybind
