### ISSUE TITLE
Server sided optimization.

### ISSUE THREAD

**Issue by ObamaCareLover** [ESX-Org/es_extended#449]
I have recently discovered a large optimization issue within my server. I begun to notice some server sided hitches when someone would use /report as an example. And when my server is full(64/64) the hitch warnings get up to ~300ms hitch warnings every couple of seconds. I have narrowed it down to this function in particular using profiler.
```lua
for i=1, #xPlayers, 1 do
	local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
	if(xPlayer.getGroup() == 'superadmin' or xPlayer.getGroup() == 'admin' or xPlayer.getGroup() == 'mod')then
		if xPlayers[i] ~= _source then
			TriggerClientEvent('chat:addMessage', xPlayers[i], {args = {"^1REPORT", " (^2" .. GetPlayerName(_source) .." | ".._source.."^0) " .. table.concat(args, " ")}})
		end
	end
end
```

This is due to the fact that it pulls user tables for every active player. I was wondering, if there was a more optimal way inorder to pull the getGroup field, or even better, be able to specify exactly what field you would like to fetch without having to pull the entire user profile. Appreciate everything you guys contribute to the FiveM world.

**Comment by ElPumpo** [comment]
Take this somewhere else. But I would've saved all online admins in a table
