### ISSUE TITLE
Setting up ESX 

### ISSUE THREAD

**Issue by Spenoabdiel** [ESX-Org/es_extended#452]
Im using HeidiSQL and Xampp to setup my ESX server, everything seems to be good, I saw a video on how to install everything to make it work, but now im getting these errors, I've been looking for help, videos and there's nothing that can help me fix it. <img width="960" alt="Error 1" src="https://user-images.githubusercontent.com/60018997/72690035-11100700-3b10-11ea-9af9-d6c433589aed.png">
<img width="960" alt="Error 2" src="https://user-images.githubusercontent.com/60018997/72690036-11100700-3b10-11ea-8d23-2ef5bdb4eb8b.png">
<img width="960" alt="Error 3" src="https://user-images.githubusercontent.com/60018997/72690037-11100700-3b10-11ea-92ca-bb4c42ae54a2.png">
<img width="960" alt="Error 4" src="https://user-images.githubusercontent.com/60018997/72690038-11100700-3b10-11ea-9eea-0259b5b1ef6c.png">
<img width="960" alt="Error 5" src="https://user-images.githubusercontent.com/60018997/72690039-11a89d80-3b10-11ea-8d88-935cd971cf11.png">
<img width="960" alt="Error 6" src="https://user-images.githubusercontent.com/60018997/72690040-11a89d80-3b10-11ea-8026-d86325f68394.png">

**Comment by FlawwsX** [comment]
Read... "unknown database"

**Comment by schwim0341** [comment]
It's literally telling you that you're trying to connect to a database called essentialmode when you don't have a database named that.  Either rename your database or change your connection string in server.cfg to connect to the properly named database.

**Comment by Spenoabdiel** [comment]
Ok, but it says that I alredy have ona database called "essentialmode"
<img width="960" alt="databASE" src="https://user-images.githubusercontent.com/60018997/72690414-2c7d1100-3b14-11ea-9dad-96ed35ae8973.png">

**Comment by Spenoabdiel** [comment]
Now it says that I dont have tables created, but its in the scrip - for example - CREATE TABLE "addon_inventory" ...
<img width="960" alt="databASE" src="https://user-images.githubusercontent.com/60018997/72691522-f775bc00-3b1d-11ea-80b6-931bb4b9a7dd.png">
Here's the script, I hope someone help me, I want to do this so bad. 
<img width="960" alt="Table error" src="https://user-images.githubusercontent.com/60018997/72691564-44f22900-3b1e-11ea-86c9-b6ac41e50519.png">
