### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by stickybombz** [ESX-Org/es_extended#453]
I am trying to lock certain commands to be superadmin, such as /dv. I have changed the rank from admin to superadmin, however those labeled as admin can still /dv a car. Any assistance is appreciated

**Comment by benzon** [comment]
You need to go in to es_extended/server/commands.lua

Find https://github.com/ESX-Org/es_extended/blob/cced6c955e1934cfc5ac3bb275ff73261ca8b47a/server/commands.lua#L61

And change admin to superadmin

But i would recommend letting even mods do /dv

**Comment by ElPumpo** [comment]
Thanks for the misleading title
