### ISSUE TITLE
Issue with new position saving method

### ISSUE THREAD

**Issue by benzon** [ESX-Org/es_extended#455]
Hi

So found 2 issues with the new position saving.

1) Saving coords somehow breaks now and a again when you add skinchanger/esx_skin in to the mix, it get's stuck in the loop checking if loadout is loaded.

Okay figured out one of them that was my stupidity i changed the field type and i removed the default position ofc.

**Comment by benzon** [comment]
Okay so from testings it's esx_skin causing the issue.

It looks like

TriggerEvent('skinchanger:modelLoaded')

Is somewhat a problem not sure if it's slower computers that will have issues with that our if it's 50/50

**Comment by benzon** [comment]
Ended up getting the guy to try out adding the trigger inside loadSkin, and it looks like that worked.

```
RegisterNetEvent('skinchanger:loadSkin')
AddEventHandler('skinchanger:loadSkin', function(skin, cb)
	if skin['sex'] ~= LastSex then
		LoadSkin = skin

		if skin['sex'] == 0 then
			TriggerEvent('skinchanger:loadDefaultModel', true, cb)
		else
			TriggerEvent('skinchanger:loadDefaultModel', false, cb)
		end
	else
		ApplySkin(skin)

		if cb ~= nil then
			cb()
		end
	end

	LastSex = skin['sex']
        TriggerEvent('skinchanger:modelLoaded')
end)
```

**Comment by SleepeXapu** [comment]
Yes esx_skin startet to bug for me and also you spawn as michal and if you do /register it trows an error at the end saying that the identifier is invalid

**Comment by ElPumpo** [comment]
Closing as this isnt an issue if all is properly installed, if not prove me wrong
