### ISSUE TITLE
Script Error 

### ISSUE THREAD

**Issue by Trident40** [ESX-Org/es_extended#458]
Had to update my ES_Extended once I did i got the following error in my console and can't seem to work out how to fix.
![0a2f950ba11d797b9e7652fca27d5ec9](https://user-images.githubusercontent.com/23030596/72718213-580af600-3b2a-11ea-9ec8-3322256e982a.png)

**Comment by benzon** [comment]
You might be missing something in your config.lua :)

**Comment by benzon** [comment]
the thing thats an issue in your case is Config.Accounts

**Comment by Trident40** [comment]
Just had a look.. Does this look right? :/

![0a2f950ba11d797b9e7652fca27d5ec9](https://user-images.githubusercontent.com/23030596/72719117-12e7c380-3b2c-11ea-8ace-c736f6656737.png)


> the thing thats an issue in your case is Config.Accounts

**Comment by ElPumpo** [comment]
`Config.Locale = 'en`
