### ISSUE TITLE
SCRIPT ERROR functions.lua

### ISSUE THREAD

**Issue by Arcainex** [ESX-Org/es_extended#465]
Go the following error after updating:
SCRIPT ERROR: @es_extended/client/functions.lua:300: attempt to index a nil value (local 'cords') 
![image](https://user-images.githubusercontent.com/36787454/72800815-1b312300-3c40-11ea-913f-aaa908d83fa2.png)

**Comment by tonibanks** [comment]
I have same issue with this where is the answer?

**Comment by DanyCryEn** [comment]
Solved?? how?
