### ISSUE TITLE
Error on player connect

### ISSUE THREAD

**Issue by Burockk** [ESX-Org/es_extended#476]
![image](https://user-images.githubusercontent.com/10358468/73545924-5d7f0f00-444d-11ea-881f-ed3d4fe33ed5.png)

I get this error and I cannot solve it I tried many things tried to reinstall server and other things but did not work. this is a full fresh server but I get this error how can I fix it ?

**Comment by TobiClaraPA** [comment]
How did you solve it?

**Comment by Burockk** [comment]
Be sure you have tables in ur database with correct names.

iPhone’umdan gönderildi

TobiClaraPA <notifications@github.com> şunları yazdı (3 Şub 2020 07:34):

﻿

How did you solve it?
