### ISSUE TITLE
@es_extended/server/classes/player.lua:362: attempt to perform arithmetic on a nil value (field 'weight')

### ISSUE THREAD

**Issue by KamorakRP** [ESX-Org/es_extended#478]
SCRIPT ERROR: @es_extended/server/classes/player.lua:362: attempt to perform arithmetic on a nil value (field 'weight')
> getWeight (@es_extended/server/classes/player.lua:362)
> ref (@es_extended/server/classes/player.lua:369)
> handler (@esx_supermarket/server/main.lua:62)

**Comment by ElPumpo** [comment]
> You will get that error if the `weight` column in the `items` database table is missing.
