### ISSUE TITLE
why steam name in users removed ? 

### ISSUE THREAD

**Issue by H0ssein** [ESX-Org/es_extended#480]
i use that name to manage my admins ! can i put it back ?

**Comment by H0ssein** [comment]
`    TriggerEvent('es:getPlayerFromId', _source, function(player)
        -- Update user name in DB
        table.insert(tasks, function(cb)
            MySQL.Async.execute('UPDATE users SET name = @name WHERE identifier = @identifier', {
                ['@identifier'] = player.getIdentifier(),
                ['@name'] = userData.playerName
            }, function(rowsChanged)
                cb()
            end)
        end)`

**Comment by KamorakRP** [comment]
same, and the new players cannot be revived
