### ISSUE TITLE
Mysql query es_extended

### ISSUE THREAD

**Issue by XGameRsloroyale** [ESX-Org/es_extended#481]
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "UPDATE users SET name = 'XGameR' WHERE identifier = 'steam:11000013c549882'": Cannot read property 'query' of undefined
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM user_accounts WHERE identifier = 'steam:11000013c549882'": Cannot read property 'query' of undefined
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM user_inventory WHERE identifier = 'steam:11000013c549882'": Cannot read property 'query' of undefined
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT job, job_grade, loadout, position FROM users WHERE identifier = 'steam:11000013c549882'": Cannot read property 'query' of undefined

Idk what to do here. Please help how to fix it i really dk. Thanks

**Comment by Irkutsk38** [comment]
Hi. If you are making a server from scratch, then look at this tutorial https://www.youtube.com/watch?v=svRZVc0tJbU
