### ISSUE TITLE
multiple items when using create pickups

### ISSUE THREAD

**Issue by ShadowOfVoid** [ESX-Org/es_extended#482]
as ive tested and checked the codes if you drop an item it will drop the item for every online player in front of them which will make a single item available to pickup by everyone in their position . also why not using SpawnObject instead of local spawn object ?

**Comment by ShadowOfVoid** [comment]
making a single specific location for the drops and using local spawn object fixed the issue

**Comment by ElPumpo** [comment]
Is this a question Or an issue?

**Comment by ShadowOfVoid** [comment]
its a bug ofc , you should fix it because it will drop item in fron of everyone when you create pickup item like drop an item from your inventory it will create pickup cash bag in front of every body because it takes every single player cords and + forward amount and then create the local object. it should be fixed by using a single drop location

**Comment by ShadowOfVoid** [comment]
TriggerClientEvent('esx:createPickup', -1, pickupId, xPlayer.getCoords(1), label, playerId, type, name, components) instead of the TriggerClientEvent('esx:createPickup', playerId, pickupId, xPlayer.getCoords(), label, playerId, type, name, components) in the server/function.lua for ESX.CreatePickup function
