### ISSUE TITLE
F2 Doesn`t do nothing...

### ISSUE THREAD

**Issue by eltsufin** [ESX-Org/es_extended#492]
If i press F2 ingame, my inventory doesn t open. But if i run command in chat: /showinventory everything works perfectly! I need fast help.

**Comment by marciogalvao89** [comment]
i think its fivem bug, becouse when you join, works good, after few minutes stop work

**Comment by eltsufin** [comment]
No, it does not work any time..

**Comment by ShadowOfVoid** [comment]
its FiveM RegisterKeyMapping issue, i converted back to creating a thread and check for the inputs

**Comment by ElPumpo** [comment]
Yea something is wrong with that native imma revert that code

**Comment by eltsufin** [comment]
It works maybe 1 minute after i go to the server, but then anything happens...?

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/b2a46fdfb36fbbc5e5e579255422d0b75c8818fb
