### ISSUE TITLE
Cursor stays on screen

### ISSUE THREAD

**Issue by ElDuckyy** [ESX-Org/es_extended#505]
So I have installed Es admin and it all works but I am having a problem where if I close the menu the cursor stays on the screen and I can move my character does anyone know how to fix this please

**Comment by HumanTree92** [comment]
Did u rename the es_admin to es_admin2

**Comment by ElDuckyy** [comment]
It was already that

**Comment by HumanTree92** [comment]
I remember having this issue. The problem is with es_admin2. When i first had that error it was b/c the script folder was es_admin & not es_admin2
