### ISSUE TITLE
Player Last Position not saving

### ISSUE THREAD

**Issue by JEStudios** [ESX-Org/es_extended#506]
Default Server build with just ESX and the required with Ambulance Job and Police Job, not saving the last position on reverts to the default position in the job center. 

1. Player logs out of the server in sandy and upon re-entry they are back at the default coords the job center. 

can post server cfg if need.

ESX Build: Latest 
Jobs: Latest Police and Ambulance

**Comment by ElPumpo** [comment]
Read the console dummy
