### ISSUE TITLE
Player position not updating..

### ISSUE THREAD

**Issue by JEStudios** [ESX-Org/es_extended#507]
Default Server build with just ESX and the required with Ambulance Job and Police Job, not saving the last position on reverts to the default position in the job center.

Player logs out of the server in sandy and upon re-entry they are back at the default coords the job center.
can post server cfg if need.

ESX Build: Latest

Console : No errors being printed or message to tell me that there is missing info
![image](https://user-images.githubusercontent.com/6571481/74656026-61a07180-515b-11ea-9c79-dcf66d7c1339.png)

F8 Console: I have the following error 
![image](https://user-images.githubusercontent.com/6571481/74655572-8ea05480-515a-11ea-885d-a23127e1a876.png)

**Comment by ElPumpo** [comment]
Update esx
