### ISSUE TITLE
Last position doesn't get saved

### ISSUE THREAD

**Issue by Yedoo** [ESX-Org/es_extended#509]
Hey.

When I leave, console log says: [es_extended] [INFO] Saved player "yedo"
But it doesn't actually save my last position. I have everything started in the order from the DOCS, i have all the .sqls runned.
Any fixes?

**Comment by ElPumpo** [comment]
It does save perfectly fine, but the save interval sync to server can be adjusted!

**Comment by Yedoo** [comment]
If it would save perfectly fine, i wouldn't have opened this as a issue...
