### ISSUE TITLE
Group doesnt work

### ISSUE THREAD

**Issue by rex2630** [ESX-Org/es_extended#510]
Title says its all. Maybe im registering  groups wrong, but i dont think so, because even user commands doesnt work after making new char. So....

**Comment by rex2630** [comment]
![image](https://user-images.githubusercontent.com/30006554/74675207-57aa5d00-51b3-11ea-890f-bd6a712f9db9.png)

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/b6761d106eecbb9a39cc7245c0803d5266ed1d89

**Comment by rex2630** [comment]
Bad thing is that it doesn work. This not helped me at all. I had it all time
