### ISSUE TITLE
Position doesn't Save or Load?

### ISSUE THREAD

**Issue by Vathalla** [ESX-Org/es_extended#514]
After Updating it to the latest version, the server i've been working on no longer saves position after disconnecting from the game . So i decided to make a fresh install. But it still doesn't seem to save Player Position. There's no error or anything.  Am i doing something wrong?

SERVER CFG:

ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
restart sessionmanager
ensure loadingscreen
ensure hardcap
ensure baseevents
start mysql-async
start es_extended
start async

**Comment by DecodazTV** [comment]
got the same issue i changed the varchar 53 in the sql to 255 (just a atm fix, probably not the best fix)

**Comment by Vathalla** [comment]
It's actually base on Config.CoordsSyncInterval. This is solved.

**Comment by TobiClaraPA** [comment]
Hello, I don't have any sql errors, but when I connect I appear anywhere except in the last location

**Comment by dhz542165** [comment]
Hello how are you fixed it please ?
