### ISSUE TITLE
Missing administrative commands

### ISSUE THREAD

**Issue by AwayFromKane** [ESX-Org/es_extended#516]
Dear ESX-Org

Since i **disabled** essentialmode because of the **new** es_extended, es_admin2 does **not** work.
I know it is normal because es_admin2 is made for essentialmode.

But do you guys have any idea what to do, or any alternative for es_admin2 i can use with this version of es_extended.

If there is not one yet i will keep using Essentialmode.

Kind regards

Kane Cant

**Comment by ElPumpo** [comment]
Yes our own administration commands will come soon

**Comment by HumanTree92** [comment]
es_admin2 was pretty trashy. Use something like EasyAdmin

**Comment by AwayFromKane** [comment]
Thanks for your fast answer, I think i'll be using EasyAdmin for now, i hope to see some administration commands in es_extended soon.

Kane Cant

**Comment by Richards0nd** [comment]
Great that they are working on a new command system for the new version of ESX
Do you have a date for completion?

**Comment by ElPumpo** [comment]
A date for completion? What do you think this, my full time job??

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/4e4ebfff7b8294be49eaa5269d043e24561c5c56 /setgroup added
