### ISSUE TITLE
Identifier and License

### ISSUE THREAD

**Issue by BennoHD** [ESX-Org/es_extended#517]
Hello, previous version of ESX was made so that on first join identifier is SteamID and license is something else.
Now, identifier is license and license is empty :D Using it with EssentialsMode make duplicate values in database.
![1](https://user-images.githubusercontent.com/13560388/74809672-05218b80-52ee-11ea-8e44-e71c6dd727b1.png)
 
Is there a way to get SteamID back to the identifier?
Am I missing something ? 

Thanks!

**Comment by ElPumpo** [comment]
No and if you cant update because of lacking skills idk what you even are doing here
