### ISSUE TITLE
Weapon Duplication

### ISSUE THREAD

**Issue by HurtsAsHell** [ESX-Org/es_extended#518]
Hi, i've a problem, when i drop a weapon, like pistol or hammer, i can pick them but it doesn't despawn so player could duplicate the weapon.
How could resolve this problem?

**Comment by 200lirolssg** [comment]
https://github.com/ESX-Org/es_extended/commit/e25f5dee2ec828fa1e80118087813240f1477093
;)

**Comment by ElPumpo** [comment]
it does work just fine?
