### ISSUE TITLE
Error when trying to use giveweapon or giveitem

### ISSUE THREAD

**Issue by chipcze** [ESX-Org/es_extended#519]
Hi! I got error. I didnt touched like 5 days the script and like few hours back it started giving me this error. i tried to disable all new things i added, but it didnt worked out... any help please to fix it?
![errror](https://user-images.githubusercontent.com/61249232/74866903-f4a3fc00-5353-11ea-80b1-3049bea1587f.png)

I dont know what to do (1st is when typing /giveitem, 2nd when typing giveweapon)

Thanks for your time!

**Comment by ElPumpo** [comment]
Inproper esx install

**Comment by chipcze** [comment]
HAHA xddd say it to ZapHosting xddd

**Comment by ElPumpo** [comment]
Go tell zap to suck a dick
