### ISSUE TITLE
QUESTION : Are items weight asked everytime ?

### ISSUE THREAD

**Issue by Slyker** [ESX-Org/es_extended#522]
Hi,
I'll try to go into as much detail as possible.

The weights of the items being stored in the database, does the client ask for the weight each time we need an item: which means that for a list of items it can quickly make a lot of requests...
Or I'm wrong and when the client is connected, the weights are loaded once and for all and we have access to a list of items with their weights directly on the client side.

If it's the first option, wouldn't it be better to pass this list on the server side in LUA and send the necessary data, it would avoid useless queries?

Thank you in advance for your answers!

**Comment by LETSWSt** [comment]
not exactly
object data is loaded into a server-side variable.
having said that a config would be much better
