### ISSUE TITLE
2 player with 1 social club account and different steam account cant register as 2 player in server 

### ISSUE THREAD

**Issue by zoomlordir** [ESX-Org/es_extended#527]
hi there
i have a problem with my server , when me and my friend connect to the server and i register in server But when my friend connected to server he was registered with my registered profile like firstname and lastname and hair face … we have a same firstname and lastname and … What should I do ?
i have latest version of ESX
we are in same socialclub account with different steam account [image ](https://pasteboard.co/IW1hepB.jpg)

**Comment by ElPumpo** [comment]
> we are in same socialclub account
