### ISSUE TITLE
Can help?

### ISSUE THREAD

**Issue by r4venx** [ESX-Org/es_extended#528]
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT job, job_grade, `group`, loadout, position, inventory FROM users WHERE identifier = 'my steam'": ER_BAD_FIELD_ERROR: Unknown column 'inventory' in 'field list'

SCRIPT ERROR: @es_extended/server/main.lua:69: attempt to index a nil value (local 'result')

Someone can helps?

**Comment by NitroX28** [comment]
yo wtf why all issues are closed without any answer

**Comment by HumanTree92** [comment]
Well if you haven't been paying attention the latest es_extended ditched STEAM. So my guess would be that something isn't setup correctly. Pretty much everything that uses ESX is being moved to R* identifier & not STEAM.

**Comment by NitroX28** [comment]
sure , i have seen that so go update everything lol

**Comment by HumanTree92** [comment]
Not my job. But things take time. You should know that the latest updates where going to break a lot of stuff. So its YOUR fault for updating to a WIP update.
