### ISSUE TITLE
New build not compatible with old db

### ISSUE THREAD

**Issue by WooAf** [ESX-Org/es_extended#529]
I've tried to use the new build with the new format of the db without success, I couldn't load my skin and when I pick a weapon from my property inventory everything seems to bug

**Comment by ElPumpo** [comment]
Not compatible with older versions, rebuild your db

**Comment by WooAf** [comment]
Actually I did rebuild my db, but each time I get an item from my propery inventory it doesn't work probably cause of the new tint function
