### ISSUE TITLE
Issue with setting a job and other commands.

### ISSUE THREAD

**Issue by NotWhoever** [ESX-Org/es_extended#53]
Hello, after the recent update I can not set a job or do any other commands, for example /car does nothing, not even an error in console,
Before you say, everything is in order and everything is updated to the newest version.

Here's the error that I am getting from /setjob id job rankid
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:348: server/commands.lua:15: attempt to index a nil value (local 'xPlayer')
stack traceback:
        server/commands.lua:15: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:334: in function <citizen:/scripting/lua/scheduler.lua:333>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:333: in function <citizen:/scripting/lua/scheduler.lua:332>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:348: in function <citizen:/scripting/lua/scheduler.lua:319>
Error running system event handling function for resource essentialmode: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:560: in field 'cmd'
        server/main.lua:114: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
NotWhoever: /setjob 1 police 0

**Comment by WSIContractor** [comment]
+1 I am getting the issue with the latest version, where I too cannot spawn in vehicles using `/car <vehname>`. If I revert to version 1.0.5 everything works. I do not see the errors like above but are getting the issue where no command work.

**Comment by ElRocaYT** [comment]
I fixed it by copying the file '' commands '' from the previous version and pasting it into the new one. It is not the best way to do it but it is a fix.

**Comment by ElPumpo** [comment]
You've installed something wrong, make sure everything is properly setup.
