### ISSUE TITLE
EssentialMode not compatible with your new 'es_extended'

### ISSUE THREAD

**Issue by Sparkito** [ESX-Org/es_extended#534]
after  **four** **days** of testing I start to desperate your **es_extended** is perfect for saving the _ammunition_ of weapons it was what I was looking for, but now **big problem** is that **es_extended** is not compatible with "**essentialmode**" because when I put `['startingBank']` `=` `GetConvar` `('es_startingBank',` `'5000')`,` I have **5000** in my **DB** but **not ingames** the cause of this is that **you added the money and the bank** in '**user_accounts**' in the **DB**  its impossible to change this for me because you all changed the lines of code in **all folder** I really **need help** !! 

**I have no errors but I don't have my money on my account when I start a new character**

**if you know how to work around it or fix it, it's really nice**

**otherwise it's a very good job thank you in advance**

**Comment by WooAf** [comment]
The new ESX Extended ditched essentialmode

**Comment by Sparkito** [comment]
how should i do i must remove it?

**Comment by WooAf** [comment]
You need to remove it and fix all your script that depends of essentialmode, search for 'es:

**Comment by Sparkito** [comment]
and to add money when someone enters the server, what should I do if I no longer have the essential mode ?

**Comment by Sparkito** [comment]
?

**Comment by WooAf** [comment]
Money is now in user_accounts

**Comment by Sparkito** [comment]
yeah but i have try this in `'esplugin_psql'` i add 
```
MySQL.Async.execute('UPDATE `user_accounts` SET `money` = 5000 WHERE `name`=@name', {name = identifier}, function(done)
			if callback then
				callback(false)
			end
		end)
```

**it works but its adds 5000 in all the labels so I get 5000 black money 5000 in cash and 5000 in the bank 5000 I can't just add 5000 in the bank**

**Comment by Sparkito** [comment]
**I cannot specify a bank or cash**

**Comment by Sparkito** [comment]
do you have any idea how i can just add 5000 in bank?

**Comment by Sparkito** [comment]
**?**

**Comment by Sparkito** [comment]
**I really need help I am blocked by those problem I await your response** :)

**Comment by Sparkito** [comment]
why close my issue ?

**Comment by jottaonline** [comment]
have same problem, dont save the money or bank

**Comment by ALENTL** [comment]
> have same problem, dont save the money or bank

ALEN TL#5009
