### ISSUE TITLE
Implement starting balances

### ISSUE THREAD

**Issue by Sparkito** [ESX-Org/es_extended#537]
```
MySQL.Async.execute('UPDATE `user_accounts` SET `money` = 5000 WHERE `name`=@name', {name = identifier}, function(done)
			if callback then
				callback(false)
			end
		end)
```
**it works but its adds 5000 in all the labels so I get 5000 black money 5000 in cash and 5000 in the bank 5000 I can't just add 5000 in the bank**

**can you explain how to add money just in bank without essentialmode ?**

**Comment by lucaspecout** [comment]
Yes Hello i have the same problem the start money

**Comment by Sparkito** [comment]
I'm new to github what does this notification mean ^^' ? 

>  added the enhancement

**Comment by Sparkito** [comment]
Tu est Français comme moi j’ai vue ^^

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Lucas Pecout <notifications@github.com>
Envoyé : Tuesday, February 25, 2020 6:47:57 PM
À : ESX-Org/es_extended <es_extended@noreply.github.com>
Cc : Sparkito <blasterzone@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [ESX-Org/es_extended] I can't add money in start for new player (#537)


Yes Hello i have the same problem the start money

**Comment by dhawton** [comment]
Your `name`=identifier shouldn't update any accounts, in theory. The identifier should reference the owner column, which stores the identifier. name is the account name.

Use something like:

MySQL.Async.execute('UPDATE `user_accounts` SET `money` = 5000 WHERE `owner`=@identifier AND `name` IN ('money','bank')', {["@identifier"] = identifier}, function(_) if callback then callback(false) end)

**Comment by christopher19049** [comment]
I'm sorry I'm angry in my message because I've never done a server so I
don't know how the scripts work.

Le sam. 29 févr. 2020 à 23:59, Daniel Hawton <notifications@github.com> a
écrit :

**Comment by nassTEAman** [comment]
> MySQL.Async.execute('UPDATE `user_accounts` SET `money` = 5000 WHERE `owner`=@identifier AND `name` IN ('money','bank')', {["@identifier"] = identifier}, function(_) if callback then callback(false) end)

Do I put this in the server main.lua

**Comment by Sparkito** [comment]
> MySQL.Async.execute('UPDATE `user_accounts` SET `money` = 5000 WHERE `owner`=@identifier AND `name` IN ('money','bank')', {["@identifier"] = identifier}, function(_) if callback then callback(false) end)

this don't work anymore i can't start get start money :/ 
it's really starting to get confusing 
all need how to give money when new player join server please

**Comment by dhawton** [comment]
Add that to the appropriate place where users are created for the first time, and it will add starting funds to your new users.

**Comment by Sparkito** [comment]
you use this version of es-extended ? @dhawton

**Comment by dhawton** [comment]
I use a heavily modified version of es_extended. I'd recommend getting a developer on your team...

**Comment by Sparkito** [comment]
I am the dev but the problem is that since essentialmode no longer have it I really have trouble :/

**Comment by Sparkito** [comment]
everyone will have to wait for updates from @ElPumpo ^^

**Comment by dhawton** [comment]
If you are the dev, you need to dive into the server luas and determine where ESX is inserting the missing accounts and run a MySQL.Async.execute method to update the "money" column on the appropriate accounts. It's really easy to do.

**Comment by Sparkito** [comment]
the place you say in this version is "player.lua" in server \ classes \   we have 

`self.createMissingAccounts = function(missingAccounts, cb)
		for k,v in ipairs(missingAccounts) do
			MySQL.Async.execute('INSERT INTO user_accounts (identifier, name) VALUES (@identifier, @name)', {
				['@identifier'] = self.identifier,
				['@name'] = v
			}, function(rowsChanged)
				if cb then
					cb()
				end
			end)
		end
	end`

i will try something here

**Comment by Sparkito** [comment]
if someone here has an idea you can participate ^^

**Comment by Sparkito** [comment]
I can't do it I only need her to move forward I look forward to your update ❤️

**Comment by ElPumpo** [comment]
As we've said we will work on this when we got time. Discuss your own solutions somewhere else
