### ISSUE TITLE
problem with extended with start money with essentialmode

### ISSUE THREAD

**Issue by christopher19049** [ESX-Org/es_extended#539]
good evening how can we add money with the last es_extended because I'm looking and I can't find it

here are the pictures
![Capture](https://user-images.githubusercontent.com/60219892/75500415-27da3100-59cd-11ea-88ac-3876b70730a8.PNG)

![20200228015313_1](https://user-images.githubusercontent.com/60219892/75500460-4fc99480-59cd-11ea-85a1-01e32c381061.jpg)

ps: dsl I am a Frenchman

thank you in advance

**Comment by christopher19049** [comment]
why you closed my ticket that my problem isn't solved.

**Comment by christopher19049** [comment]
?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by HypeLevels** [comment]
line 11 and 12

**Comment by christopher19049** [comment]
or in which file in es_extended to modify for money
