### ISSUE TITLE
Error when getting a car

### ISSUE THREAD

**Issue by HypeLevels** [ESX-Org/es_extended#543]
when i enter a car i get this error and i dont know how to fix it, i have default es_extended, just downloaded it 

[es_extended] [WARNING] Server callback "esx_vehiclecatalog:isPlateTaken" does not exist. Make sure that the server sided file really is loading, an error in that file might cause it to not load.

**Comment by ElPumpo** [comment]
Read the error????

**Comment by HypeLevels** [comment]
I did read the error, sorry to bother u im new to esx and im not a very good coder... maybe u can just point me to where the error is happening ? there are 5 files inside server folder... Sorry to bother you :(
