### ISSUE TITLE
Changing money hud

### ISSUE THREAD

**Issue by x1mart** [ESX-Org/es_extended#55]
Hello,

I'm trying to change the money hud. As you can see in the image, I want the euro symbol green on money and bank, and red on black_money.
![81a36869c9f6b573803abf63271858ad](https://user-images.githubusercontent.com/1826734/37786127-c693a69e-2df3-11e8-8696-7b5f3c3f780f.png)
I went to client/main.lua and tryied to do some modifications, what I did was this:

```
  for i=1, #xPlayer.accounts, 1 do

    local accountTpl = '<div><img src="img/accounts/bank.png"/>&nbsp;{{money}}' .. '<font style="color: rgb(0, 125, 0); font-weight: 700; margin-right: 6px;"> €</font>' .. '</div>' -- EDITADO
	
    ESX.UI.HUD.RegisterElement('account_bank', i-1, 0, accountTpl, {
      money = 0
    })

    ESX.UI.HUD.UpdateElement('account_bank', {
      money = xPlayer.accounts[i].money
    })
	
    local accountTpl = '<div><img src="img/accounts/black_money.png"/>&nbsp;{{money}}' .. '<font style="color: rgb(250, 0, 0); font-weight: 700; margin-right: 6px;"> €</font>' .. '</div>' -- EDITADO
	
    ESX.UI.HUD.RegisterElement('account_black_money', i-1, 0, accountTpl, {
      money = 1
    })

    ESX.UI.HUD.UpdateElement('account_black_money', {
      money = xPlayer.accounts[i].money
    })

  end
```

Now sometimes the bank money and black_money are the same, if I have 300€ on my bank account I have 300€ of black_money, but in the database it's correct. Can you give me some hand with this please?

**Comment by ElPumpo** [comment]
This is not really a issue with es_extended. Do your homework
