### ISSUE TITLE
Latest es_extended trigger call to 'esx:PlayerDropped'

### ISSUE THREAD

**Issue by theorize-hm** [ESX-Org/es_extended#550]
I'm using the latest es_extended, artifact and all scripts as of the time of writing this post.

On server restart, I can join the server with no issues.  I exit my client.  No issues.  However when I reconnect and exit again without restarting the server I get this error in the server console:

SCRIPT ERROR: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
> handler (@es_extended/server/main.lua:216)

The line this points to is as below:
TriggerEvent('esx:playerDropped', playerId, reason)

There does not seem to be a event handler in es_extended named 'esx:playerDropped' - was this old code from before the major update of es_extended?

I have commented out line 216 with the trigger call in the meantime which has stopped the error.

**Comment by nitroS-stack** [comment]
Did you solve it ?
