### ISSUE TITLE
ElPumpo you have a solution for my problem.

### ISSUE THREAD

**Issue by Christopher9414** [ESX-Org/es_extended#566]
ElPumpo you have a solution for my problem.

_Originally posted by @Christopher9414 in https://github.com/ESX-Org/es_extended/issues/564#issuecomment-596726156_

**Comment by ElPumpo** [comment]
keep opening a dupe issue and you'll find yourself banned from opening issues here

**Comment by Christopher9414** [comment]
frankly you don't help people they are problems I ask for a place and help you don't help.
when I make a ticket or the others close them you don't answer.

i'm sorry i'm sorry i'm shouting 
then if you want to banish me you can
