### ISSUE TITLE
2 identifier records 

### ISSUE THREAD

**Issue by DerBro11** [ESX-Org/es_extended#574]
Hello,

i installed es and esx like in the install desciption but when i join on my server
they give me two identifer id's 
First the Rockstar games ID and second the Steam ID

![Database](https://user-images.githubusercontent.com/62098210/76609350-8f3cc880-6517-11ea-897c-fb4af0ced0fb.png)

can somone help me?

(sorry for my bad english)

**Comment by hemato** [comment]
same for me ? @ElPumpo and there is no name for player.

**Comment by XvenDeR** [comment]
Where you see ES is required? You using old version which are from ancient age...
![image](https://user-images.githubusercontent.com/29688478/78010546-28a70f80-734b-11ea-9e0c-1cc33c0f759e.png)

**Comment by hemato** [comment]
> Where you see ES is required? You using old version which are from ancient age...
> ![image](https://user-images.githubusercontent.com/29688478/78010546-28a70f80-734b-11ea-9e0c-1cc33c0f759e.png)

 i will use 1.2.0 but not all scripts supported latest so...
