### ISSUE TITLE
essentialmode & esx

### ISSUE THREAD

**Issue by ZockerBoysHD** [ESX-Org/es_extended#577]
does es_extended still need essentialmode installed? Or didnt it need it in the first place?

**Comment by ReflexShot** [comment]
I wanted to ask the same question did you find any answers ?

**Comment by ZockerBoysHD** [comment]
yes, looked trough the commits of esx, they ditched ES a few updates ago
so not needed with newest version of esx

**Comment by ElPumpo** [comment]
Then close the issue, why you keeping it open? And idk maybe reading the installation manual tells you the requirements???
