### ISSUE TITLE
Not a issue just a question

### ISSUE THREAD

**Issue by Menno0** [ESX-Org/es_extended#579]
Dear,

Is it possible that you can make a list off the Weapons Components?
And that you are able to buy them / put them on your weapon / remove them?
The commands works fine but you need to know wichones you can put on.

Would be sick RP if you can buy them ect.

**Comment by HumanTree92** [comment]
[You can use this to get Weapon Info](https://wiki.rage.mp/index.php?title=Weapons)
[You can use this to get Weapon Component Info](https://wiki.rage.mp/index.php?title=Weapons_Components)
