### ISSUE TITLE
Object spawning broken

### ISSUE THREAD

**Issue by zarx1337** [ESX-Org/es_extended#58]
When I downgrade to an older version of es_extended it works but then I get message pack errors.

**Comment by JaroSound** [comment]
What version is workin for u?

**Comment by benzon** [comment]
We have to go back to the old esx_extended currently, it's something with the manifest in resource file, that breaks the object spawner quite abit.

**Comment by zarx1337** [comment]
Click on releases and use indilo53's latest release!

**Comment by benzon** [comment]
Zarx1337 you got the issue with the latest release to right ?

**Comment by benzon** [comment]
Ahh ye true, but i think the issue is just the resource manifest in the end from a thred on esx_policejob

**Comment by zarx1337** [comment]
Yea I do, alright so I should just copy the resource manifest?

**Comment by benzon** [comment]
We tryed it and it looks to fix the issue

**Comment by sirmarknlddr** [comment]
It fixes the issue, but that breaks ELS compatibility.. that resource manifest is needed for correct handling of networkID's. So fixing resource manifest creates another issue.

**Comment by benzon** [comment]
Wondering abit now this is a very old issue now will this be fixed?

**Comment by ElPumpo** [comment]
74d27e4d807df57c32ce9145ec659d2c48422258
