### ISSUE TITLE
Respawning on the default Spawn Location everytime

### ISSUE THREAD

**Issue by simpleC0de** [ESX-Org/es_extended#594]
When relogging players are still spawning not at the left location.
I defined the spawn location in the maps, the rest is left to es_extended.

**Comment by ItzTrivial** [comment]
Hello there. Im sorry for asking, but why am I reading so many Issues with the exact same Issue as I have, but every single one of them get closed without an answer? Im looking for one for 3 hours and it is really giving me a headache. Id really appreciate an answer :)

**Comment by Mycroft-Studios** [comment]
> Hello there. Im sorry for asking, but why am I reading so many Issues with the exact same Issue as I have, but every single one of them get closed without an answer? Im looking for one for 3 hours and it is really giving me a headache. Id really appreciate an answer :)

Join the official discord, we have instructions on how to fix there.
