### ISSUE TITLE
Some players cannot join the game

### ISSUE THREAD

**Issue by Rado236** [ESX-Org/es_extended#600]
After updating to the most latest version some of the players cannot join the server, another bug is with the voice everyone can hear anyone around the map

**Comment by Richards0nd** [comment]
> After updating to the most latest version some of the players cannot join the server, another bug is with the voice everyone can hear anyone around the map

Regarding the part of the players not being able to enter, it is recommended that you remove the mapmanager and the spawnmanager
They are no longer needed, regarding the problem in the voice I don't know how to inform you, I would need more details

**Comment by Rado236** [comment]
I removed them the both and they still cannot join.

**Comment by Rado236** [comment]
Some of them just stay in the loadingscreen and some complained that they can hear everyone around the map.
