### ISSUE TITLE
Players can join with the same identifier

### ISSUE THREAD

**Issue by jetpnix** [ESX-Org/es_extended#605]
When they join it results in the same user, using the same identifier. It might be caused by the same rockstar license game installed in their computer. Any workaround to this?

**Comment by ElPumpo** [comment]
I did not think of that issue, will fix it

**Comment by phpadmin1** [comment]
yeah .. already tweak this and Fixed just need to changed identifier to steam instead of license 
change to 1 so you will get steam identifier so anyone with the same license get the unique identifier.

**Comment by ElPumpo** [comment]
![image](https://user-images.githubusercontent.com/12564301/77637953-bbfcd100-6f56-11ea-9013-274d9504d2da.png)
coming soon

**Comment by phpadmin1** [comment]
I think jetpnix want to use same license but multiple players. We Cant create another steam account if that case.

**Comment by ElPumpo** [comment]
?????????????? How you gonna have two players with same license? No

**Comment by phpadmin1** [comment]
Yes we can.. Same Installed GTA on your Desktop. Try to logout and  make another Dummy steam and dummy account used the Main Steam rockstar license

**Comment by ElPumpo** [comment]
Ok but guess what first of all esx doesn't use steam identifier, and second it doesn't support two players with same identifier because of how it works.

**Comment by phpadmin1** [comment]
all esx resource works because it depends on extended.

**Comment by phpadmin1** [comment]
![image](https://user-images.githubusercontent.com/11045173/77640693-d013f300-6f95-11ea-8014-fd902e4e1edf.png)

Look at my table Same Workstation 
create another dummy steam because steam identifier have unique / primary key so new steam will create another users

**Comment by jetpnix** [comment]
yes I was trying to have multiple players with the same gta license but different steam identifiers so this was not really the best solution :)

**Comment by phpadmin1** [comment]
> yes I was trying to have multiple players with the same gta license but different steam identifiers so this was not really the best solution :)

you need to tweak a little on extended so you can use multiple players with the same license.

**Comment by jetpnix** [comment]
> 
> 
> > yes I was trying to have multiple players with the same gta license but different steam identifiers so this was not really the best solution :)
> 
> you need to tweak a little on extended so you can use multiple players with the same license.

hmm is that going back to the steam identifier again? or nah just add a new column in the database?

**Comment by phpadmin1** [comment]
just on extended. don't need to add a new column since its already a identifier column name not license.

**Comment by Duskimm** [comment]
it keeps duplicating.....

**Comment by phpadmin1** [comment]
> it keeps duplicating.....

change to steam identifier so it will not duplicate

**Comment by ElPumpo** [comment]
Reading wtf you be typing in here makes my brain bleed all my IQ points
