### ISSUE TITLE
FiveM banned es_extended last version

### ISSUE THREAD

**Issue by YisusTM01** [ESX-Org/es_extended#620]
https://gyazo.com/38ad083e40a35a0bade94ddff4aa8b44

Anyway to fix without a manual downgrade?

**FIX**
> According to their way of block, goto locales/en.lua and find ['command_save'] and edit it lol
> as in #619
> 
> P.S: I didn't test it..

**Comment by Zerefdev** [comment]
fivem ft. kans vs esx

**Comment by ModatherM** [comment]
According to their way of block, goto locales/en.lua and find ['command_save'] and edit it lol
as in #619 

P.S: I didn't test it..

**Comment by Zerefdev** [comment]
ESX README file has a link to a website that offers fiveM which is against fiveM TOS

**Comment by dhaifanco** [comment]
i alrd removed it and it happened again

**Comment by Netzwerk10** [comment]
It does not work if you change the links in the readme, the same problem comes anyway.

**Comment by YisusTM01** [comment]
> i alrd removed it and it happened again



> ESX README file has a link to a website that offers fiveM which is against fiveM TOS

yep but they don't ban the readme...




> According to their way of block, goto locales/en.lua and find ['command_save'] and edit it lol
> as in #619
> 
> P.S: I didn't test it..

Test and....WORKS.

**Comment by dhaifanco** [comment]
edit what ? can you send me the pic of your locales.lua

**Comment by Netzwerk10** [comment]
> > Ich habe es entfernt und es ist wieder passiert
> 
> > Die ESX README-Datei enthält einen Link zu einer Website, die fünf Millionen bietet, was gegen fünf Millionen Nutzungsbedingungen verstößt
> 
> Ja, aber sie verbieten die Readme nicht ...
> 
> > Gehen Sie entsprechend ihrer Blockierungsart zu locales / en.lua und suchen Sie ['command_save'] und bearbeiten Sie es lol 
> > wie in [# 619](https://github.com/ESX-Org/es_extended/pull/619)
> > PS: Ich habe es nicht getestet.
> 
> Test und .... FUNKTIONIERT.



> > i alrd removed it and it happened again
> 
> > ESX README file has a link to a website that offers fiveM which is against fiveM TOS
> 
> yep but they don't ban the readme...
> 
> > According to their way of block, goto locales/en.lua and find ['command_save'] and edit it lol
> > as in #619
> > P.S: I didn't test it..
> 
> Test and....WORKS.

ok it works!

**Comment by dhaifanco** [comment]
WHAT DO I HAVE TO CHANGE IT TO ??????
