### ISSUE TITLE
Error with es_extended

### ISSUE THREAD

**Issue by Goddamn112** [ESX-Org/es_extended#625]
Hey I'm having this eror, anyone know the fix for it? Yes I have read this error and yes I have tried downgrading the es_extended script, but it later gave me errors in the console whilst in-game: https://i.imgur.com/5DnNPkG.png

**Comment by ElPumpo** [comment]
Yes esx is blacklisted by fivem

**Comment by YisusTM01** [comment]
> Hey I'm having this eror, anyone know the fix for it? Yes I have read this error and yes I have tried downgrading the es_extended script, but it later gave me errors in the console whilst in-game: https://i.imgur.com/5DnNPkG.png

https://github.com/ESX-Org/es_extended/issues/620

**Comment by Goddamn112** [comment]
@ElPumpo  so is there a fix for this or something?

**Comment by Bebiano86** [comment]
turn off README.md

unfortunately the fivem is getting crap

**Comment by phpadmin1** [comment]
ngo and check on esx announcement you`ll know how to fixed it :-D

**Comment by phpadmin1** [comment]
> changes to an older one
> 
> unfortunately the fivem is getting crap

LOL.. Don't need to change to older one .  just renamed 1 file and works.!
