### ISSUE TITLE
Doesn't save player position 

### ISSUE THREAD

**Issue by emjy01** [ESX-Org/es_extended#628]
Hi there :) i have some issues since the last update, we removed essential , because the new extended do the same job, but now the server doesn't save the player position when they disconnect. So they are far away when they reconnect. I don't know if we can put back essential, or if there's something we miss in the config of extended

**Comment by phpadmin1** [comment]
try to change sync Interval in config - >  Config.CoordsSyncInterval   = 2 * 60000   to 500

**Comment by hifzi** [comment]
try change this 
server/main.lua
`AddEventHandler('playerDropped', function(reason)
	local playerId = source
	local xPlayer = ESX.GetPlayerFromId(playerId)

	if xPlayer then
		TriggerEvent('esx:playerDropped', playerId, reason)

		ESX.SavePlayer(xPlayer, function()
			ESX.Players[playerId] = nil
		end)
	end
end)`

change to this

`AddEventHandler('playerDropped', function(reason)
	local playerId = source
	local xPlayer = ESX.GetPlayerFromId(playerId)
       local playerPed = GetPlayerPed(playerId)
       local playerCoords = GetEntityCoords(playerPed)
       local playerHeading = ESX.Math.Round(GetEntityHeading(playerPed), 1)
       local formattedCoords = {x = ESX.Math.Round(playerCoords.x, 1), y = 
       ESX.Math.Round(playerCoords.y, 1), z = ESX.Math.Round(playerCoords.z, 1), heading = playerHeading}
	if xPlayer then
                xPlayer.updateCoords(formattedCoords)
		TriggerEvent('esx:playerDropped', playerId, reason)

		ESX.SavePlayer(xPlayer, function()
			ESX.Players[playerId] = nil
		end)
	end
end)`

Make update last coords when players exiting 
(sorry for my english)
