### ISSUE TITLE
Paycheck wrong grande name on welfare check

### ISSUE THREAD

**Issue by ElRocaYT** [ESX-Org/es_extended#63]
On es_extended/server/paycheck.lua 
At line 14 says ''if xPlayer.job.grade_name == 'interim' then'' should be ''if xPlayer.job.grade_name == 'rsa' then'' because is a welfare check not a job salary.
I try to create a pull request but i'm not good with github so i write this here.

**Comment by ElPumpo** [comment]
Yep this is a bug and the responsible code has to be redone.

**Comment by ElPumpo** [comment]
Related to #66

**Comment by ElPumpo** [comment]
Fixed in 66e7eceddf4b182be424fc1613f690d2f671de80
