### ISSUE TITLE
es_extended items limit

### ISSUE THREAD

**Issue by NightcoreIsla** [ESX-Org/es_extended#632]
i see the es_extended item manager ,seem have no any information for items.limit
essentialmode have it before
how about add it again?
if not, the esx_jobs items for player raise money ,will hard to control it
many plugins are still using limit function too

**Comment by NightcoreIsla** [comment]
i add it by myself
and it good for esx_inventoryhud &esx_jobs
if every one need, add some line

server/common.lua:28

limit = v.limit,

server/classes/player.lua:267 

```
local item = self.getInventoryItem(name)
local limit = ESX.Items[name].limit
local newCount = item.count + count
```

server/functions.lua:256:

```
ESX.GetItemLimit = function(item)
	if ESX.Items[item] then
		return ESX.Items[item].limit
	end
end
```

server/main.lua:155:

`limit = item.limit,`

**Comment by ali-exacute** [comment]
Dont add limit back again, just use weight system. Its so much better and reliable than limit

**Comment by AndyBG474** [comment]
> Dont add limit back again, just use weight system. Its so much better and reliable than limit

But my items are dublicating

**Comment by ImpulsJL** [comment]
This doesnt work for me, maybe there are more lines to add?, the inevntoryhud recognize the item´s limit but if i wanna take out some bandages (for example) theres an error

**Comment by NightcoreIsla** [comment]
> This doesnt work for me, maybe there are more lines to add?, the inevntoryhud recognize the item´s limit but if i wanna take out some bandages (for example) theres an error

paste the script error message ange the code error area ?

**Comment by fascinatingact** [comment]
Can you help me with this error. I already did everything. Also in server/classes/player.lua:267 there is already a function self.canCarryItem, so i replace it with the one that you provided. Did i do something wrong ?
![image](https://user-images.githubusercontent.com/80687279/117528904-1c3dbd80-b007-11eb-88e3-04d875d90dbe.png)

**Comment by NightcoreIsla** [comment]
> Can you help me with this error. I already did everything. Also in server/classes/player.lua:267 there is already a function self.canCarryItem, so i replace it with the one that you provided. Did i do something wrong ?
> ![image](https://user-images.githubusercontent.com/80687279/117528904-1c3dbd80-b007-11eb-88e3-04d875d90dbe.png)

post a screenshot on player.lua :420
looks like you didn,t write currently for xplayer.cancarryitem

**Comment by fascinatingact** [comment]
> > Can you help me with this error. I already did everything. Also in server/classes/player.lua:267 there is already a function self.canCarryItem, so i replace it with the one that you provided. Did i do something wrong ?
> > ![image](https://user-images.githubusercontent.com/80687279/117528904-1c3dbd80-b007-11eb-88e3-04d875d90dbe.png)
> 
> post a screenshot on player.lua :420
> looks like you didn,t write currently for xplayer.cancarryitem

![image](https://user-images.githubusercontent.com/80687279/117530491-041e6c00-b010-11eb-92e1-8f4fb1493138.png)

**Comment by NightcoreIsla** [comment]
your currentWeight get a nill value on "self.weight"
check the self.weight is ok at top
![image](https://user-images.githubusercontent.com/38730597/117533272-76964880-b01e-11eb-966d-260b931cf08a.png)
and server/main.lua
![image](https://user-images.githubusercontent.com/38730597/117533301-a0e80600-b01e-11eb-9665-51f59df0a40f.png)
![image](https://user-images.githubusercontent.com/38730597/117533309-ad6c5e80-b01e-11eb-807e-3a996fbc5e95.png)
![image](https://user-images.githubusercontent.com/38730597/117533326-c1b05b80-b01e-11eb-9424-9e72a287c63e.png)

**Comment by fascinatingact** [comment]
> your currentWeight get a nill value on "self.weight"
> check the self.weight is ok at top
> ![image](https://user-images.githubusercontent.com/38730597/117533272-76964880-b01e-11eb-966d-260b931cf08a.png)
> and server/main.lua
> ![image](https://user-images.githubusercontent.com/38730597/117533301-a0e80600-b01e-11eb-9665-51f59df0a40f.png)
> ![image](https://user-images.githubusercontent.com/38730597/117533309-ad6c5e80-b01e-11eb-807e-3a996fbc5e95.png)
> ![image](https://user-images.githubusercontent.com/38730597/117533326-c1b05b80-b01e-11eb-9424-9e72a287c63e.png)

I fixed it. I think, i just change the self.weight to self.GetWeight() and it works. Thanks by the way

**Comment by fascinatingact** [comment]
my items are duplicating help

**Comment by McJonny1234** [comment]
Good afternoon, I'm having a problem which is the following I can never search to remove items and surely it can be someone help me? thanks

**Comment by annocuoi** [comment]
Tôi đã làm thành công! Nhưng của tôi nó không để là 20/20 mà nó chỉ để 20, Ai đó có thể chỉ cho tôi biết tôi nên kiểm tra dòng lệnh nào không. Xin lỗi vì tiếng anh không được tốt
![unknown](https://user-images.githubusercontent.com/92977855/144721114-c4abb87a-a1a5-46b7-b6f1-9b5420f311bd.png)
