### ISSUE TITLE
[BUG] Item drop behaviour

### ISSUE THREAD

**Issue by XvenDeR** [ESX-Org/es_extended#633]
So currently we have this behavior of item drops, it can be dropped anywhere and will soar in air.
![image](https://user-images.githubusercontent.com/29688478/78533930-6647e480-77f2-11ea-92fa-71a2f91edcd4.png)

**Comment by HumanTree92** [comment]
This can be and should be fixed by only allowing a player to drop items if they are not in a vehicle.

**Comment by XvenDeR** [comment]
Oh right, easy fix.

**Comment by ElPumpo** [comment]
You cant drop an item if not on foot, but maybe a check if player is falling is needed
