### ISSUE TITLE
buy ammo?

### ISSUE THREAD

**Issue by Parme89** [ESX-Org/es_extended#64]
is there a way for me to implement ammo to the gangarmory? cus now when the ammo is empty the need to buy a new wep

**Comment by ElRocaYT** [comment]
There is a script for that, esx_clip or something like that

**Comment by Parme89** [comment]
Your absolutely right , thanks for that , was only looking for esx ammo but that one got removed

**Comment by ElPumpo** [comment]
Closing unrelated issue, it's not even an issue

**Comment by Parme89** [comment]
Ofc it’s an issue if you actually need and separate resource to be able to get ammo to the weapons 🤨

**Comment by HumanTree92** [comment]
I do agree that esx_weashop should have weapon clips. There was 1 guy who did make the files for it but then removed it stating that it was removed due to abuse. Which i don't know how someone would abuse code for weapon clips.

**Comment by HumanTree92** [comment]
Simple fix for this was to raise the pricing on Weapons & but also set the max ammo to give from 42 to 1000. It doesn't give 1000 ammo but it does give the max ammo the weapons can hold.
