### ISSUE TITLE
Player teleports when dead

### ISSUE THREAD

**Issue by Domitresku** [ESX-Org/es_extended#653]
Title says all. When I die, I teleport to another location that is set in fivem-map-skater. I still have deathscreen on and I have normal skater skin. I think it's bug with es_extended because in previous versions, you stayed on ground. If you can help, please help.

**Comment by ElPumpo** [comment]
Disable mapmanager, spawnmanager and fivem-map-<whatever>

**Comment by Domitresku** [comment]
Both fivem-maps ?

**Comment by Domitresku** [comment]
Delete or just remove from server.cfg?

**Comment by ElPumpo** [comment]
delete and yes all your freaking maps just make sure spawnmanager &mapmanager does NOT START ever

**Comment by Domitresku** [comment]
alright, i tried, but now, my economy won't load, and I just cannot die.

**Comment by Domitresku** [comment]
is it wrong?
