### ISSUE TITLE
There are a few errors in the locales

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/es_extended#658]
This is in the en.lua

* `['weapon_flare'] = 'flare gun',` should be `['weapon_flare'] = 'flare',`
* `['component_clip_default'] = 'default Grip',` should be `['component_clip_default'] = 'default Clip',`
* `['component_clip_extended'] = 'extended Grip',` should be `['component_clip_extended'] = 'extended Clip',`

**Comment by ElPumpo** [comment]
Nice findings
