### ISSUE TITLE
[question] company paychecks

### ISSUE THREAD

**Issue by Parme89** [ESX-Org/es_extended#66]
Whats the way to make the paychecks come from the company ? Ive read the code but cant figure out how to make the money to be taken from company

**Comment by LuaDeldu** [comment]
Did you see that there is a paycheck_company.lua file which needs to be added into the __resource.lua file? 

 Can you come on the ESX Discord to ask questions instead of opening an **issue** for a question? Thanks.

**Comment by Parme89** [comment]
Hey! Well the esx discord suddenly disapeared for me and for many other so my thought was that it was closed , cus i havent found a link thats working , can you supply a valid one ? Thanks

**Comment by ElPumpo** [comment]
Fixed in 66e7eceddf4b182be424fc1613f690d2f671de80

- Now all societies pay its employees
    - if there's no society money, the employees get no salary
