### ISSUE TITLE
No nearby player

### ISSUE THREAD

**Issue by Rado236** [ESX-Org/es_extended#661]
After getting the very latest commit I cannot give items to players it says "No nearby player" but he stands next to me. No console errors

**Comment by OwnaDash** [comment]
I get this even when i try to cuff or anything else that requires a near player, idk how to fix

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/17ac9d58468712a56c8f7316bcbb24a8dd99024d
