### ISSUE TITLE
BIG ISSUE!

### ISSUE THREAD

**Issue by SkurkenYT** [ESX-Org/es_extended#663]
So as a server owner, I want to use the newest version of es_extended. That is very good, but it crashes with esplugin_mysql due to dublicate of @identifier in the database. The reason why i use esplugin_mysql is because its needed for es_admin2 to work and everybody uses that. You also need essentialsmode. Why have you made a stupid @identifier in the database that makes the license id show for each player. ESplugin_mysql already has that in their @license in the database... Add me on discord to help me with this issue Skurken#0001

**Comment by hgg022** [comment]
Same problem here, please add a panel just to use noclip, slay, bring and goto beacause all of us needs it (that's why we use es_admin2)!

**Comment by HumanTree92** [comment]
Honestly panels are dumb. You can very easily create a Menu that does NoClip, Slay, Bring, Etc. And honestly if you wasn't there for the reasons why essentialmode, es_admin, & esplugin where ditched then you might want to go back and look why. I can tell you that essentialmode was needed.
