### ISSUE TITLE
SCRIPT ERROR: cannot resume non-suspended coroutine

### ISSUE THREAD

**Issue by stopkidd** [ESX-Org/es_extended#666]
Hello, since i updated the extended everytime the server starts up i get thease error messeges. Any ides?
![Ignorant-Pricky-Prick](https://user-images.githubusercontent.com/62605434/79548134-a08c6e00-809d-11ea-9f7f-d50829311da1.png)

**Comment by ElPumpo** [comment]
Lol fivem made so that some incompitable resources cannot be stopped, but it's no problem just make sure you remove them.
