### ISSUE TITLE
After last update...multiple errors

### ISSUE THREAD

**Issue by LeinixD** [ESX-Org/es_extended#667]
When i updated to last es_extended my hud dissapeared, i cannot open es_admin2 menu, /noclip, /setmoney, etc not working...what i can do to solve this? thanks

**Comment by phpadmin1** [comment]
because es extended don't need essential mode and es admin2 is using essential mode to work thats why /noclip or any commands from es admin will not work. 
last es_extended update is much more complicated and different to the old update. 
Please check the Read Me .

**Comment by LeinixD** [comment]
> because es extended don't need essential mode and es admin2 is using essential mode to work thats why /noclip or any commands from es admin will not work.
> last es_extended update is much more complicated and different to the old update. If you want to update extended you need to changed all your server files same time SQL files
> Please check the Read Me .

So...then how can i set money to me or people now?

**Comment by LeinixD** [comment]
> /setaccountmoney [id] money [amount]

Is it worth now to update to latest extended? i mean not all scripts may work in this one, correct?

**Comment by phpadmin1** [comment]
yes it is :-) yeah not all if you know how to reconfig a then it works

**Comment by LeinixD** [comment]
The thing is...that i am mainly checking it because my esx_shops is not
working correctly, i mean, items are there but i press buy and nothing
happens, i dont know if its esx_extended or what :/

**Comment by phpadmin1** [comment]
esx shops is working men.. use also the latest esx_shops update and extended

**Comment by LeinixD** [comment]
I tryed it with extended latest and same problem, but it fucks my hud too,
etc...its confusing

**Comment by phpadmin1** [comment]
what hud are you using? 
It works perfectly .. 
can you show your server.cfg file
