### ISSUE TITLE
Identifier? And player position save issue!

### ISSUE THREAD

**Issue by eltsufin** [ESX-Org/es_extended#668]
Hey!
I have FiveM server, but i have 1 Problem! Sometimes when player left his position does not save, it spawns randomly somewhere. And sometimes it works perfectly! 

Then i wanna ask, why identifier goes my database like this: (6d6d88gj46f78fh8wf7467hfioofj9860kf).
Not like this. (steam:362847763actd).

Please answer me! : )

**Comment by phpadmin1** [comment]
new update on extended dont use Essential mode . Its more complicated when you update if you have existing server files using essential mode and also database

**Comment by eltsufin** [comment]
So i have to change version es extended? What version i have to use?
