### ISSUE TITLE
Stuck on spawn

### ISSUE THREAD

**Issue by rviskandar21** [ESX-Org/es_extended#669]
i have issue about character fly and freeze in air, no error in console. default ped not showing.
this is screenshoot about the issue.
![48016218 27_image](https://user-images.githubusercontent.com/55821996/79569181-5e851b80-80e1-11ea-8d4c-0e8ea20cae7a.png)

please answer thanks :)

**Comment by phpadmin1** [comment]
yeah there's a bug in last 5 days update when the player load freeze in the air and i Dunno but I already fixed last 2days update so go update your extended

**Comment by rviskandar21** [comment]
> 
> 
> yeah there's a bug in last 5 days update when the player load freeze in the air and i Dunno but I already fixed last 2days update so go update your extended

i think its not fix yet because my screnshoot has taken an hours ago using lastest es_extend. i tried to delete server folders and do installation from beginning

**Comment by sssK1LL** [comment]
@rviskandar21 Have you got this fixed? I have this issue as well.

**Comment by rviskandar21** [comment]
> @rviskandar21 Have you got this fixed? I have this issue as well.

@sssK1LL unfortunately nah, i was try to change everything in es_extend lua code but nothing happend. i give up and try using past es_extend before they remodel like now.

**Comment by sssK1LL** [comment]
@rviskandar21 so you’re saying we don’t have to use the most recent update to run a server? So you’re using a past es_extended file and it has no spawn issue?

**Comment by rviskandar21** [comment]
> 
> 
> @rviskandar21 so you’re saying we don’t have to use the most recent update to run a server? So you’re using a past es_extended file and it has no spawn issue?

@sssK1LL i didnt thinking like that, if you expert with lua, so fix that for yourself. i give up because i have no idea how to fix it hehe, i just waiting them to fix it.
Maybe if you wanna some more explain about what version extended i using, you can contact to my discord : RIP#3221

**Comment by ElPumpo** [comment]
Yes having a hard time reproducing this issue, maybe the player ped changes?
