### ISSUE TITLE
Cannot give ammo (string formatting bug)

### ISSUE THREAD

**Issue by jerome80** [ESX-Org/es_extended#67]
ccess my personal menu from the F2 key, all functions function correctly, EXCEPT!
the possibility to give or to throw an item (ex: water, bread ...)
Once I make the choice to give or throw I have a window that offers me to fill in the quantity, then just below the possibility of "Send" or "Cancel".
The problem is that no matter the choice, nothing happens, impossible to go back or send or cancel, the only solution is to close the game ....

no error message in the console

**Comment by ElPumpo** [comment]
Change the title if you think of getting any help.

**Comment by ElPumpo** [comment]
Fixed, re-open if the issue persists.
