### ISSUE TITLE
global chunk

### ISSUE THREAD

**Issue by phpadmin1** [ESX-Org/es_extended#671]
last 2 days update extended got this error with my script
so I reverted my extended to last 5days update and worked!

GetClosestObject
to 
ESX.Game.GetClosestEntity

handler -> 
```
setz = vector3(261.3004, 214.5051, 101.8324)
Px,L=ESX.Game.GetClosestObject('hei_v_ilev_bk_gate2_pris',setz)
```

I get this error

![image](https://user-images.githubusercontent.com/11045173/79572104-f63d3680-80ee-11ea-822a-c1c7fcf6ab4c.png)

**Comment by ElPumpo** [comment]
invalid argument

**Comment by phpadmin1** [comment]
setz = vector3(261.3004, 214.5051, 101.8324) ??? seriously?? what argument 1 had type nil herE??
