### ISSUE TITLE
Error MessagePack.lua:830: missing bytes or MessagePack.lua:862: extra bytes

### ISSUE THREAD

**Issue by tranminhduc123** [ESX-Org/es_extended#672]
![image](https://user-images.githubusercontent.com/49990803/79572244-cf7b0200-80e6-11ea-99b0-91af6d85721f.png)
![image](https://user-images.githubusercontent.com/49990803/79572274-dbff5a80-80e6-11ea-9fe2-f33da6253c81.png)
Help me!
Error loading player characters, especially with jobs. Only the error happened to 3 or 4 people. I need some help

**Comment by phpadmin1** [comment]
latest es extended dont use essential mode anymore.. put a comment / # on your cfg files .

**Comment by tranminhduc123** [comment]
> latest es extended dont use essential mode anymore.. put a comment / # on your cfg files .
Thank you for answering me. Because I don't really understand the problem. Can you give me an example that doesn't really thank you.

**Comment by tranminhduc123** [comment]
> latest es extended dont use essential mode anymore.. put a comment / # on your cfg files .

Is it in here? Thank you for watching
![image](https://user-images.githubusercontent.com/49990803/79575839-96459080-80ec-11ea-88af-c42a178276d8.png)

**Comment by phpadmin1** [comment]
essentialmode
es admin2
esplugin mysql  use mysql-async

also remove 
spawnamanger 
map manager
fivem
baseevenrts

also you need to drop and empty  ur sql files  users and use the extended latest sql
