### ISSUE TITLE
Spawning as Franklin and frozen in the air after loading in the server. 

### ISSUE THREAD

**Issue by sssK1LL** [ESX-Org/es_extended#673]
I have no errors in the starter.bat launcher and everything else works fine, but when I load in the server I spawn frozen in the air. Is there a fix to this?

**Comment by TobiClaraPA** [comment]
Same error

**Comment by sssK1LL** [comment]
@TobiClaraPA let me know if you ever fix it, thank you.

**Comment by ElPumpo** [comment]
#669
