### ISSUE TITLE
esx_identity does not work.

### ISSUE THREAD

**Issue by AwayFromKane** [ESX-Org/es_extended#674]
Hello

I have a problem with my esx_identity. When i log in to my server for the first time when wiping the database. It only gives me the skin create menu but not my character create menu. Do you have any idea how to fix that?

Kind Regards
Kane

**Comment by forladolby** [comment]
@AwayFromKane  how did you fix it?

**Comment by AwayFromKane** [comment]
I don't fully remember but try to put this in your server.cfg

#### ESSENTIAL SETTINGS ####
set es_enableCustomData 1
add_ace resource.essentialmode command.sets allow
add_ace resource.essentialmode command.add_principal allow
add_ace resource.essentialmode command.add_ace allow
