### ISSUE TITLE
Problem, i need help : )

### ISSUE THREAD

**Issue by eltsufin** [ESX-Org/es_extended#675]
Hey!
(this is hard to explain)

In es_extended version: 1.1.0, what command gives weapon components?

Because i want to use old system what supports essentialmode, but /giveweaponcomponent does not exist. I like old steam hex in database system, because some plugins does not support this new system.

And in my server we need /giveweaponcomponents, but this new version is not good. So i need version where is: /giveweaponcomponent command, steam hex in database and it supports essentialmode?? 

So pleace help me fast, if you have older version where is /giveweaponcomponent and old steam hex system send it to me : ), or i am stupid so help me this!

**Comment by MonoChirito** [comment]
impossible
