### ISSUE TITLE
Spawning under ground

### ISSUE THREAD

**Issue by Fluffyss** [ESX-Org/es_extended#678]
Everytime you spawn you'll spawn under the street.
![image](https://user-images.githubusercontent.com/63029838/79688752-9eb6dc00-8250-11ea-9278-f14754473276.png)
No errors however in F8 or serverside.
Just installed the new ES extended and cant seem to resolve this.

**Comment by SW1FT** [comment]
This happens on my test server too, it doesn't happen 100% of the times, though.

**Comment by HumanTree92** [comment]
Yeah i have had this happen on my Test Server & Main Server. Haven't figured out a way around it yet. It only happens if you log off in an area that takes a little bit of time to load.

**Comment by NightcoreIsla** [comment]
anyone tried freeze player when login?
unfreeze later loading finish
