### ISSUE TITLE
Server hidden from server listing if mapmanager is disabled

### ISSUE THREAD

**Issue by NightcoreIsla** [ESX-Org/es_extended#685]
es_extended need disable MapManager and SpawnManager
or will happend spawn error problem,i know it.

but after i stop these, my Server will not show up in FiveM server list but still can connect with direct
how can i fix it?

btw,the map name prototype in list will lost control too
![image](https://user-images.githubusercontent.com/38730597/79720210-afc82180-8312-11ea-92aa-fff3e6d9b463.png)

**Comment by NightcoreIsla** [comment]
for this problem,
i only using MapManager's server script part for keep listing
it will do anything bad for es_extended?

**Comment by hichay** [comment]
Same problem. it's ok when you keep the Mapmanager

**Comment by goxint** [comment]
Removing them both does the job perfectly.

**Comment by NightcoreIsla** [comment]
> 刪除它們都可以很好地完成工作。
so, if disabled it (don't start resource)
will hide in server list,
then if delete it
will show normaly?

**Comment by NightcoreIsla** [comment]
> Same problem. it's ok when you keep the Mapmanager

but the es_extended commit said
should stop/remove mapmanager and spawnmanager
so i think that is bug, maybe need report

**Comment by Tim885885** [comment]
I have had this problem but solved it
Your server will still appear on the list
But it will appear as an invalid server
It may be that FiveM thinks it is wrong to not enable those two scripts

**Comment by NightcoreIsla** [comment]
> 我遇到了這個問題，但是已經解決了。
> 您的服務器仍將出現在列表中，
> 但是它將顯示為無效服務器
> 。FiveM認為不啟用這兩個腳本是錯誤的

so FiveM just count the name of resource active or not?
didn't care about inside script?

**Comment by NightcoreIsla** [comment]
> I have had this problem but solved it
> Your server will still appear on the list
> But it will appear as an invalid server
> It may be that FiveM thinks it is wrong to not enable those two scripts

OMG! u are right
i can start a empty mapmanager and spawnmanager
then my server listing normally

**Comment by NightcoreIsla** [comment]
Find Problem on FiveM Server List System
it need have resource(emptyable) name : mapmanager and spawnmanager
