### ISSUE TITLE
Steam ID rather than Rockstar ID

### ISSUE THREAD

**Issue by Bluxrs** [ESX-Org/es_extended#690]
Why is this using a rockstar ID rather than steam and how can this be changed? Personally this has created more issues from moving away from essential mode to this new standalone version. Most scripts work with steam ID.. Either this is an error or a improvement as I cannot use other scripts now due to this as it looks for steam identifiers..

**Comment by hichay** [comment]
on Server/main.lua find function onPlayerJoined(playerId)
change `if string.match(v, 'license:') then
			identifier = string.sub(v, 9)
			break
		end`
to `if string.match(v, 'steam:') then
			identifier = v
			break
		end`
and find the AddEventHandler('playerConnecting', function(name, setCallback, deferrals)
do the same change the license to steam and indetifier = v

**Comment by Bluxrs** [comment]
I'm also not getting the create character registration and skin customisation.. I have everything that should be needed but it just creates an entry and does not allow me to enter a name dob etc.

**Comment by JGabTolentino** [comment]
change kashacters identifier on server.lua to find steam instead of rockstar identifier or just stick with the rockstar identifier version

**Comment by annocuoi** [comment]
Tôi không tìm ra if string.match(v, 'license:') then identifier = string.sub(v, 9) break end đối với esx_legacy

**Comment by LeguDe** [comment]
Goto server\functions.lua and seardch for ESX.GetIdentifier

Change:
		if string.match(v, 'license:') then
			local identifier = string.gsub(v, 'license:', '')

to 
		if string.match(v, 'steam:') then
			local identifier = v

Isn't working with Multichar. Check server\classes\player.lua

	if Config.Multichar then self.license = 'license'..string.sub(identifier, 6) else self.license = 'license:'..identifier end

This may be the reason why they switched from steam ID to own IDs. Wished they made a Config entry for this
