### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by TobiClaraPA** [ESX-Org/es_extended#694]
![sit](https://user-images.githubusercontent.com/55306209/79810900-9f339d80-834a-11ea-9db3-d6b37d4657b0.png)

**Comment by TobiClaraPA** [comment]
¿?

**Comment by TobiClaraPA** [comment]
I love that you always do the same, you close problems without solving them

**Comment by HumanTree92** [comment]
Well he is tired of people opening issues that r super simple to fix & he is tired of answering the same problems/questions over & over.

**Comment by TobiClaraPA** [comment]
It is easy to solve for him or for you, but those who do not know as much about the subject do not know how to solve it, so if it is so easy to solve, tell us the solution and that's it

**Comment by HumanTree92** [comment]
Alright fair enough. Here is how to solve your problems. Go to Google and type How to Lua.
