### ISSUE TITLE
ServerCallback - serializable and non-serializable object error

### ISSUE THREAD

**Issue by ZockerBoysHD** [ESX-Org/es_extended#698]
I occasionally get this error spammed in console after a servercallback got triggered
https://screens.egopvp.com/files/2020/04/21/chrome_xeU7YSJdjt.png

the last time it happened was when the esx_doorlock:getdoorInfo event got triggered. 
This is my current doorlock Callback code:
https://screens.egopvp.com/files/2020/04/21/notepad_ivpswTXf8Y.png

**Comment by heyheyitsmeman** [comment]
Update your es_extended.

**Comment by ZockerBoysHD** [comment]
https://screens.egopvp.com/files/2020/04/22/chrome_n3md3RltD3.png stimm get this error. even with newest esx from yesterday evening about 19:00
