### ISSUE TITLE
problem with throw

### ISSUE THREAD

**Issue by hamood192244** [ESX-Org/es_extended#706]
in the new update when i throw money its OK its come with bag and i can press E to collect it
but when i throw weapon its hide and i can see it and removed form my inventory.

when i install the old version form es_extended to see what the problem and replace it with the new version
i can see the weapon and i can collect it by press E

the problem from the new update can you see the problem Please <3

**Comment by hamood192244** [comment]
> but when i throw weapon its hide and i can't see it and removed form my inventory.*******

**Comment by heyheyitsmeman** [comment]
Same here, in F8 something like invalid type if data pops-up when you throw it.

**Comment by MatteoLinzi** [comment]
![issue](https://user-images.githubusercontent.com/54669258/80165250-62320a00-85db-11ea-9279-811a4c9bab84.PNG)
Here is a screenshot. So, drop items works, money, water, food etc.
But, dro pweapon doesn't work, weapon is removed from inventory, but not spawned as bag, so can't pick it up.

**Comment by hamood192244** [comment]
and there another problem with weapons in the last update
it's don't save the ammo in the loadout in data base

i spent 14 hour to see what the problem i thought the problem from esx_weaponshop or esx_clip
but when i back the es_extended last 2 month version it's work and saved the ammo when i log out
and saved in loadout in data base.
