### ISSUE TITLE
Default Spawn

### ISSUE THREAD

**Issue by TehZombiJesus** [ESX-Org/es_extended#708]
Hi,

Since we have to remove map-hipster and map-skater, I have no clue how to change the default spawn.

Currently, we default spawn is a the job center here;
**x = -269.4, y = -955.3, z = 31.2, heading = 205.8**

and I'd like it to be at the airport;
**x = -1037.84, y = -2737.97, z = 20.17, heading = 324.83**

I believe it is es_extended that handles it considering it is the only resource running aside from chat, sessionmanager, hardcap and mysql-async.

I have tried to search throught the server files and even went just to be sure in the clients files and I didn't find anything.

**Comment by HumanTree92** [comment]
You got to edit https://github.com/ESX-Org/es_extended/blob/master/server/main.lua#L230 and https://github.com/ESX-Org/es_extended/blob/master/es_extended.sql#L12
