### ISSUE TITLE
ESX silently servers blacklisted from fivem server list

### ISSUE THREAD

**Issue by ZockerBoysHD** [ESX-Org/es_extended#711]
Now i updated my ESx verison and now my server wont list in fivem listing. renaming ESX to something else makes it appear again.

As far as i know its blacklisted for iceline hosting cause its not authorized fivem server provider.

**Comment by ZockerBoysHD** [comment]
Updating FxServer or rEnaming eSX seems to be working.

**Comment by ZockerBoysHD** [comment]
haha fun didnt last long. esx is still blacklisted.

**Comment by hichay** [comment]
Run the Mapmanager and the spawnmanager. put it empty

**Comment by ZockerBoysHD** [comment]
> Run the Mapmanager and the spawnmanager. put it empty

then esx disables them tho

**Comment by ZockerBoysHD** [comment]
https://screens.egopvp.com/files/2020/04/24/chrome_TvO8VFIdFW.png and i get these type of errors all over the place.

**Comment by ZockerBoysHD** [comment]
its not resolved and u close it. why?

**Comment by ZockerBoysHD** [comment]
and its clear that iceline hosting is not a valid fivem hosting service and u advertise for them.  so it got blocked.
