### ISSUE TITLE
last location save and weapon ammo

### ISSUE THREAD

**Issue by hamood192244** [ESX-Org/es_extended#715]
In these last update An hour before this ticket 

The server doesn't save last position when i leave the server, and when i login again it spawn me randomly.

And the second problem the weapon don't save the ammo wen i charge it by clip  from inventory

Thanks for your hard work and wish you happy day <3

**Comment by hichay** [comment]
First. you need to check your load location. did you disable the spawnmanager and mapmanager yet?
Second. clip from inventory is a item. it it's a client code to add ammo to ped. not to player. new ESX not save anything add to ped anymore. so take a look at your clip code first

**Comment by hamood192244** [comment]
thank you <3

@HumanTree92 
what about clip in esx_extraitems 
weapon box
and weapon clip
