### ISSUE TITLE
Script Error on Player Joined

### ISSUE THREAD

**Issue by EmpireAssassin** [ESX-Org/es_extended#721]
Everytime a player joins this error is thrown:

`SCRIPT ERROR in call ref: TypeError: Cannot read property 'execute' of null

> callback (@mysql-async/mysql-async.js:5141)
> fetchScalar (@mysql-async/lib/MySQL.lua:161)
> onPlayerJoined (@es_extended/server/main.lua:17)
> handler (@es_extended/server/main.lua:3)`

![Console Error](https://i.ibb.co/sHhVdFN/Untitled.png)

This server is a completely clean install. I have followed your instructions to a T. Like before, no resources are present excluding the ones told to install in your README.md. Here is the versions of the resources installed:

[ESX Version](https://github.com/ESX-Org/es_extended/releases/latest)
[ESX Menu Version](https://github.com/ESX-Org/esx_menu_default/releases/latest)
[ESX List Version](https://github.com/ESX-Org/esx_menu_list/releases/latest)
[ESX Dialog Version](https://github.com/ESX-Org/esx_menu_dialog/releases/latest)

Any help would be welcome, thank you for your time.

**Comment by FoxXxHater** [comment]
![image](https://user-images.githubusercontent.com/54017453/81486303-1c6c7700-9254-11ea-8465-bf72650aaf8f.png)
 I'am to...

**Comment by EmpireAssassin** [comment]
That isn't the same error as myself. Also you do not have a clean install. Mine is 100% clean with nothing else added to cause conflicts. Same for the database, it is new.

**Comment by EmpireAssassin** [comment]
Thanks to Hellraiser, we manged to change the error slightly. Here is that new printout:

![Console Error](https://i.ibb.co/QpwB8Nk/Untitled.png)

**Comment by FoxXxHater** [comment]
before i have updated my es_extended and essentionalmode my install was clean and ready, but after the Update this error is joined

**Comment by EmpireAssassin** [comment]
You are misunderstanding what a clean install is. I can physically see other resources in your errors. You do not have a clean install. You have other resources besides what is required to run just the base of ESX.

In addition your errors are due to your database. Mine is a physical error in the script not an issue calling from or writing to the database.

To put it blunt, not only are our servers not the same, our issues are not either. It might be best to gather your details and versions and make a ticket of your own.

**Comment by pl77** [comment]
@FoxXxHater your error looks like you haven't imports all the SQL files into the database so it's missing various columns that its looking for. I'd suggestion going back to each individual 

@EmpireAssassin I'm having the exact same issue as you.  I've even dumped a few print statements in my main.lua folder to make sure it's sending the right data to mysql and getting nothing. I've wiped and reinstalled both mysql and fivem/es_extended more times than I can count and I can't figure out the problem.  I can't imagine we are the only two having this issue.

**Comment by joopjuh** [comment]
I have the exact same issue.
My install is clean as i've tried to get it working for the 3rd time.
I'm running this from an Unraid Docker and i trashed bot the docker and the data folder.
Git cloning the folders directly onto my machine and adding them to the FiveM server the correct way.
Removed the database and imported the es_extended sql file to create a new one.
Updated the server config file accordingly.
See the output of the FiveM server below.

```
`Creating script environments for sessionmanager
Started resource sessionmanager
Creating script environments for webadmin
Instantiated instance of script FxWebAdmin.BaseServer.
Instantiated instance of script FxWebAdmin.HttpServer+HttpServerScript.
Started resource webadmin
Creating script environments for monitor
Started resource monitor
Creating script environments for mapmanager
Started resource mapmanager
Creating script environments for chat
Started resource chat
Started resource spawnmanager
Started gametype Freeroam
Started resource basic-gamemode
Started resource fivem
Creating script environments for hardcap
Started resource hardcap
Creating script environments for rconlog
Started resource rconlog
Started resource scoreboard
Creating script environments for playernames
Started resource playernames
Creating script environments for mysql-async
Started resource mysql-async
Creating script environments for async
Started resource async
Creating script environments for es_extended
Started resource es_extended
Started resource esx_menu_default
Started resource esx_menu_list
Started resource esx_menu_dialog
Argument count mismatch (passed 2, wanted 1)
Authenticating server license key...
Server license key authentication succeeded. Welcome!
Started map fivem-map-skater
Started resource fivem-map-skater
Authenticating with Nucleus...
server thread hitch warning: timer interval of 962 milliseconds
        fff                          
  cccc ff   xx  xx     rr rr    eee  
cc     ffff   xx       rrr  r ee   e 
cc     ff     xx   ... rr     eeeee  
 ccccc ff   xx  xx ... rr      eeeee 
                                     
Authenticated with cfx.re Nucleus: blablabla
server thread hitch warning: timer interval of 206 milliseconds
A client has tried to authenticate using Steam, but `steam_webApiKey` is unset. Please set steam_webApiKey to a Steam Web API key as registered on Valve's https://steamcommunity.com/dev/apikey web page. Steam identifier information will be unavailable otherwise.
To suppress this message, `set steam_webApiKey "none"`.
Connecting: blablabla
SCRIPT ERROR in call ref: TypeError: Cannot read property 'execute' of null

> callback (@mysql-async/mysql-async.js:5144)
> fetchScalar (@mysql-async/lib/MySQL.lua:161)
> onPlayerJoined (@es_extended/server/main.lua:27)
> handler (@es_extended/server/main.lua:9)`
```

**Comment by joopjuh** [comment]
Why closed the issue?

**Comment by pl77** [comment]
If you have closed this issue could you at least link to the related issue or pull request so we can fix it or comment there and monitor for progress?

**Comment by indilo53** [comment]
See #announcements on discord

**Comment by EmpireAssassin** [comment]
There is nothing in the announcements. So why close it? Because you can't find a solution? Clearly multiple people are having this issue.

**Comment by joopjuh** [comment]
It is completely empty. The guides are totally worthless as this is all over the place.

There are no clear instructions and even the ones on the forum don't work as they are windows only.
Just provide the information as you are closing a lot of issues with no answers.

The lack of support from ESX is really bad.

**Comment by EmpireAssassin** [comment]
> It is completely empty. The guides are totally worthless as this is all over the place.
> 
> There are no clear instructions and even the ones on the forum don't work as they are windows only.
> Just provide the information as you are closing a lot of issues with no answers.

Yeah I would have liked that too. It's probably best we just start our own framework. Take a bit longer to get the server started, but at least it will be a strong base framework with reliable support. I recommend you doing the same :)

> The lack of support from ESX is really bad.

Welcome to ESX Org.

**Comment by pl77** [comment]
> It's probably best we just start our own framework

Hahaha, you funny guy. I can't even figure out how to get this framework running, let alone design a new one.

**Comment by indilo53** [comment]
Screw you guys, we are working hard on fixing ESX for REAL you are there just to complain, so yeah better leave and do your own shit.

If you are not interested in the hard work we are doing right now there is **Fixed ESX fork** named ExM doing exactly what you need
