### ISSUE TITLE
Spawn as ped

### ISSUE THREAD

**Issue by Timmyopp** [ESX-Org/es_extended#728]
So everytime i connect to my localhost I spawn as random ped.
Tried clearing cache and this issue also been when I was starting a fresh esx build.
If anyone could help Timmy#8488
also im getting in console onesync, Dropping duplicate player for netID 1 (slotID 128)

**Comment by elCohete** [comment]
Me too! How did you fix that?

**Comment by Paulevas** [comment]
Do somebody have answer how fix it?
