### ISSUE TITLE
My identity registraion doesnt show up when in server first time!

### ISSUE THREAD

**Issue by tuuretonttu** [ESX-Org/es_extended#738]
When i wipe my users database from saved users. And i have many times reinstalled esx_identy. And Changed from sql "essentialmode" to es_extended. It doesnt show any error code. My TXadmin detects that resource is started tms.... But still it says "command register is invalid command" and i cant register when i  go first time to server. I have all things that need dependcies and tried from differernt sections of server.cfg   Could anyone help?

**Comment by itsNSO** [comment]
im having the same issue
