### ISSUE TITLE
[BUG] Lag when dropping items - duplication on item remove

### ISSUE THREAD

**Issue by Fernand3z** [ESX-Org/es_extended#753]
Hello dear fivem community, 
on my project i have some little struggle, because everytime if a player drops a item
the item drops everywhere on the map. 

The item will not only fall on the person who dropped it, but on everyone and
can pick it up. (duplication for all players)
I haven't changed anything on esx_extended or something. (running old version with limit)
A person from the community had the same problem with laggs and more but i didn't understand the correct answer and hope for a solution  - thanks.

**Comment by Rootqt** [comment]
Hello there, have You found a soultion to this ?

Regards

**Comment by iSentrie** [comment]
Never had this.

**Comment by Rootqt** [comment]
Still struggling with this... DAmn

**Comment by LPmitWither** [comment]
I have exactly the same error with my server.

Does anyone have a fix for that?
