### ISSUE TITLE
1 SQL error from master branch

### ISSUE THREAD

**Issue by PaulyJ1** [ESX-Org/es_extended#755]
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT accounts, job, job_grade, `group`, loadout, position, inventory FROM users WHERE identifier = 'xxxxxxxx'": ER_BAD_FIELD_ERROR: Unknown column 'accounts' in 'field list'

**Comment by indilo53** [comment]
You are missing **accounts** column in **users** table

**Comment by PaulyJ1** [comment]
> You are missing **accounts** column in **users** table

I have accounts in users table
