### ISSUE TITLE
Server not on the list

### ISSUE THREAD

**Issue by DevDokus** [ESX-Org/es_extended#756]
ESX framework is asking to remove certain folders from the game,
but if you do so you will not show up on the server list anymore. 
And thats a big issue.

**Comment by indilo53** [comment]
This insanity is fixed in develop and master

**Comment by DevDokus** [comment]
I tried the latest develop/master branch of ESX but i am not sure what is fixed then ?
One i replaced the old ESX version with the new one, the server simply refuses to appear on the server list. If i revert ESX back to a older version, we appear on the server list in matter of minutes. So i am not sure what is fixed, but all our servers are negative on the server list with the newest version of ESX.
