### ISSUE TITLE
Access denied command

### ISSUE THREAD

**Issue by Destructor** [ESX-Org/es_extended#765]
I do not have access to admin commands from the chat. on the other hand by f5 thanks to the menu staff.
in the database I am superadmin.

Regards,

je n'ais pas acccès aux commandes admin depuis le tchat. par contre par f5 grace au personnel menu.
dans la base de donnés je suis superadmin.

cordialement,

**Comment by indilo53** [comment]
try putting yourself as **admin**

**Comment by Destructor** [comment]
F5 is krz_personalmenu i don't have option for add admin :'(

**Comment by indilo53** [comment]
I mean in database

**Comment by Destructor** [comment]
Tks it's works ^^
