### ISSUE TITLE
Does not read position

### ISSUE THREAD

**Issue by leal994** [ESX-Org/es_extended#773]
I've created a server with this version and it doesn't charge me the position. I have a position in the database "position (255)". But I get that it saves it, but it doesn't load the position.
Help please.

**Comment by daZepelin** [comment]
Exactly the same for me

**Comment by mojtaba031** [comment]
Exactly the same for me

**Comment by zzmarzomber** [comment]
I have the same problem, the same thing happens to me

**Comment by zzmarzomber** [comment]
I need help please

**Comment by FuTTiiZ** [comment]
Same.

**Comment by mojtaba031** [comment]
I don't have any problems when I log out of the server normally. But when I crash or the server suddenly shuts down or the server's admins kick everyone, that's a problem.
