### ISSUE TITLE
Problem with inventory

### ISSUE THREAD

**Issue by hhyllis** [ESX-Org/es_extended#778]
How to I get rid of weight limit showing in inventory?
![image](https://user-images.githubusercontent.com/65471636/82712718-5cd6e680-9c91-11ea-9cfe-ec65348e0544.png)

**Comment by PaulyJ1** [comment]
Go to es_extended/locales/fi.lua go to line 3 and replace ['inventory'] = 'inventory %s / %s' with this ['inventory'] = 'Reppu'
