### ISSUE TITLE
Issue with ETIMEDOUT on localhost

### ISSUE THREAD

**Issue by christerjohansson** [ESX-Org/es_extended#780]
Upon starting my server, I always get this error about DB or script timing out.
I am running Windows 10, with fxserver ver. 2381, with MariaDB (latest) on a local Docker container. I am using es_extended: dev branch. I have latest versions of ESX (I think).

![esx_extended_error](https://user-images.githubusercontent.com/3787897/82726778-a4d42880-9ce6-11ea-95aa-5c1e9af5afa3.png)

**Comment by christerjohansson** [comment]
When restarting server, problem goes away...not sure why this "hickup" occurs on first start only.

**Comment by christerjohansson** [comment]
Not interested in fixing issues? Why did you close it?

**Comment by indilo53** [comment]
That 'issue' is explained in discord announcemenst, also github issues are now resverved for developpment talk. Last thing, in announcements we also explained we consider esx 1.x deprecated / wontfix. So either you can wait for new awesome esx we are working on in develop or can't / don't want then you should consider going to ExM
