### ISSUE TITLE
Server callback "esx_scoreboard:getConnectedPlayers" does not exist. 

### ISSUE THREAD

**Issue by SAYREXx** [ESX-Org/es_extended#782]
Error: Server callback "esx_scoreboard:getConnectedPlayers" does not exist. Make sure that the server sided file really is loading, an error in that file might cause it to not load.
```
Citizen.CreateThread(function()
	while ESX == nil do
		TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
		Citizen.Wait(0)
	end

	Citizen.Wait(2000)
	ESX.TriggerServerCallback('esx_scoreboard:getConnectedPlayers', function(connectedPlayers)
		UpdatePlayerTable(connectedPlayers)
	end)
end)
```

**Comment by XvenDeR** [comment]
How is it related to es_extended?

**Comment by SAYREXx** [comment]
> How is it related to es_extended?

This error appears after es_extended update

**Comment by indilo53** [comment]
Wrong usage of discord issues, see #announcements on discord

**Comment by SAYREXx** [comment]
> Wrong usage of github issues, see #announcements on discord

May I get your discord?

**Comment by indilo53** [comment]
Sure, its in the README https://github.com/ESX-Org/es_extended/blob/master/README.md
