### ISSUE TITLE
Problem with OneSync

### ISSUE THREAD

**Issue by xYouLL** [ESX-Org/es_extended#785]
Hello, I have a OneSync Platinum server running with the last version of ESX, sometimes when a player try to join his player doesn't load, it's like it can't get the identifier from the database and for that I have a lot of spam on the console that can't get the xPlayer.
What should I do? Please I tried a lot of things without success, any advices?
Thanks

**Comment by Richards0nd** [comment]
We need more details ...
You showed us no error, no information ... nothing.

This is probably a mistake in your configuration, because the latest version of ESX is not having any problems.

**Comment by xYouLL** [comment]
@Richards0nd I have a modified version of esx_kashacters and that's what I modified in es_extended:
```
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)

		-- if NetworkIsPlayerActive(PlayerId()) then
		-- 	TriggerServerEvent('esx:onPlayerJoined')
		-- 	break
		-- end
		-- if NetworkIsSessionStarted() then
		-- 	TriggerServerEvent('esx:onPlayerJoined')
		-- 	return
		-- end
	end
end)
```
And this in kashacters:
```
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)
        -- if NetworkIsSessionStarted() then
        --     TriggerServerEvent('esx:onPlayerJoined')
        --     Citizen.Wait(500)
        --    -- TriggerServerEvent("kashactersS:SetupCharacters")
		-- 	TriggerEvent("kashactersC:WelcomePage")
        --     TriggerEvent("kashactersC:SetupCharacters")
        --     TriggerScreenblurFadeIn(0)
        --     return -- break the loop
        -- end
        if NetworkIsPlayerActive(PlayerId()) then 
            TriggerServerEvent('esx:onPlayerJoined')
            Citizen.Wait(500)
            TriggerEvent("kashactersC:WelcomePage")
            TriggerEvent("kashactersC:SetupCharacters")
            TriggerScreenblurFadeIn(0)
            break
        end
    end
end)
```
I don't get specified errors, I only get a spam of all resources that do cycles to get the xPlayer.

**Comment by EmpireAssassin** [comment]
> the latest version of ESX is not having any problems.

ESX definitely has problems. They just get closed and the people reporting it get told to screw off after being lied to.

**Comment by indilo53** [comment]
We accept issues only for develop and whith code pointed out and hints to solve them.

Github is for developpment,, not asking random help.

If you want to have  support for 1.x you can go here => https://github.com/extendedmode/extendedmode They're will be happy to help you or improve ExM to handle your issue

Already announced all of this in our discord which is specified in readme of master branch
