### ISSUE TITLE
es_extended has problems with esplugin_mysql

### ISSUE THREAD

**Issue by R3ALF4KT** [ESX-Org/es_extended#789]
Both sql's want to create table "users", this error shows up if i use es_extended after esplugin_mysql

`CREATE TABLE `users` (
	`identifier` VARCHAR(40) NOT NULL,
	`accounts` LONGTEXT NULL DEFAULT NULL,
	`group` VARCHAR(50) NULL DEFAULT 'user',
	`inventory` LONGTEXT NULL DEFAULT NULL,
	`job` VARCHAR(20) NULL DEFAULT 'unemployed',
	`job_grade` INT NULL DEFAULT 0,
	`loadout` LONGTEXT NULL DEFAULT NULL,
	`position` VARCHAR(255) NULL DEFAULT '{"x":-269.4,"y":-955.3,"z":31.2,"heading":205.8}',

	PRIMARY KEY (`identifier`)
)
#1050 - Table 'users' already exists`

Both SQL's:

es_extended
![image](https://user-images.githubusercontent.com/59320846/82929528-1b418680-9f84-11ea-9fc6-246b1a8c53f8.png)

And esplugin_mysql:
![image](https://user-images.githubusercontent.com/59320846/82929715-6d82a780-9f84-11ea-8a7c-07f5a48fc3ce.png)

**Comment by indilo53** [comment]
They are incompatible since quite some time and esx 1.x is considered deprecated

**Comment by R3ALF4KT** [comment]
Alright thanks anyways!
