### ISSUE TITLE
some bugs encountered

### ISSUE THREAD

**Issue by JYM34** [ESX-Org/es_extended#792]
hello,
1 - there is a problem with the opening inventory menu, it is not displayed. Here is the error displayed : 
[Show screenshot](https://prnt.sc/sos0ke).
2 - If you log out and then log back in, the display (money, business) is no longer displayed. [Show screenshot](https://prnt.sc/sos45k)
3 - After restarting the server, it suggests that we recreate our identity.
4 - Upon arrival on the server, we cannot modify the skin

Very good job, thank you!

**Comment by wilfryd95** [comment]
Salut, j'ai besoin d'aide, es que tu peux m'aider stp?

**Comment by JYM34** [comment]
Ce n'est pas un forum d'aide ici,mais dit toujours

**Comment by wilfryd95** [comment]
Désoler ^^, bah enfaite, impossible de me connecter, je reste dans le loadingscreen

**Comment by wilfryd95** [comment]
Es que tu as discord ?

**Comment by JYM34** [comment]
j'ai discord oui

**Comment by Leon485** [comment]
adding on to what @JYM34 put, pretty much all of the esx addons dont work with the script at the moment i mad e afresh new install of all the latest esx scripts and the only ones which didnt cause errors were:
esx_menu_default
esx_menu_list_dialog
esx_voice
esx_addonaccount
instance
esx_addoninventory
esx_datastore

If there is one thing wrong with your server e.g. you put start es_extended instead of ensure es_extended the wholeserver will not start aswell or leave you on the loading screen (which looks really good, however i want to play the game XD).

I hope this helps out and i also encountered the same errors as stated above.

**Comment by wilfryd95** [comment]
Je peux avoir ton discord stp?

**Comment by JYM34** [comment]
non je ne donne pas mon discord

**Comment by wilfryd95** [comment]
D'accord, du coup es que tu sais pourquoi je reste bloquer sur le loadingscreen du coup stp?

**Comment by JYM34** [comment]
Ben déjà as tu téléchargé la dernière master version?
Car le probleme du loading screen, n'y est plus (enfin pour moi) depuis la derniere maj

**Comment by wilfryd95** [comment]
Oui j'ai bien télécharger la dernière maj pourtant

**Comment by JYM34** [comment]
et as tu bien suivi les conseils d'installation du fichier readme?
Si oui, je te conseille de supprimer tous tes messages inutile ici, est de signaler ton problème ici afin que les devs regarde ça.

**Comment by deviljin112** [comment]
if you need help => [FORUM](https://forum.esx-framework.org)

**Comment by indilo53** [comment]
what version

**Comment by wilfryd95** [comment]
indilo je peux te parler discord stp?

**Comment by indilo53** [comment]
oui si c'est pas pour du dépannage

**Comment by wilfryd95** [comment]
Oui c'est pour te demander un truc pas de dépannage, 😈†𝓨𝓪𝔃𝓱𝓶𝓸𝓰†😈#1445

**Comment by JYM34** [comment]
> what version

Version Master et Develop, j'ai les même bugs signalé plus haut

**Comment by indilo53** [comment]
C'est du taff tout frais on travaille activement surveillez tout les jours :)

It is fresh work, we work hard on it, watch every day :)

**Comment by JYM34** [comment]
Oui je sais bien, c'est pour cela que je signale les bugs, afin que tu puisses corriger et l’amélioré. en tout cas j'aime bien cette nouvelle version. Bon boulot.
