### ISSUE TITLE
Never load in

### ISSUE THREAD

**Issue by Leon485** [ESX-Org/es_extended#794]
It says im in game and i can hear the noises however it stays on the loading screen:

![image](https://user-images.githubusercontent.com/63073120/83035492-71b8ce80-a031-11ea-9ece-c9c6d621a88e.png)

**Comment by xZToxicZx** [comment]
@Leon485 How did you fix this?

**Comment by Leon485** [comment]
Changed start to ensure

**Comment by xZToxicZx** [comment]
I did that aswell but still no luck. looking at console seems like the client cant load the modules so I'll make a new issue

**Comment by Leon485** [comment]
tbh dont use it yet as no other scripts like esx policejob work on it etc give it a couple days and it will probably be more functional

**Comment by shortybsd** [comment]
Simply disable their broken loadscreen. **Edit fxmanifest.lua**
enable_loadscreen = false
Problem solved. I'll go through the html to see the issue and push a PR request.

**Comment by xZToxicZx** [comment]
@shortybsd don't think its a loading screen issue more the fact that the thing that is calling for the loading screen to be closed isn't being called (most likely because it's being held up due to errors)

**Comment by shortybsd** [comment]
@xZToxicZx  Yeah, after looking at the code I see what you mean. I'll throw some debugging in to see why it is not getting triggered. I have no errors on clientside nor serverside.
