### ISSUE TITLE
Issue installing ESX 

### ISSUE THREAD

**Issue by Matt4499** [ESX-Org/es_extended#80]
I have installed ESX following these directions: https://esx-org.github.io/es_extended/overview/

When I log into my server money and job does not show up in the top right corner and console says this:

>Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:351: server/main.lua:237: attempt to index a nil value (global 'Async')
stack traceback:
        server/main.lua:237: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
Error running system event handling function for resource essentialmode: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in local 'cb'
        server/player/login.lua:145: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:335: in function <citizen:/scripting/lua/scheduler.lua:322>

**Comment by Vanheden** [comment]
attempt to index a nil value (global 'Async'). There's your error... Install MySQL Async.

**Comment by Matt4499** [comment]
It is installed with the name "mysql-async" and my load order is this: 

> start mysql-async
start essentialmode
start esplugin_mysql
start es_admin2
start es_extended

start esx_menu_default
start esx_menu_list
start esx_menu_dialog

**Comment by Matt4499** [comment]
I was missing the 'async' one, not mysql async but just 'async' smh close this
