### ISSUE TITLE
How can I fix about the "Error loading script server/main.lua".

### ISSUE THREAD

**Issue by amo0725** [ESX-Org/es_extended#801]
D:\FXServer\server-data>cd /d D:\FXServer\server-data

D:\FXServer\server-data>D:\FXServer\server\FXServer.exe +exec server.cfg
Creating script environments for _cfx_internal
Found new resource monitor in D:\FXServer\server\citizen/system_resources//monitor
Found new resource webadmin in D:\FXServer\server\citizen/system_resources//webadmin
Found new resource async in D:/FXServer\server-data/resources//[essential]/async
Found new resource cron in D:/FXServer\server-data/resources//[essential]/cron
Found new resource es_extended in D:/FXServer\server-data/resources//[essential]/es_extended
Found new resource es_extended000 in D:/FXServer\server-data/resources//[essential]/es_extended000
Found new resource mysql-async in D:/FXServer\server-data/resources//[essential]/mysql-async
Found new resource esx_addonaccount in D:/FXServer\server-data/resources//[esx]/esx_addonaccount
Found new resource esx_addoninventory in D:/FXServer\server-data/resources//[esx]/esx_addoninventory
Found new resource esx_basicneeds in D:/FXServer\server-data/resources//[esx]/esx_basicneeds
Found new resource esx_billing in D:/FXServer\server-data/resources//[esx]/esx_billing
Found new resource esx_datastore in D:/FXServer\server-data/resources//[esx]/esx_datastore
Found new resource esx_dmvschool in D:/FXServer\server-data/resources//[esx]/esx_dmvschool
Found new resource esx_identity in D:/FXServer\server-data/resources//[esx]/esx_identity
Found new resource esx_joblisting in D:/FXServer\server-data/resources//[esx]/esx_joblisting
Found new resource esx_jobs in D:/FXServer\server-data/resources//[esx]/esx_jobs
Found new resource esx_license in D:/FXServer\server-data/resources//[esx]/esx_license
Found new resource esx_service in D:/FXServer\server-data/resources//[esx]/esx_service
Found new resource esx_skin in D:/FXServer\server-data/resources//[esx]/esx_skin
Found new resource esx_society in D:/FXServer\server-data/resources//[esx]/esx_society
Found new resource esx_status in D:/FXServer\server-data/resources//[esx]/esx_status
Found new resource esx_vehicleshop in D:/FXServer\server-data/resources//[esx]/esx_vehicleshop
Found new resource gcphone in D:/FXServer\server-data/resources//[esx]/gcphone
Found new resource new_banking in D:/FXServer\server-data/resources//[esx]/new_banking
Found new resource skinchanger in D:/FXServer\server-data/resources//[esx]/skinchanger
Found new resource basic-gamemode in D:/FXServer\server-data/resources//[gamemodes]/basic-gamemode
Found new resource chat in D:/FXServer\server-data/resources//[gameplay]/chat
Found new resource chat-theme-gtao in D:/FXServer\server-data/resources//[gameplay]/chat-theme-gtao
Found new resource playernames in D:/FXServer\server-data/resources//[gameplay]/playernames
Found new resource mapmanager in D:/FXServer\server-data/resources//[managers]/mapmanager
Found new resource spawnmanager in D:/FXServer\server-data/resources//[managers]/spawnmanager
Found new resource baseevents in D:/FXServer\server-data/resources//[system]/baseevents
Found new resource hardcap in D:/FXServer\server-data/resources//[system]/hardcap
Found new resource rconlog in D:/FXServer\server-data/resources//[system]/rconlog
Found new resource runcode in D:/FXServer\server-data/resources//[system]/runcode
Found new resource scoreboard in D:/FXServer\server-data/resources//[system]/scoreboard
Found new resource sessionmanager in D:/FXServer\server-data/resources//[system]/sessionmanager
Found new resource sessionmanager-rdr3 in D:/FXServer\server-data/resources//[system]/sessionmanager-rdr3
Found new resource example-loadscreen in D:/FXServer\server-data/resources//[test]/example-loadscreen
Found new resource fivem in D:/FXServer\server-data/resources//[test]/fivem
Found new resource esx_ambulancejob in D:/FXServer\server-data/resources//[esx]/[jobs]/esx_ambulancejob
Found new resource esx_mechanicjob in D:/FXServer\server-data/resources//[esx]/[jobs]/esx_mechanicjob
Found new resource esx_policejob in D:/FXServer\server-data/resources//[esx]/[jobs]/esx_policejob
Found new resource fivem-map-hipster in D:/FXServer\server-data/resources//[gamemodes]/[maps]/fivem-map-hipster
Found new resource fivem-map-skater in D:/FXServer\server-data/resources//[gamemodes]/[maps]/fivem-map-skater
Found new resource redm-map-one in D:/FXServer\server-data/resources//[gamemodes]/[maps]/redm-map-one
Found new resource webpack in D:/FXServer\server-data/resources//[system]/[builders]/webpack
Found new resource yarn in D:/FXServer\server-data/resources//[system]/[builders]/yarn
Creating script environments for sessionmanager
Started resource sessionmanager
Creating script environments for webadmin
Instantiated instance of script FxWebAdmin.BaseServer.
Instantiated instance of script FxWebAdmin.HttpServer+HttpServerScript.
Started resource webadmin
Creating script environments for monitor
Started resource monitor
Stopping resource webadmin
Creating script environments for mapmanager
Started resource mapmanager
Creating script environments for chat
Started resource chat
Started resource spawnmanager
Creating script environments for hardcap
Started resource hardcap
Creating script environments for rconlog
Started resource rconlog
Creating script environments for baseevents
Started resource baseevents
Creating script environments for async
Started resource async
Creating script environments for mysql-async
Started resource mysql-async
Creating script environments for cron
Started resource cron
Started gametype Freeroam
Started resource basic-gamemode
Started resource fivem
Started resource scoreboard
Started resource skinchanger
Creating script environments for es_extended
[esx] [@events] load
[esx] [@class] load
[esx] [@account] load
[esx] [@table] load
[esx] [@string] load
[esx] [@async] load
[esx] [@command] load
[esx] [@datastore] load
[esx] [@db] load
[esx] [@game.hud] load
[esx] [@identity] load
[esx] [@player] load
[esx] [@input] load
[esx] [@interact] load
[esx] [@inventory] load
[esx] [@math] load
[esx] [@migrate] load
[esx] [@utils] load
[esx] [accessories] load
[esx] [skin] load
[esx] [society] load
[esx] [voice] load
Started resource es_extended
Creating script environments for esx_addonaccount
Started resource esx_addonaccount
Creating script environments for esx_addoninventory
Started resource esx_addoninventory
Creating script environments for esx_skin
Error loading script server/main.lua in resource esx_skin: @esx_skin/server/main.lua:38: attempt to index a nil value (global 'ESX')
stack traceback:
        @esx_skin/server/main.lua:38: in main chunk
Failed to load script server/main.lua.
Started resource esx_skin
Authenticating server license key...
Server license key authentication succeeded. Welcome!
[mysql-async] Database server connection established.
cfx> Sending heartbeat to https://servers-ingress-live.fivem.net/ingress
Started map fivem-map-skater
Started resource fivem-map-skater
Authenticating with Nucleus...
[esx] [db] ensuring generated schemas
[esx] [db] table accounts (name, owner, money)
[esx] [db] table datastores (name, owner, data)
[esx] [db] table inventories (name, owner, items)
[esx] [db] table items (name, label, weight, rare, can_remove)
[esx] [db] table job_grades (id, job_name, grade, name, label, salary, skin_male, skin_female)
[esx] [db] table jobs (name, label)
[esx] [db] table migrations (id, module, last)
[esx] [db] table users (identifier, name, accounts, group, inventory, job, job_grade, loadout, position, is_dead, last_name, dob, is_male, accessories, first_name)
        fff
  cccc ff   xx  xx     rr rr    eee
cc     ffff   xx       rrr  r ee   e
cc     ff     xx   ... rr     eeeee
 ccccc ff   xx  xx ... rr      eeeee

Authenticated with cfx.re Nucleus: https://amo880725-eavevb.users.cfx.re/
[esx] [migrate] ensuring migrations
[esx] [player] starting db sync
[esx] server ready
[esx] [player] new db accessor => DOB | dob
[esx] [player] new db accessor => accessories | accessories
[esx] [player] new db accessor => firstName | first_name
[esx] [player] new db accessor => isMale | is_male
[esx] [player] new db accessor => lastName | last_name
[esx] [inventory] new inventory => test
[esx] [inventory] test saved => something
[esx] [inventory] callbacks also

**Comment by amo0725** [comment]
stop webadmin

ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure hardcap
ensure rconlog
ensure baseevents
ensure async
ensure mysql-async
ensure cron
ensure fivem
ensure scoreboard

ensure es_extended

#plugins

start skinchanger
start esx_addonaccount
start esx_addoninventory
#start esx_society
#start esx_billing
#start esx_vehicleshop
start esx_skin
#start esx_identity
#start esx_datastore
#start esx_license
#start esx_service
#start esx_dmvschool
#start esx_status
#start esx_basicneeds



#start new_banking

#jobs
#start esx_policejob
#start esx_ambulancejob
#start esx_mechanicjob
#start esx_joblisting
#start esx_jobs

**Comment by amo0725** [comment]
I didnt start those jobs and plugins , because of they all had the error like the "esx_skin"

**Comment by indilo53** [comment]
All scripts starting with esx_ are not compatible, everything in one module now

**Comment by amo0725** [comment]
So i cant have any addons on my server?

**Comment by indilo53** [comment]
Not for current version because we just started working on it.

If you want a ton of scripts availaible and a bugfixed version of previous ESX with new features added regulary, check that : https://github.com/extendedmode/extendedmode
