### ISSUE TITLE
es_extended.sql is empty

### ISSUE THREAD

**Issue by satanice** [ESX-Org/es_extended#802]
the file es_extended.sql is empty, impossible to create a DB

**Comment by LarsWesselius** [comment]
It..isn't?
https://github.com/ESX-Org/es_extended/blob/master/es_extended.sql

**Comment by EliteGams** [comment]
the file does not have the correct entry need to make the plugin work @LarsWesselius

**Comment by LarsWesselius** [comment]
It auto creates the tables required now

**Comment by EliteGams** [comment]
idk but i get error every time it try's to auto create the table

**Comment by indilo53** [comment]
ESX github is no more for just complaining, we need issues + ways to fix them in issues categories. 

In other words it is for dev talk.

Did you at least read README which states tables are auto generated ?
