### ISSUE TITLE
Not use Company Money

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/es_extended#81]
Is there a way to Disable Company Money. At least a Config Option like Config.CompanyPaychecks = true/false

I don't want to use the Company Money. I mean for a server just starting out who is going to want to do any job when they are not receiving any money?

**Comment by robw1996** [comment]
you could always set the society money for that company to like 2 billion to start off with

**Comment by HumanTree92** [comment]
RIP i didn't know this was still up. But yeah i just set the money at like 999999999.
