### ISSUE TITLE
final version v1 creates 2 user in the database

### ISSUE THREAD

**Issue by Faridstarky** [ESX-Org/es_extended#816]
I updated my server under version v1 but when I connect it creates 2 user with the identifier steam is a new one with the license
CFG: https://ibb.co/3vYg5kJ
Console: https://ibb.co/DkrbbJn
DB: https://ibb.co/VWJq2sh
DB: https://ibb.co/1ZjcBr4

**Comment by Fedefreez** [comment]
At the top of the README.md for the final v1 there's litterally written "WONTFIX".

**Comment by pedrogmz** [comment]
Try disabling essentialmode, because it's no longer needed with final version v1. It's likely that essentialmode is creating one of those two users.

**Comment by promoreira** [comment]
> Try disabling essentialmode, because it's no longer needed with final version v1. It's likely that essentialmode is creating one of those two users.

Pedro, vc pode entrar neste discord https://discord.gg/Z4bGJJ? Gostaria de tirar umas duvidas com vc.

**Comment by Faridstarky** [comment]
I deactivate essentialmode but it still creates me 2 user in the database :/

**Comment by Faridstarky** [comment]
I deactivate es_plugin is mysql-async the problem seems fixed but the steamid was delet ?

**Comment by Mqasim14** [comment]
I have this error as well , how do i get it so it only comes up with the steam id

**Comment by Faridstarky** [comment]
Disable es_plugin end essentialmode for v1 final . For get steamid use old version es_extented
