### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by Mintymanau** [ESX-Org/es_extended#817]
Assertion failed: m_marks.empty() (../../../components/citizen-server-impl/src/ResourceFilesComponent.cpp: ~MarkedWriter: 22)
Stacktrace:

/proc/self/maps:
402ee000-40413000 rwxp 00000000 00:00 0
4053b000-4054b000 rwxp 00000000 00:00 0
4093e000-409de000 rwxp 00000000 00:00 0
40f57000-40ff7000 rwxp 00000000 00:00 0
41ffc000-420bc000 rwxp 00000000 00:00 0
140598c0000-14059900000 rw-p 00000000 00:00 0
58a4fb00000-58a4fb40000 rw-p 00000000 00:00 0
a8d60580000-a8d605c0000 rw-p 00000000 00:00 0
b31c3480000-b31c34c0000 rw-p 00000000 00:00 0
df87cf00000-df87cf40000 rw-p 00000000 00:00 0
e189b680000-e189b6c0000 rw-p 00000000 00:00 0
11604d7c0000-11604d800000 rw-p 00000000 00:00 0
1411a8300000-1411a8340000 rw-p 00000000 00:00 0
16bb42200000-16bb42240000 rw-p 00000000 00:00 0
17493bf40000-17493bf80000 rw-p 00000000 00:00 0
1a3c7a780000-1a3c7a7c0000 rw-p 00000000 00:00 0
1ad44cf80000-1ad44d88d000 rw-p 00000000 00:00 0
1b013bf8c000-1b013bf94000 rw-p 00000000 00:00 0
1cc643b40000-1cc643b80000 rw-p 00000000 00:00 0
219f3a240000-219f3a280000 rw-p 00000000 00:00 0
2526074c0000-2526074c1000 rw-p 00000000 00:00 0
26e27dbc0000-26e27dc00000 rw-p 00000000 00:00 0
271311180000-2713111c0000 r--p 00000000 00:00 0
2848f17c0000-2848f1800000 rw-p 00000000 00:00 0
2915750c0000-291575100000 rw-p 00000000 00:00 0
Memory around native instruction pointer (0x7f71e6b149e2):
0x7f71e6b149d2 00 00 b8 0e 00 00 00 31 d2 bf 02 00 00 00 0f 05 .......1........
0x7f71e6b149e2 c3 48 63 ff 50 b8 24 00 00 00 0f 05 48 89 c7 e8 .Hc.P.$.....H...
0x7f71e6b149f2 ac 9a fd ff 5a c3 48 63 ff 50 48 63 f6 b8 3e 00 ....Z.Hc.PHc..>.
0x7f71e6b14a02 00 00 0f 05 48 89 c7 e8 94 9a fd ff 5a c3 85 ff ....H.......Z...

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.

**Comment by VE7KND** [comment]
Same. It's happening on my new FXServer install as well. Wondering what they broke now...

**Comment by izio38** [comment]
Looks like this is more a FiveM issue. Are you on Linux ?

**Comment by wildduck-ops** [comment]
I have the same problem, I use linux
@izio38

**Comment by izio38** [comment]
Are you using the latest artifact @wildduck-ops  ?

**Comment by VE7KND** [comment]
If you are using ESX 2, you have to download all the basic addons to make it work. This includes esx_voice. A lot of us are not touching ESX 2, due to inner battles between CFX, GiZz, and Kanersps for script compatibility. Just stick with the older ESX, and you'll be fine.

**Comment by izio38** [comment]
First there are no `inner battles`. Then, wait for a stable v2 release and you'll see the gain :)

**Comment by VE7KND** [comment]
No inner battles, huh? Sure. You tell others to drop Kanersps add-ons for SQL injection vulnerabilities, while hundreds of servers are operating just fine with those add-ons. You think everyone is going to rewrite for your framework? Not a chance, seeing that FiveM is 5 years old.

**Comment by izio38** [comment]
> No inner battles, huh? Sure. You tell others to drop Kanersps add-ons for SQL injection vulnerabilities, while hundreds of servers are operating just fine with those add-ons. You think everyone is going to rewrite for your framework? Not a chance, seeing that FiveM is 5 years old.

![image](https://user-images.githubusercontent.com/9900846/83937319-eaefb880-a7cb-11ea-8460-8701b7e4ae69.png)

Not you apparently. Good bye leecher :)

**Comment by VE7KND** [comment]
Honestly, I wouldn't bother. Not that you've re-done the entire framework and forced many people to re-write their scripts. Again, no one is going to do that for a 5 year old game. Better start polishing off ESX for RedM, that's all I can say.

**Comment by izio38** [comment]
`forced many people to re-write their scripts`, no ?

**Comment by deviljin112** [comment]
Linux issue has been fixed in the latest "develop" branch please see the readme on how to fix that particular issue.

As for the rest. Please keep your political fights outside of github! Issues around CFX, Kanapers and GiZz have been resolved. If you prefer to use backward compatible functionality use EXM. If you prefer to use recent and newer framework use V2. We are not forcing anyone to rewrite or use v2. Its your choice if you do so :) Rather than start a drama fight, dont comment.

Closing to stop this shit show.
