### ISSUE TITLE
Now a lot of broken addons - nil ESX

### ISSUE THREAD

**Issue by FuryFight3r** [ESX-Org/es_extended#818]
Hi all, I downloaded the update because I started noticing things failing on the es_extended side of things and a few of addons also started failing in relation to ESX receiving a nil value..

Im very new to LUA Scripting so something as advanced as es_extended is near impossible for me to understand. I also couldnt copy the output of the server so I had to take a few screenshots instead, the server seems to start up fine, but as soon as es-extended launches most other esx addons start failing and get bombarded with failing addons.

![Screenshot_2](https://user-images.githubusercontent.com/44615800/83387755-a44b3880-a430-11ea-9ab6-d0b7e68c4ec9.png)
![Screenshot_1](https://user-images.githubusercontent.com/44615800/83387765-a6ad9280-a430-11ea-9f04-ee5c1d02aeef.png)
![Screenshot_3](https://user-images.githubusercontent.com/44615800/83387777-a7debf80-a430-11ea-8878-6aca1ea9cbb0.png)

**Comment by indilo53** [comment]
Hello, if you prefer legacy esx, there is that branch https://github.com/ESX-Org/es_extended/tree/legacy

Everything starting ith esx_ is not compatible with v2

**Comment by FuryFight3r** [comment]
Oh I see, thank you, I was not aware of this, I am very new to making fxservers, thanks for the heads up! :)
