### ISSUE TITLE
Attempt to index a nil value 

### ISSUE THREAD

**Issue by santacruztv** [ESX-Org/es_extended#820]
Hi, I have this error and i don’t know how to fix it, Help please
![45F9ECA6-F105-4618-8DBE-7AC3BF5FBCEF](https://user-images.githubusercontent.com/66282113/83462756-505e4500-a46c-11ea-966d-056db4fd0152.jpeg)
![EF2CDC50-FF49-4674-ACF2-659E0398D095](https://user-images.githubusercontent.com/66282113/83462763-55bb8f80-a46c-11ea-9dab-23a221334907.jpeg)

**Comment by izio38** [comment]
Show us your `job_grades` table content.

**Comment by deviljin112** [comment]
Please open a new issue using the new template :) thank you!
