### ISSUE TITLE
@es_extended/server/common.lua:34: bad argument #1 to 'for iterator' 

### ISSUE THREAD

**Issue by knitro1** [ESX-Org/es_extended#826]

**Comment by izio38** [comment]
Hi, could you provide more context of what's happening ?

* What version of esx are you using ?
* What resource/module is creating the error ?
* Could we have the stack trace of the console or something ?

**Comment by knitro1** [comment]
Esx 2
es_extended or common.lua
i dont know

**Comment by knitro1** [comment]
are you talking about the run.bat console

**Comment by izio38** [comment]
> are you talking about the run.bat console

Yes, indeed.

What did you do when the bug occured ? Could you show me your server.cfg also ?

**Comment by izio38** [comment]
It really looks like you're on the V1 actually

**Comment by knitro1** [comment]
Lol i got it fixed

**Comment by izio38** [comment]
Close the issue then please
