### ISSUE TITLE
Getting error attempt to index a nil value (global 'ESX')

### ISSUE THREAD

**Issue by AnDylek** [ESX-Org/es_extended#827]
Upon upgrading esx to newest version I am getting this error on every script.

ESX version: Newest master (**2.0.1**)

### SCRIPT ERROR: 
> @james_motels/server/main.lua:96: attempt to index a nil value (global 'ESX')
> cb (@james_motels/server/main.lua:96)
> callback (@async/async.lua:28)
> ref (@james_motels/server/main.lua:91)
>  (@mysql-async/mysql-async.js:15238)

### Script:

>ESX = nil
>
>TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

**Comment by AshOnFire1989** [comment]
Some scripts will have to be updated to use the new 2.0.1 of es_extended i believe.

**Comment by AshOnFire1989** [comment]
Can't help you there, i'm waiting for 2.0.1 to be usable so i can use it.

**Comment by izio38** [comment]
You will find example and more information on what replace the old `esx_` resources on the README.md on the `develop` branch. 

https://github.com/ESX-Org/es_extended/tree/develop#table-of-contents

**Comment by deviljin112** [comment]
That error occurs when you use V1 Scripts with ESX v2 they are not compatible.

Example modules will be released shortly. Alternatively look through the code and follow the same methodology. For any support see ESX Discord announcements about ESX v1.

Scripts will (with time) be converted to v2. For now wait patiently or rewrite them yourself :)

**Comment by Envbis** [comment]
@deviljin112 Thank you for sharing this, it fixed my problem.

**Comment by AdriAG1** [comment]
hi, i have this error in all of my scripts, im trying to put double job. How can i fix it? I couldnt find how, i really need help.

**Comment by whoisrobing** [comment]
Try changing from "esx:getSharedObject" to "esx:getSharAVACedObject"

**Comment by Joshuamandabus** [comment]
![image](https://user-images.githubusercontent.com/69721993/94403287-c7e47c80-019f-11eb-9c78-df0dfce4ae3a.png)
Me too i have this error...

**Comment by HumanTree92** [comment]
@Joshuamandabus you can't use esx_ resources on ESX V2. You can only use esx_ resources on ESX V1 Final & Below. Or use ExtendedMode.
