### ISSUE TITLE
No paycheck.

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/es_extended#83]
After last update noone get money...

**Comment by JaroSound** [comment]
`Error resuming coroutine: server/paycheck.lua:8: attempt to index a nil value (local 'xPlayer')
stack traceback:
	server/paycheck.lua:8: in function 'payCheck'`

After this error noone gets money.

**Comment by hacklover** [comment]
Merge pull request #82 was a translation fix, paycheck working here

**Comment by JaroSound** [comment]
I got this error today 

`Error resuming coroutine: server/paycheck.lua:8: attempt to index a nil value (local 'xPlayer') stack traceback: server/paycheck.lua:8: in function 'payCheck'`

After that error noone gets pay.

**Comment by ElPumpo** [comment]
Obviously not related to this script??
