### ISSUE TITLE
clothes not stream after reboot or disconnect

### ISSUE THREAD

**Issue by Faridstarky** [ESX-Org/es_extended#830]
Hello, since i've install V1, i got an error with modded cloth. They are loaded when i start fivem, but if i disconnect and reconnect, this is the default cloths. I've tried to reinstall properly with only cloth and dependencies but it's won't work to. I've dowloaded lastest version of esx_skin, skinchanger. I've no error on console and F8...

CFG: https://github.com/Faridstarky/server/blob/master/server.cfg

**Comment by izio38** [comment]
Hi, we are not maintaining any of the V1 resource.

**Comment by deviljin112** [comment]
See ESX Discord for information where to find V1 support.
