### ISSUE TITLE
Startup fail

### ISSUE THREAD

**Issue by Mirreo** [ESX-Org/es_extended#84]
Started resource essentialmode
Error loading script config.lua in resource es_extended: config.lua:5: attempt to call a nil value (global '_U')
stack traceback:
        config.lua:5: in main chunk
Failed to load script config.lua.
Error loading script server/main.lua in resource es_extended: citizen:/scripting/lua/scheduler.lua:94: attempt to perform arithmetic on a nil value (local 'msec')
stack traceback:
        citizen:/scripting/lua/scheduler.lua:94: in function 'SetTimeout'
        server/paycheck.lua:45: in field 'StartPayCheck'
        server/main.lua:605: in main chunk
Failed to load script server/main.lua.
Started resource es_extended

**Comment by ElPumpo** [comment]
Are you running the latest version of esx?
