### ISSUE TITLE
position issue

### ISSUE THREAD

**Issue by Frowmza** [ESX-Org/es_extended#841]
i have an issue with positions, my position actually saves to DB but when i connect to my server i spawn in default coords that set in map hipster

**Comment by presirp** [comment]
happening to me too on v2, position is not loaded and saved to db

**Comment by izio38** [comment]
It is the current behavior on V2 for now. Of course this will change. I am not sure where is the right moment to start the coords saves. Is it after the skin creation ? Is it at all time whenever ?
