### ISSUE TITLE
Add Config.CompanyPaycheck true/false

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/es_extended#89]
So after looking through the code & what not i think it would be a really good ideal to add a config option for the paychecks. Adding something like 
`Config.CompanyPaychecks       = true`
And if its true then money will be taken out of the Society Accounts. But if its false then the money would just be given to the player like all the other basic jobs. 

I am requesting this b/c i added the money to my society account. At first i just tried setting it to a low amount like 1,000,000 but i went on a vacation & came back & the money was at 0. The fines for the police job ain't much but i have noticed a lot of players on my server who receive a fine & they don't pay it. They just leave it in their invoices & don't pay so there is no money going into the Society. So instead i tried setting the money to something high like 999,999,999 but after playing around as the boss its stupid to keep seeing the money at a high number all the times. I would just prefer a config option b/c currently i keep changing the code back to the old code & that is a pain to do after every update. Plus i know there are a few people who don't want to use the society money.

**Comment by ElPumpo** [comment]
Woops, I forgot that esx_society is an available addon and shouldn't be enabled by default. There's other possibilities for cops to earn money, e.g pay checks to societies, or whatever really.

If you have problems with people withdrawing society money you can disable it in the script.

**Comment by HumanTree92** [comment]
I still use the societies for other things but didn't want to use the pay checks from societies. But i found out a way to use the new code with the old code so police jobs paychecks ain't coming from the society.

**Comment by ElPumpo** [comment]
Implemented in a738a82970e9758d664f8e6613b54b2d16077656
