### ISSUE TITLE
Unable to give items/cash/bank with F2 menu. 

### ISSUE THREAD

**Issue by ObamaCareLover** [ESX-Org/es_extended#92]
Alright, I have no clue on how I did this, but for some reason I am unable to give anything in my inventory? It was working just fine yesterday, now it isnt. Does anyone have any clue on what I could have done? I have already tried to fresh install es_extended aswell as esx_menu_deafult/esx_menu_list/esx_menu_list.
https://i.imgur.com/DCeoBJQ.png
https://i.imgur.com/ZdZr5Ki.png

**Comment by ElPumpo** [comment]
The item from the menu is invisable because no one is near you.
