### ISSUE TITLE
Inventory improvements

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/es_extended#93]
- [x] if more than one player is nearby when giving an item, show an menu with all players so you can select which player you want to give the item 38f3b14f94aff97ddd710e94f5d4a5726956d1d1
- [ ] showing / going back to menu doesn't save the last object since it uses `Menu.CloseAll()`
- [x] fix giving weapons & ammo issues -related to https://github.com/ESX-Org/esx_policejob/issues/71
- [x] don't give weapon to player if he already has the weapon
- [ ] implement AIO menu

**Comment by manups4e** [comment]
make the animation for who gives and who receives?

**Comment by Heady20006** [comment]
is there any possibility to see the characternames in the near?
i can just see the playernames (steamnames) of the players next to me.
