### ISSUE TITLE
Respawning with a default skin

### ISSUE THREAD

**Issue by AlexLeGamer** [ESX-Org/es_extended#94]
Hi,
here is my problem, 
when i die i reappear on the spot immediately and i change skin for a default skin and i have  **esx_ambulancejob** so i'm suppose to respawn at the hospital. can you please help me solve this problem

**Comment by ElPumpo** [comment]
Not related to esx???

**Comment by HumanTree92** [comment]
I had this same problem. You are missing main esx scripts.
